//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
//
#pragma warning disable 1591

namespace AvukatProLib.pttSorgu
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void gonderiHareketBarkodSorguCompletedEventHandler(object sender, gonderiHareketBarkodSorguCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void gonderiHareketIslemTarihiSorguCompletedEventHandler(object sender, gonderiHareketIslemTarihiSorguCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gonderiHareketBarkodSorguCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal gonderiHareketBarkodSorguCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public OutputTum Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OutputTum)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gonderiHareketIslemTarihiSorguCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal gonderiHareketIslemTarihiSorguCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public OutputTum Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OutputTum)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hareket.ptt.gov.tr")]
    public partial class InputBarkod
    {
        private string barkod_devamField;

        private string ilk_barkodField;

        private string kullaniciField;

        private string kurum_rumuzField;

        private System.Nullable<int> musteri_idField;

        private string sifreField;

        private string son_barkodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string barkod_devam
        {
            get
            {
                return this.barkod_devamField;
            }
            set
            {
                this.barkod_devamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ilk_barkod
        {
            get
            {
                return this.ilk_barkodField;
            }
            set
            {
                this.ilk_barkodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kullanici
        {
            get
            {
                return this.kullaniciField;
            }
            set
            {
                this.kullaniciField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kurum_rumuz
        {
            get
            {
                return this.kurum_rumuzField;
            }
            set
            {
                this.kurum_rumuzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> musteri_id
        {
            get
            {
                return this.musteri_idField;
            }
            set
            {
                this.musteri_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string sifre
        {
            get
            {
                return this.sifreField;
            }
            set
            {
                this.sifreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string son_barkod
        {
            get
            {
                return this.son_barkodField;
            }
            set
            {
                this.son_barkodField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hareket.ptt.gov.tr")]
    public partial class InputTarih
    {
        private string kullaniciField;

        private string kurum_rumuzField;

        private System.Nullable<int> musteri_idField;

        private string sifreField;

        private System.Nullable<int> son_islem_tarihiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kullanici
        {
            get
            {
                return this.kullaniciField;
            }
            set
            {
                this.kullaniciField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kurum_rumuz
        {
            get
            {
                return this.kurum_rumuzField;
            }
            set
            {
                this.kurum_rumuzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> musteri_id
        {
            get
            {
                return this.musteri_idField;
            }
            set
            {
                this.musteri_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string sifre
        {
            get
            {
                return this.sifreField;
            }
            set
            {
                this.sifreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> son_islem_tarihi
        {
            get
            {
                return this.son_islem_tarihiField;
            }
            set
            {
                this.son_islem_tarihiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hareket.ptt.gov.tr")]
    public partial class Output
    {
        private string agirlikField;

        private string barkod_noField;

        private string boyField;

        private string deger_konulmus_ucretField;

        private string desiField;

        private string dosya_adiField;

        private string ek_hizmetField;

        private string enField;

        private string gerceklesen_ziyaret_sayisiField;

        private string gonderi_durum_aciklamaField;

        private string gonderi_durumuField;

        private string iade_tarihiField;

        private string kabul_il_adField;

        private string kabul_merkeziField;

        private string kabul_saatiField;

        private string kabul_tarihiField;

        private string musteri_idField;

        private string musteri_referans_noField;

        private string odeme_sartli_ucretField;

        private string posta_cekiField;

        private string ptt_teslim_tarihiField;

        private string rezerve1Field;

        private string rezerve2Field;

        private string rezerve3Field;

        private string rezerve4Field;

        private string rezerve5Field;

        private string siparis_idField;

        private string son_islem_il_adiField;

        private string son_islem_merkez_adiField;

        private string son_islem_saatiField;

        private string son_islem_tarihiField;

        private string talimat_durumField;

        private string teslim_alanField;

        private string yukseklikField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string agirlik
        {
            get
            {
                return this.agirlikField;
            }
            set
            {
                this.agirlikField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string barkod_no
        {
            get
            {
                return this.barkod_noField;
            }
            set
            {
                this.barkod_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string boy
        {
            get
            {
                return this.boyField;
            }
            set
            {
                this.boyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string deger_konulmus_ucret
        {
            get
            {
                return this.deger_konulmus_ucretField;
            }
            set
            {
                this.deger_konulmus_ucretField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string desi
        {
            get
            {
                return this.desiField;
            }
            set
            {
                this.desiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string dosya_adi
        {
            get
            {
                return this.dosya_adiField;
            }
            set
            {
                this.dosya_adiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ek_hizmet
        {
            get
            {
                return this.ek_hizmetField;
            }
            set
            {
                this.ek_hizmetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string en
        {
            get
            {
                return this.enField;
            }
            set
            {
                this.enField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string gerceklesen_ziyaret_sayisi
        {
            get
            {
                return this.gerceklesen_ziyaret_sayisiField;
            }
            set
            {
                this.gerceklesen_ziyaret_sayisiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string gonderi_durum_aciklama
        {
            get
            {
                return this.gonderi_durum_aciklamaField;
            }
            set
            {
                this.gonderi_durum_aciklamaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string gonderi_durumu
        {
            get
            {
                return this.gonderi_durumuField;
            }
            set
            {
                this.gonderi_durumuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string iade_tarihi
        {
            get
            {
                return this.iade_tarihiField;
            }
            set
            {
                this.iade_tarihiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kabul_il_ad
        {
            get
            {
                return this.kabul_il_adField;
            }
            set
            {
                this.kabul_il_adField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kabul_merkezi
        {
            get
            {
                return this.kabul_merkeziField;
            }
            set
            {
                this.kabul_merkeziField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kabul_saati
        {
            get
            {
                return this.kabul_saatiField;
            }
            set
            {
                this.kabul_saatiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kabul_tarihi
        {
            get
            {
                return this.kabul_tarihiField;
            }
            set
            {
                this.kabul_tarihiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string musteri_id
        {
            get
            {
                return this.musteri_idField;
            }
            set
            {
                this.musteri_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string musteri_referans_no
        {
            get
            {
                return this.musteri_referans_noField;
            }
            set
            {
                this.musteri_referans_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string odeme_sartli_ucret
        {
            get
            {
                return this.odeme_sartli_ucretField;
            }
            set
            {
                this.odeme_sartli_ucretField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string posta_ceki
        {
            get
            {
                return this.posta_cekiField;
            }
            set
            {
                this.posta_cekiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ptt_teslim_tarihi
        {
            get
            {
                return this.ptt_teslim_tarihiField;
            }
            set
            {
                this.ptt_teslim_tarihiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerve1
        {
            get
            {
                return this.rezerve1Field;
            }
            set
            {
                this.rezerve1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerve2
        {
            get
            {
                return this.rezerve2Field;
            }
            set
            {
                this.rezerve2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerve3
        {
            get
            {
                return this.rezerve3Field;
            }
            set
            {
                this.rezerve3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerve4
        {
            get
            {
                return this.rezerve4Field;
            }
            set
            {
                this.rezerve4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerve5
        {
            get
            {
                return this.rezerve5Field;
            }
            set
            {
                this.rezerve5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string siparis_id
        {
            get
            {
                return this.siparis_idField;
            }
            set
            {
                this.siparis_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string son_islem_il_adi
        {
            get
            {
                return this.son_islem_il_adiField;
            }
            set
            {
                this.son_islem_il_adiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string son_islem_merkez_adi
        {
            get
            {
                return this.son_islem_merkez_adiField;
            }
            set
            {
                this.son_islem_merkez_adiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string son_islem_saati
        {
            get
            {
                return this.son_islem_saatiField;
            }
            set
            {
                this.son_islem_saatiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string son_islem_tarihi
        {
            get
            {
                return this.son_islem_tarihiField;
            }
            set
            {
                this.son_islem_tarihiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string talimat_durum
        {
            get
            {
                return this.talimat_durumField;
            }
            set
            {
                this.talimat_durumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string teslim_alan
        {
            get
            {
                return this.teslim_alanField;
            }
            set
            {
                this.teslim_alanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string yukseklik
        {
            get
            {
                return this.yukseklikField;
            }
            set
            {
                this.yukseklikField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://hareket.ptt.gov.tr")]
    public partial class OutputTum
    {
        private string aciklamaField;

        private string barkod_devamField;

        private Output[] donguField;

        private System.Nullable<int> rcodeField;

        private System.Nullable<int> sqlcodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string barkod_devam
        {
            get
            {
                return this.barkod_devamField;
            }
            set
            {
                this.barkod_devamField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
        public Output[] dongu
        {
            get
            {
                return this.donguField;
            }
            set
            {
                this.donguField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> rcode
        {
            get
            {
                return this.rcodeField;
            }
            set
            {
                this.rcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> sqlcode
        {
            get
            {
                return this.sqlcodeField;
            }
            set
            {
                this.sqlcodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SorguSoapBinding", Namespace = "http://hareket.ptt.gov.tr")]
    public partial class SorguService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        /// <remarks/>
        public SorguService()
        {
            this.Url = global::AvukatProLib.Properties.Settings.Default.AvukatProLib_pttSorgu_SorguService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        private System.Threading.SendOrPostCallback gonderiHareketBarkodSorguOperationCompleted;
        private System.Threading.SendOrPostCallback gonderiHareketIslemTarihiSorguOperationCompleted;
        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public event gonderiHareketBarkodSorguCompletedEventHandler gonderiHareketBarkodSorguCompleted;

        /// <remarks/>
        public event gonderiHareketIslemTarihiSorguCompletedEventHandler gonderiHareketIslemTarihiSorguCompleted;

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gonderiHareketBarkodSorguReturn", Namespace = "http://hareket.ptt.gov.tr")]
        public OutputTum gonderiHareketBarkodSorgu([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://hareket.ptt.gov.tr")] InputBarkod input1)
        {
            object[] results = this.Invoke("gonderiHareketBarkodSorgu", new object[] {
                        input1});
            return ((OutputTum)(results[0]));
        }

        /// <remarks/>
        public void gonderiHareketBarkodSorguAsync(InputBarkod input1)
        {
            this.gonderiHareketBarkodSorguAsync(input1, null);
        }

        /// <remarks/>
        public void gonderiHareketBarkodSorguAsync(InputBarkod input1, object userState)
        {
            if ((this.gonderiHareketBarkodSorguOperationCompleted == null))
            {
                this.gonderiHareketBarkodSorguOperationCompleted = new System.Threading.SendOrPostCallback(this.OngonderiHareketBarkodSorguOperationCompleted);
            }
            this.InvokeAsync("gonderiHareketBarkodSorgu", new object[] {
                        input1}, this.gonderiHareketBarkodSorguOperationCompleted, userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gonderiHareketIslemTarihiSorguReturn", Namespace = "http://hareket.ptt.gov.tr")]
        public OutputTum gonderiHareketIslemTarihiSorgu([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://hareket.ptt.gov.tr")] InputTarih input)
        {
            object[] results = this.Invoke("gonderiHareketIslemTarihiSorgu", new object[] {
                        input});
            return ((OutputTum)(results[0]));
        }

        /// <remarks/>
        public void gonderiHareketIslemTarihiSorguAsync(InputTarih input)
        {
            this.gonderiHareketIslemTarihiSorguAsync(input, null);
        }

        /// <remarks/>
        public void gonderiHareketIslemTarihiSorguAsync(InputTarih input, object userState)
        {
            if ((this.gonderiHareketIslemTarihiSorguOperationCompleted == null))
            {
                this.gonderiHareketIslemTarihiSorguOperationCompleted = new System.Threading.SendOrPostCallback(this.OngonderiHareketIslemTarihiSorguOperationCompleted);
            }
            this.InvokeAsync("gonderiHareketIslemTarihiSorgu", new object[] {
                        input}, this.gonderiHareketIslemTarihiSorguOperationCompleted, userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }

        private void OngonderiHareketBarkodSorguOperationCompleted(object arg)
        {
            if ((this.gonderiHareketBarkodSorguCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gonderiHareketBarkodSorguCompleted(this, new gonderiHareketBarkodSorguCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        private void OngonderiHareketIslemTarihiSorguOperationCompleted(object arg)
        {
            if ((this.gonderiHareketIslemTarihiSorguCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gonderiHareketIslemTarihiSorguCompleted(this, new gonderiHareketIslemTarihiSorguCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
}

#pragma warning restore 1591