//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
//
#pragma warning disable 1591

namespace ServerSideServices.pttTopluSorgulamaV2
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void gonderiSorgulaCompletedEventHandler(object sender, gonderiSorgulaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kp.ptt.gov.tr/xsd")]
    public partial class GonderiSafahat
    {
        private string bARKODField;

        private string iMERKField;

        private string iSLEMField;

        private string iTARIHField;

        private string rEZERVE_SONUC1Field;

        private string rEZERVE_SONUC2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BARKOD
        {
            get
            {
                return this.bARKODField;
            }
            set
            {
                this.bARKODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IMERK
        {
            get
            {
                return this.iMERKField;
            }
            set
            {
                this.iMERKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ISLEM
        {
            get
            {
                return this.iSLEMField;
            }
            set
            {
                this.iSLEMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ITARIH
        {
            get
            {
                return this.iTARIHField;
            }
            set
            {
                this.iTARIHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string REZERVE_SONUC1
        {
            get
            {
                return this.rEZERVE_SONUC1Field;
            }
            set
            {
                this.rEZERVE_SONUC1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string REZERVE_SONUC2
        {
            get
            {
                return this.rEZERVE_SONUC2Field;
            }
            set
            {
                this.rEZERVE_SONUC2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gonderiSorgulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal gonderiSorgulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public KurumRumuzSorgu Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((KurumRumuzSorgu)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GonderiTakipSoap11Binding", Namespace = "http://kp.ptt.gov.tr")]
    public partial class GonderiTakip : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        /// <remarks/>
        public GonderiTakip()
        {
            this.Url = global::ServerSideServices.Properties.Settings.Default.ServerSideServices_pttTopluSorgulamaV2_GonderiTakip;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        private System.Threading.SendOrPostCallback gonderiSorgulaOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public event gonderiSorgulaCompletedEventHandler gonderiSorgulaCompleted;

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:gonderiSorgula", RequestNamespace = "http://kp.ptt.gov.tr", ResponseNamespace = "http://kp.ptt.gov.tr", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
        public KurumRumuzSorgu gonderiSorgula([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] KurumRumuzSorguInput input)
        {
            object[] results = this.Invoke("gonderiSorgula", new object[] {
                        input});
            return ((KurumRumuzSorgu)(results[0]));
        }

        /// <remarks/>
        public void gonderiSorgulaAsync(KurumRumuzSorguInput input)
        {
            this.gonderiSorgulaAsync(input, null);
        }

        /// <remarks/>
        public void gonderiSorgulaAsync(KurumRumuzSorguInput input, object userState)
        {
            if ((this.gonderiSorgulaOperationCompleted == null))
            {
                this.gonderiSorgulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngonderiSorgulaOperationCompleted);
            }
            this.InvokeAsync("gonderiSorgula", new object[] {
                        input}, this.gonderiSorgulaOperationCompleted, userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }

        private void OngonderiSorgulaOperationCompleted(object arg)
        {
            if ((this.gonderiSorgulaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gonderiSorgulaCompleted(this, new gonderiSorgulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kp.ptt.gov.tr/xsd")]
    public partial class KurumRumuzSorgu
    {
        private int musteri_idField;
        private bool musteri_idFieldSpecified;
        private GonderiSafahat[] safahatlarField;
        private string sONUCField;

        /// <remarks/>
        public int musteri_id
        {
            get
            {
                return this.musteri_idField;
            }
            set
            {
                this.musteri_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool musteri_idSpecified
        {
            get
            {
                return this.musteri_idFieldSpecified;
            }
            set
            {
                this.musteri_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("safahatlar", IsNullable = true)]
        public GonderiSafahat[] safahatlar
        {
            get
            {
                return this.safahatlarField;
            }
            set
            {
                this.safahatlarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SONUC
        {
            get
            {
                return this.sONUCField;
            }
            set
            {
                this.sONUCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kp.ptt.gov.tr/xsd")]
    public partial class KurumRumuzSorguInput
    {
        private string ilk_BarkodField;

        private int musteriIdField;

        private bool musteriIdFieldSpecified;

        private string rezerv1Field;

        private string rezerv2Field;

        private string rezerv3Field;

        private string son_BarkodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ilk_Barkod
        {
            get
            {
                return this.ilk_BarkodField;
            }
            set
            {
                this.ilk_BarkodField = value;
            }
        }

        /// <remarks/>
        public int musteriId
        {
            get
            {
                return this.musteriIdField;
            }
            set
            {
                this.musteriIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool musteriIdSpecified
        {
            get
            {
                return this.musteriIdFieldSpecified;
            }
            set
            {
                this.musteriIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerv1
        {
            get
            {
                return this.rezerv1Field;
            }
            set
            {
                this.rezerv1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerv2
        {
            get
            {
                return this.rezerv2Field;
            }
            set
            {
                this.rezerv2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string rezerv3
        {
            get
            {
                return this.rezerv3Field;
            }
            set
            {
                this.rezerv3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string son_Barkod
        {
            get
            {
                return this.son_BarkodField;
            }
            set
            {
                this.son_BarkodField = value;
            }
        }
    }
}

#pragma warning restore 1591