#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvpErrorHandlerService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AVP_MYS")]
	public partial class ErrorHandlerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTMYS_EXE_SURUM(TMYS_EXE_SURUM instance);
    partial void UpdateTMYS_EXE_SURUM(TMYS_EXE_SURUM instance);
    partial void DeleteTMYS_EXE_SURUM(TMYS_EXE_SURUM instance);
    partial void InsertTMYS_DB_SURUM(TMYS_DB_SURUM instance);
    partial void UpdateTMYS_DB_SURUM(TMYS_DB_SURUM instance);
    partial void DeleteTMYS_DB_SURUM(TMYS_DB_SURUM instance);
    partial void InsertTMYS_HATA_RAPORU(TMYS_HATA_RAPORU instance);
    partial void UpdateTMYS_HATA_RAPORU(TMYS_HATA_RAPORU instance);
    partial void DeleteTMYS_HATA_RAPORU(TMYS_HATA_RAPORU instance);
    #endregion
		
		public ErrorHandlerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AVP_MYSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ErrorHandlerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ErrorHandlerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ErrorHandlerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ErrorHandlerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TMYS_EXE_SURUM> TMYS_EXE_SURUMs
		{
			get
			{
				return this.GetTable<TMYS_EXE_SURUM>();
			}
		}
		
		public System.Data.Linq.Table<TMYS_DB_SURUM> TMYS_DB_SURUMs
		{
			get
			{
				return this.GetTable<TMYS_DB_SURUM>();
			}
		}
		
		public System.Data.Linq.Table<TMYS_HATA_RAPORU> TMYS_HATA_RAPORUs
		{
			get
			{
				return this.GetTable<TMYS_HATA_RAPORU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMYS_EXE_SURUM")]
	public partial class TMYS_EXE_SURUM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SURUM;
		
		private string _SURUM_NOTLARI;
		
		private string _INDIRME_ADRESI;
		
		private System.DateTime _CIKIS_TARIHI;
		
		private bool _BIR_ONCEKI_SURUM_GEREKLI;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private byte _DURUM;
		
		private System.Nullable<int> _DB_SURUM_ID;
		
		private System.Guid _EUID;
		
		private EntitySet<TMYS_HATA_RAPORU> _TMYS_HATA_RAPORUs;
		
		private EntityRef<TMYS_DB_SURUM> _TMYS_DB_SURUM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSURUMChanging(string value);
    partial void OnSURUMChanged();
    partial void OnSURUM_NOTLARIChanging(string value);
    partial void OnSURUM_NOTLARIChanged();
    partial void OnINDIRME_ADRESIChanging(string value);
    partial void OnINDIRME_ADRESIChanged();
    partial void OnCIKIS_TARIHIChanging(System.DateTime value);
    partial void OnCIKIS_TARIHIChanged();
    partial void OnBIR_ONCEKI_SURUM_GEREKLIChanging(bool value);
    partial void OnBIR_ONCEKI_SURUM_GEREKLIChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnDURUMChanging(byte value);
    partial void OnDURUMChanged();
    partial void OnDB_SURUM_IDChanging(System.Nullable<int> value);
    partial void OnDB_SURUM_IDChanged();
    partial void OnEUIDChanging(System.Guid value);
    partial void OnEUIDChanged();
    #endregion
		
		public TMYS_EXE_SURUM()
		{
			this._TMYS_HATA_RAPORUs = new EntitySet<TMYS_HATA_RAPORU>(new Action<TMYS_HATA_RAPORU>(this.attach_TMYS_HATA_RAPORUs), new Action<TMYS_HATA_RAPORU>(this.detach_TMYS_HATA_RAPORUs));
			this._TMYS_DB_SURUM = default(EntityRef<TMYS_DB_SURUM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURUM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SURUM
		{
			get
			{
				return this._SURUM;
			}
			set
			{
				if ((this._SURUM != value))
				{
					this.OnSURUMChanging(value);
					this.SendPropertyChanging();
					this._SURUM = value;
					this.SendPropertyChanged("SURUM");
					this.OnSURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURUM_NOTLARI", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SURUM_NOTLARI
		{
			get
			{
				return this._SURUM_NOTLARI;
			}
			set
			{
				if ((this._SURUM_NOTLARI != value))
				{
					this.OnSURUM_NOTLARIChanging(value);
					this.SendPropertyChanging();
					this._SURUM_NOTLARI = value;
					this.SendPropertyChanged("SURUM_NOTLARI");
					this.OnSURUM_NOTLARIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDIRME_ADRESI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string INDIRME_ADRESI
		{
			get
			{
				return this._INDIRME_ADRESI;
			}
			set
			{
				if ((this._INDIRME_ADRESI != value))
				{
					this.OnINDIRME_ADRESIChanging(value);
					this.SendPropertyChanging();
					this._INDIRME_ADRESI = value;
					this.SendPropertyChanged("INDIRME_ADRESI");
					this.OnINDIRME_ADRESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime CIKIS_TARIHI
		{
			get
			{
				return this._CIKIS_TARIHI;
			}
			set
			{
				if ((this._CIKIS_TARIHI != value))
				{
					this.OnCIKIS_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._CIKIS_TARIHI = value;
					this.SendPropertyChanged("CIKIS_TARIHI");
					this.OnCIKIS_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIR_ONCEKI_SURUM_GEREKLI", DbType="Bit NOT NULL")]
		public bool BIR_ONCEKI_SURUM_GEREKLI
		{
			get
			{
				return this._BIR_ONCEKI_SURUM_GEREKLI;
			}
			set
			{
				if ((this._BIR_ONCEKI_SURUM_GEREKLI != value))
				{
					this.OnBIR_ONCEKI_SURUM_GEREKLIChanging(value);
					this.SendPropertyChanging();
					this._BIR_ONCEKI_SURUM_GEREKLI = value;
					this.SendPropertyChanged("BIR_ONCEKI_SURUM_GEREKLI");
					this.OnBIR_ONCEKI_SURUM_GEREKLIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="TinyInt NOT NULL")]
		public byte DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_SURUM_ID", DbType="Int")]
		public System.Nullable<int> DB_SURUM_ID
		{
			get
			{
				return this._DB_SURUM_ID;
			}
			set
			{
				if ((this._DB_SURUM_ID != value))
				{
					if (this._TMYS_DB_SURUM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDB_SURUM_IDChanging(value);
					this.SendPropertyChanging();
					this._DB_SURUM_ID = value;
					this.SendPropertyChanged("DB_SURUM_ID");
					this.OnDB_SURUM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EUID
		{
			get
			{
				return this._EUID;
			}
			set
			{
				if ((this._EUID != value))
				{
					this.OnEUIDChanging(value);
					this.SendPropertyChanging();
					this._EUID = value;
					this.SendPropertyChanged("EUID");
					this.OnEUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_EXE_SURUM_TMYS_HATA_RAPORU", Storage="_TMYS_HATA_RAPORUs", ThisKey="ID", OtherKey="EXE_SURUM_ID")]
		public EntitySet<TMYS_HATA_RAPORU> TMYS_HATA_RAPORUs
		{
			get
			{
				return this._TMYS_HATA_RAPORUs;
			}
			set
			{
				this._TMYS_HATA_RAPORUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_DB_SURUM_TMYS_EXE_SURUM", Storage="_TMYS_DB_SURUM", ThisKey="DB_SURUM_ID", OtherKey="ID", IsForeignKey=true)]
		public TMYS_DB_SURUM TMYS_DB_SURUM
		{
			get
			{
				return this._TMYS_DB_SURUM.Entity;
			}
			set
			{
				TMYS_DB_SURUM previousValue = this._TMYS_DB_SURUM.Entity;
				if (((previousValue != value) 
							|| (this._TMYS_DB_SURUM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMYS_DB_SURUM.Entity = null;
						previousValue.TMYS_EXE_SURUMs.Remove(this);
					}
					this._TMYS_DB_SURUM.Entity = value;
					if ((value != null))
					{
						value.TMYS_EXE_SURUMs.Add(this);
						this._DB_SURUM_ID = value.ID;
					}
					else
					{
						this._DB_SURUM_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TMYS_DB_SURUM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TMYS_HATA_RAPORUs(TMYS_HATA_RAPORU entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_EXE_SURUM = this;
		}
		
		private void detach_TMYS_HATA_RAPORUs(TMYS_HATA_RAPORU entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_EXE_SURUM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMYS_DB_SURUM")]
	public partial class TMYS_DB_SURUM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SURUM;
		
		private string _SURUM_NOTLARI;
		
		private string _INDIRME_ADRESI;
		
		private System.DateTime _CIKIS_TARIHI;
		
		private bool _BIR_ONCEKI_SURUM_GEREKLI;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private byte _DURUM;
		
		private System.Guid _EUID;
		
		private EntitySet<TMYS_EXE_SURUM> _TMYS_EXE_SURUMs;
		
		private EntitySet<TMYS_HATA_RAPORU> _TMYS_HATA_RAPORUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSURUMChanging(string value);
    partial void OnSURUMChanged();
    partial void OnSURUM_NOTLARIChanging(string value);
    partial void OnSURUM_NOTLARIChanged();
    partial void OnINDIRME_ADRESIChanging(string value);
    partial void OnINDIRME_ADRESIChanged();
    partial void OnCIKIS_TARIHIChanging(System.DateTime value);
    partial void OnCIKIS_TARIHIChanged();
    partial void OnBIR_ONCEKI_SURUM_GEREKLIChanging(bool value);
    partial void OnBIR_ONCEKI_SURUM_GEREKLIChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnDURUMChanging(byte value);
    partial void OnDURUMChanged();
    partial void OnEUIDChanging(System.Guid value);
    partial void OnEUIDChanged();
    #endregion
		
		public TMYS_DB_SURUM()
		{
			this._TMYS_EXE_SURUMs = new EntitySet<TMYS_EXE_SURUM>(new Action<TMYS_EXE_SURUM>(this.attach_TMYS_EXE_SURUMs), new Action<TMYS_EXE_SURUM>(this.detach_TMYS_EXE_SURUMs));
			this._TMYS_HATA_RAPORUs = new EntitySet<TMYS_HATA_RAPORU>(new Action<TMYS_HATA_RAPORU>(this.attach_TMYS_HATA_RAPORUs), new Action<TMYS_HATA_RAPORU>(this.detach_TMYS_HATA_RAPORUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURUM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SURUM
		{
			get
			{
				return this._SURUM;
			}
			set
			{
				if ((this._SURUM != value))
				{
					this.OnSURUMChanging(value);
					this.SendPropertyChanging();
					this._SURUM = value;
					this.SendPropertyChanged("SURUM");
					this.OnSURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURUM_NOTLARI", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SURUM_NOTLARI
		{
			get
			{
				return this._SURUM_NOTLARI;
			}
			set
			{
				if ((this._SURUM_NOTLARI != value))
				{
					this.OnSURUM_NOTLARIChanging(value);
					this.SendPropertyChanging();
					this._SURUM_NOTLARI = value;
					this.SendPropertyChanged("SURUM_NOTLARI");
					this.OnSURUM_NOTLARIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDIRME_ADRESI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string INDIRME_ADRESI
		{
			get
			{
				return this._INDIRME_ADRESI;
			}
			set
			{
				if ((this._INDIRME_ADRESI != value))
				{
					this.OnINDIRME_ADRESIChanging(value);
					this.SendPropertyChanging();
					this._INDIRME_ADRESI = value;
					this.SendPropertyChanged("INDIRME_ADRESI");
					this.OnINDIRME_ADRESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime CIKIS_TARIHI
		{
			get
			{
				return this._CIKIS_TARIHI;
			}
			set
			{
				if ((this._CIKIS_TARIHI != value))
				{
					this.OnCIKIS_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._CIKIS_TARIHI = value;
					this.SendPropertyChanged("CIKIS_TARIHI");
					this.OnCIKIS_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIR_ONCEKI_SURUM_GEREKLI", DbType="Bit NOT NULL")]
		public bool BIR_ONCEKI_SURUM_GEREKLI
		{
			get
			{
				return this._BIR_ONCEKI_SURUM_GEREKLI;
			}
			set
			{
				if ((this._BIR_ONCEKI_SURUM_GEREKLI != value))
				{
					this.OnBIR_ONCEKI_SURUM_GEREKLIChanging(value);
					this.SendPropertyChanging();
					this._BIR_ONCEKI_SURUM_GEREKLI = value;
					this.SendPropertyChanged("BIR_ONCEKI_SURUM_GEREKLI");
					this.OnBIR_ONCEKI_SURUM_GEREKLIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="TinyInt NOT NULL")]
		public byte DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EUID
		{
			get
			{
				return this._EUID;
			}
			set
			{
				if ((this._EUID != value))
				{
					this.OnEUIDChanging(value);
					this.SendPropertyChanging();
					this._EUID = value;
					this.SendPropertyChanged("EUID");
					this.OnEUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_DB_SURUM_TMYS_EXE_SURUM", Storage="_TMYS_EXE_SURUMs", ThisKey="ID", OtherKey="DB_SURUM_ID")]
		public EntitySet<TMYS_EXE_SURUM> TMYS_EXE_SURUMs
		{
			get
			{
				return this._TMYS_EXE_SURUMs;
			}
			set
			{
				this._TMYS_EXE_SURUMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_DB_SURUM_TMYS_HATA_RAPORU", Storage="_TMYS_HATA_RAPORUs", ThisKey="ID", OtherKey="DB_SURUM_ID")]
		public EntitySet<TMYS_HATA_RAPORU> TMYS_HATA_RAPORUs
		{
			get
			{
				return this._TMYS_HATA_RAPORUs;
			}
			set
			{
				this._TMYS_HATA_RAPORUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TMYS_EXE_SURUMs(TMYS_EXE_SURUM entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_DB_SURUM = this;
		}
		
		private void detach_TMYS_EXE_SURUMs(TMYS_EXE_SURUM entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_DB_SURUM = null;
		}
		
		private void attach_TMYS_HATA_RAPORUs(TMYS_HATA_RAPORU entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_DB_SURUM = this;
		}
		
		private void detach_TMYS_HATA_RAPORUs(TMYS_HATA_RAPORU entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_DB_SURUM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMYS_HATA_RAPORU")]
	public partial class TMYS_HATA_RAPORU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KIMDEN;
		
		private System.DateTime _NE_ZAMAN;
		
		private string _GONDEREN_EMAIL;
		
		private string _GONDEREN_NOTU;
		
		private string _HATA_RAPORU;
		
		private System.Nullable<int> _EXE_SURUM_ID;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private System.Nullable<int> _DB_SURUM_ID;
		
		private byte _DURUM;
		
		private EntityRef<TMYS_DB_SURUM> _TMYS_DB_SURUM;
		
		private EntityRef<TMYS_EXE_SURUM> _TMYS_EXE_SURUM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKIMDENChanging(string value);
    partial void OnKIMDENChanged();
    partial void OnNE_ZAMANChanging(System.DateTime value);
    partial void OnNE_ZAMANChanged();
    partial void OnGONDEREN_EMAILChanging(string value);
    partial void OnGONDEREN_EMAILChanged();
    partial void OnGONDEREN_NOTUChanging(string value);
    partial void OnGONDEREN_NOTUChanged();
    partial void OnHATA_RAPORUChanging(string value);
    partial void OnHATA_RAPORUChanged();
    partial void OnEXE_SURUM_IDChanging(System.Nullable<int> value);
    partial void OnEXE_SURUM_IDChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnDB_SURUM_IDChanging(System.Nullable<int> value);
    partial void OnDB_SURUM_IDChanged();
    partial void OnDURUMChanging(byte value);
    partial void OnDURUMChanged();
    #endregion
		
		public TMYS_HATA_RAPORU()
		{
			this._TMYS_DB_SURUM = default(EntityRef<TMYS_DB_SURUM>);
			this._TMYS_EXE_SURUM = default(EntityRef<TMYS_EXE_SURUM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIMDEN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string KIMDEN
		{
			get
			{
				return this._KIMDEN;
			}
			set
			{
				if ((this._KIMDEN != value))
				{
					this.OnKIMDENChanging(value);
					this.SendPropertyChanging();
					this._KIMDEN = value;
					this.SendPropertyChanged("KIMDEN");
					this.OnKIMDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NE_ZAMAN", DbType="DateTime NOT NULL")]
		public System.DateTime NE_ZAMAN
		{
			get
			{
				return this._NE_ZAMAN;
			}
			set
			{
				if ((this._NE_ZAMAN != value))
				{
					this.OnNE_ZAMANChanging(value);
					this.SendPropertyChanging();
					this._NE_ZAMAN = value;
					this.SendPropertyChanged("NE_ZAMAN");
					this.OnNE_ZAMANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONDEREN_EMAIL", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string GONDEREN_EMAIL
		{
			get
			{
				return this._GONDEREN_EMAIL;
			}
			set
			{
				if ((this._GONDEREN_EMAIL != value))
				{
					this.OnGONDEREN_EMAILChanging(value);
					this.SendPropertyChanging();
					this._GONDEREN_EMAIL = value;
					this.SendPropertyChanged("GONDEREN_EMAIL");
					this.OnGONDEREN_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GONDEREN_NOTU", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string GONDEREN_NOTU
		{
			get
			{
				return this._GONDEREN_NOTU;
			}
			set
			{
				if ((this._GONDEREN_NOTU != value))
				{
					this.OnGONDEREN_NOTUChanging(value);
					this.SendPropertyChanging();
					this._GONDEREN_NOTU = value;
					this.SendPropertyChanged("GONDEREN_NOTU");
					this.OnGONDEREN_NOTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATA_RAPORU", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HATA_RAPORU
		{
			get
			{
				return this._HATA_RAPORU;
			}
			set
			{
				if ((this._HATA_RAPORU != value))
				{
					this.OnHATA_RAPORUChanging(value);
					this.SendPropertyChanging();
					this._HATA_RAPORU = value;
					this.SendPropertyChanged("HATA_RAPORU");
					this.OnHATA_RAPORUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXE_SURUM_ID", DbType="Int")]
		public System.Nullable<int> EXE_SURUM_ID
		{
			get
			{
				return this._EXE_SURUM_ID;
			}
			set
			{
				if ((this._EXE_SURUM_ID != value))
				{
					if (this._TMYS_EXE_SURUM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEXE_SURUM_IDChanging(value);
					this.SendPropertyChanging();
					this._EXE_SURUM_ID = value;
					this.SendPropertyChanged("EXE_SURUM_ID");
					this.OnEXE_SURUM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_SURUM_ID", DbType="Int")]
		public System.Nullable<int> DB_SURUM_ID
		{
			get
			{
				return this._DB_SURUM_ID;
			}
			set
			{
				if ((this._DB_SURUM_ID != value))
				{
					if (this._TMYS_DB_SURUM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDB_SURUM_IDChanging(value);
					this.SendPropertyChanging();
					this._DB_SURUM_ID = value;
					this.SendPropertyChanged("DB_SURUM_ID");
					this.OnDB_SURUM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="TinyInt NOT NULL")]
		public byte DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_DB_SURUM_TMYS_HATA_RAPORU", Storage="_TMYS_DB_SURUM", ThisKey="DB_SURUM_ID", OtherKey="ID", IsForeignKey=true)]
		public TMYS_DB_SURUM TMYS_DB_SURUM
		{
			get
			{
				return this._TMYS_DB_SURUM.Entity;
			}
			set
			{
				TMYS_DB_SURUM previousValue = this._TMYS_DB_SURUM.Entity;
				if (((previousValue != value) 
							|| (this._TMYS_DB_SURUM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMYS_DB_SURUM.Entity = null;
						previousValue.TMYS_HATA_RAPORUs.Remove(this);
					}
					this._TMYS_DB_SURUM.Entity = value;
					if ((value != null))
					{
						value.TMYS_HATA_RAPORUs.Add(this);
						this._DB_SURUM_ID = value.ID;
					}
					else
					{
						this._DB_SURUM_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TMYS_DB_SURUM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_EXE_SURUM_TMYS_HATA_RAPORU", Storage="_TMYS_EXE_SURUM", ThisKey="EXE_SURUM_ID", OtherKey="ID", IsForeignKey=true)]
		public TMYS_EXE_SURUM TMYS_EXE_SURUM
		{
			get
			{
				return this._TMYS_EXE_SURUM.Entity;
			}
			set
			{
				TMYS_EXE_SURUM previousValue = this._TMYS_EXE_SURUM.Entity;
				if (((previousValue != value) 
							|| (this._TMYS_EXE_SURUM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMYS_EXE_SURUM.Entity = null;
						previousValue.TMYS_HATA_RAPORUs.Remove(this);
					}
					this._TMYS_EXE_SURUM.Entity = value;
					if ((value != null))
					{
						value.TMYS_HATA_RAPORUs.Add(this);
						this._EXE_SURUM_ID = value.ID;
					}
					else
					{
						this._EXE_SURUM_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TMYS_EXE_SURUM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
