namespace AvukatProLib.Extras
{
    /// <summary>
    /// TI_KOD_ALACAK_NEDEN
    /// </summary>
    public enum AlacakNeden
    {
        Cek = 1,
        Cek_33 = 33,
        Cek_34 = 34,
        Cek_35 = 35,

        CEK_50 = 129,
        CEK_201 = 130,
        CEK_151 = 131,
        CEK_152 = 132,

        Fatura_37 = 37,

        FATURA_151 = 143,
        FATURA_152 = 144,
        FATURA_153 = 4,
        FATURA_201 = 142,
        FATURA_50 = 141,

        Senet_2 = 2,
        Senet = 11,
        Senet_38 = 38,
        Senet_36 = 36,

        SENET_151 = 139,
        SENET_152 = 140,
        SENET_201 = 138,
        SENET_50 = 137,

        Police = 3,
        Police_40 = 40,
        Police_41 = 41,
        Police_39 = 39,

        POLICE_151 = 135,
        POLICE_152 = 136,
        POLICE_201 = 134,
        POLICE_50 = 133,

        Kira_43 = 43,
        Kira = 44,
        Kira_5 = 5,

        KiraFarkı_45 = 45,
        KiraFarkı_46 = 46,
        KiraFarkı_6 = 6,

        BankaKrediKarti = 49,
        BankaKrediKarti_9 = 9,

        BANKA_KREDI_KARTI_151 = 151,
        BANKA_KREDI_KARTI_152 = 152,
        BANKA_KREDI_KARTI_201 = 150,
        BANKA_KREDI_KARTI_50 = 149,

        BankaKrediAlacagi = 50,
        BankaKrediAlacagi_10 = 10,

        BANKA_KREDI_ALACAGI_151 = 155,
        BANKA_KREDI_ALACAGI_152 = 156,
        BANKA_KREDI_ALACAGI_201 = 154,
        BANKA_KREDI_ALACAGI_50 = 153,

        Tahliye_Taahhudu_12 = 12,

        MenkulRehni_14 = 14,
        MenkulRehni_53 = 53,

        MENKUL_TESLIMI_54 = 30,

        Tahliye_29 = 29,

        Ipotek_32 = 32,
        Ipotek_52 = 52,

        Irtifak_Hakkinin_Kaldirilmasi_60 = 60,

        Sozlesme_7 = 7,
        Sozlesme_47 = 47,

        SOZLESME_151 = 147,
        SOZLESME_152 = 148,
        SOZLESME_201 = 146,
        SOZLESME_50 = 145,

        DigerAlacak_64 = 64,
        DigerAlacak_65 = 65,
        DigerAlacak_66 = 66,
        DigerAlacak_67 = 67,
        DigerAlacak_68 = 68,
        DigerAlacak_69 = 69,
        DigerAlacak_70 = 70,
        DigerAlacak_71 = 71,
        DigerAlacak_72 = 72,
        DigerAlacak_73 = 73,
        DigerAlacak_74 = 74,
        DigerAlacak_75 = 75,

        DIGER_ALACAK_153 = 55,
        DIGER_ALACAK_201 = 76,
        DIGER_ALACAK_49 = 54,
        DIGER_ALACAK_53 = 90,

        DigerDepo_49 = 123, //10042,
        DigerDepo_153 = 124, //10043,
        DigerDepo_50 = 125, //10044,
        DigerDepo_201 = 126, //10045,
        DigerDepo_152 = 127, //10046,
        DigerDepo_151 = 128, //10047,

        BankaKefaleti_49 = 117,//10028,
        BankaKefaleti_153 = 118,//10029,
        BankaKefaleti_50 = 119,//10030,
        BankaKefaleti_201 = 120,//10031,
        BankaKefaleti_151 = 121,//10032,
        BankaKefaleti_152 = 122,//10033,

        CekYapragi_49 = 93,//10004,
        CekYapragi_153 = 94,//10005,
        CekYapragi_50 = 95,//10006,
        CekYapragi_201 = 96,//10007,
        CekYapragi_151 = 97,//10008,
        CekYapragi_152 = 98,//10009,

        TeminatMektubu_49 = 99,//10010,
        TeminatMektubu_153 = 100,//10011,
        TeminatMektubu_50 = 101,//10012,
        TeminatMektubu_201 = 102,//10013,
        TeminatMektubu_151 = 103,//10014,
        TeminatMektubu_152 = 104,//10015,

        VadeliAkreditif_49 = 105,//10016,
        VadeliAkreditif_153 = 106,//10017,
        VadeliAkreditif_50 = 107,//10018,
        VadeliAkreditif_201 = 108,//10019,
        VadeliAkreditif_151 = 109,//10020,
        VadeliAkreditif_152 = 110,//10021,

        Aval_49 = 111,//10022,
        Aval_153 = 112,//10023,
        Aval_50 = 113,//10024,
        Aval_201 = 114,//10025,
        Aval_151 = 115,//10026,
        Aval_152 = 116,//10027,

        //KONUT_KREDISI_50 = 10081,
        //KONUT_KREDISI_201 = 10082,
        //KONUT_KREDISI_151 = 10083,
        //KONUT_KREDISI_152 = 10084,

        KONUT_KREDISI_50 = 157, // 10076 Eski ID
        KONUT_KREDISI_201 = 158, // 10077 Eski ID
        KONUT_KREDISI_151 = 159, // 10078 Eski ID
        KONUT_KREDISI_152 = 160, // 10079 Eski ID

        //ARAC_KREDISI_50 = 10085,
        //ARAC_KREDISI_201 = 10086,
        //ARAC_KREDISI_151 = 10087,
        //ARAC_KREDISI_152 = 10088,

        ARAC_KREDISI_50 = 161, // 10080 Eski ID
        ARAC_KREDISI_201 = 162, // 10081 Eski ID
        ARAC_KREDISI_151 = 163, // 10082 Eski ID
        ARAC_KREDISI_152 = 164, // 10083 Eski ID

        //TUKETICI_KREDISI_50 = 10089,
        //TUKETICI_KREDISI_201 = 10090,
        //TUKETICI_KREDISI_151 = 10091,
        //TUKETICI_KREDISI_152 = 10092,

        TUKETICI_KREDISI_50 = 165, // 10084 Eski ID
        TUKETICI_KREDISI_201 = 166, // 10085 Eski ID
        TUKETICI_KREDISI_151 = 167, // 10086 Eski ID
        TUKETICI_KREDISI_152 = 168, // 10087 Eski ID

        //ROTATIF_KREDI_50 = 10093,
        //ROTATIF_KREDI_201 = 10094,
        //ROTATIF_KREDI_151 = 10095,
        //ROTATIF_KREDI_152 = 10096,

        ROTATIF_KREDI_50 = 169, // 10088 Eski ID
        ROTATIF_KREDI_201 = 170, // 10089 Eski ID
        ROTATIF_KREDI_151 = 171, // 10090 Eski ID
        ROTATIF_KREDI_152 = 172, // 10091 Eski ID

        //KREDILI_TICARI_MEVDUAT_50 = 10097,
        //KREDILI_TICARI_MEVDUAT_201 = 10098,
        //KREDILI_TICARI_MEVDUAT_151 = 10099,
        //KREDILI_TICARI_MEVDUAT_152 = 10100,

        KREDILI_TICARI_MEVDUAT_50 = 173, // 10092 Eski ID
        KREDILI_TICARI_MEVDUAT_201 = 174, // 10093 Eski ID
        KREDILI_TICARI_MEVDUAT_151 = 175, // 10094 Eski ID
        KREDILI_TICARI_MEVDUAT_152 = 176, // 10095 Eski ID

        //DOVIZ_KREDISI_50 = 10101,
        //DOVIZ_KREDISI_201 = 10102,
        //DOVIZ_KREDISI_151 = 10103,
        //DOVIZ_KREDISI_152 = 10104,

        DOVIZ_KREDISI_50 = 177, // 10096 Eski ID
        DOVIZ_KREDISI_201 = 178, // 10097 Eski ID
        DOVIZ_KREDISI_151 = 179, // 10098 Eski ID
        DOVIZ_KREDISI_152 = 180, // 10099 Eski ID

        //IHRACAAT_KREDISI_50 = 10105,
        //IHRACAAT_KREDISI_201 = 10106,
        //IHRACAAT_KREDISI_151 = 10107,
        //IHRACAAT_KREDISI_152 = 10108,

        IHRACAAT_KREDISI_50 = 181, // 10100 Eski ID
        IHRACAAT_KREDISI_201 = 182, // 10101 Eski ID
        IHRACAAT_KREDISI_151 = 183, // 10102 Eski ID
        IHRACAAT_KREDISI_152 = 184, // 10103 Eski ID

        //YATIRIM_KREDISI_50 = 10109,
        //YATIRIM_KREDISI_201 = 10110,
        //YATIRIM_KREDISI_151 = 10111,
        //YATIRIM_KREDISI_152 = 10112,

        YATIRIM_KREDISI_50 = 185, // 10104 Eski ID
        YATIRIM_KREDISI_201 = 186, // 10105 Eski ID
        YATIRIM_KREDISI_151 = 187, // 10106 Eski ID
        YATIRIM_KREDISI_152 = 188, // 10107 Eski ID

        //TAKSITLI_TICARI_KREDI_50 = 10113,
        //TAKSITLI_TICARI_KREDI_201 = 10114,
        //TAKSITLI_TICARI_KREDI_151 = 10115,
        //TAKSITLI_TICARI_KREDI_152 = 10116,

        TAKSITLI_TICARI_KREDI_50 = 189, // 10108 Eski ID
        TAKSITLI_TICARI_KREDI_201 = 190, // 10109 Eski ID
        TAKSITLI_TICARI_KREDI_151 = 191, // 10110 Eski ID
        TAKSITLI_TICARI_KREDI_152 = 192, // 10111 Eski ID

        //FIRMA_TASIT_KREDISI_50 = 10117,
        //FIRMA_TASIT_KREDISI_201 = 10118,
        //FIRMA_TASIT_KREDISI_151 = 10119,
        //FIRMA_TASIT_KREDISI_152 = 10120,

        FIRMA_TASIT_KREDISI_50 = 193, // 10112 Eski ID
        FIRMA_TASIT_KREDISI_201 = 194, // 10113 Eski ID
        FIRMA_TASIT_KREDISI_151 = 195, // 10114 Eski ID
        FIRMA_TASIT_KREDISI_152 = 196, // 10115 Eski ID

        //KONUT_GELISTIRME_KREDISI_50 = 10121,
        //KONUT_GELISTIRME_KREDISI_201 = 10122,
        //KONUT_GELISTIRME_KREDISI_151 = 10123,
        //KONUT_GELISTIRME_KREDISI_152 = 10124,

        KONUT_GELISTIRME_KREDISI_50 = 197, // 10116 Eski ID
        KONUT_GELISTIRME_KREDISI_201 = 198, // 10117 Eski ID
        KONUT_GELISTIRME_KREDISI_151 = 199, // 10118 Eski ID
        KONUT_GELISTIRME_KREDISI_152 = 200, // 10119 Eski ID

        //MORGATE_50 = 10125,
        //MORGATE_201 = 10126,
        //MORGATE_151 = 10127,
        //MORGATE_152 = 10128,

        MORGATE_50 = 201, // 10120 Eski ID
        MORGATE_201 = 202, // 10121 Eski ID
        MORGATE_151 = 203, // 10122 Eski ID
        MORGATE_152 = 204, // 10123 Eski ID

        //IHTIYAC_KREDISI_50 = 10129,
        //IHTIYAC_KREDISI_201 = 10130,
        //IHTIYAC_KREDISI_151 = 10131,
        //IHTIYAC_KREDISI_152 = 10132,

        IHTIYAC_KREDISI_50 = 205, // 10124 Eski ID
        IHTIYAC_KREDISI_201 = 206, // 10125 Eski ID
        IHTIYAC_KREDISI_151 = 207, // 10126 Eski ID
        IHTIYAC_KREDISI_152 = 208, // 10127 Eski ID

        //SIRKET_KREDI_KARTI_50 = 10133,
        //SIRKET_KREDI_KARTI_201 = 10134,
        //SIRKET_KREDI_KARTI_151 = 10135,
        //SIRKET_KREDI_KARTI_152 = 10136,

        SIRKET_KREDI_KARTI_50 = 209, // 10128 Eski ID
        SIRKET_KREDI_KARTI_201 = 210, // 10129 Eski ID
        SIRKET_KREDI_KARTI_151 = 211, // 10130 Eski ID
        SIRKET_KREDI_KARTI_152 = 212, // 10131 Eski ID

        //KREDILI_MEVDUAT_HESABI_50 = 10137,
        //KREDILI_MEVDUAT_HESABI_201 = 10138,
        //KREDILI_MEVDUAT_HESABI_151 = 10139,
        //KREDILI_MEVDUAT_HESABI_152 = 10140,

        KREDILI_MEVDUAT_HESABI_50 = 213, // 10132 Eski ID
        KREDILI_MEVDUAT_HESABI_201 = 214, // 10133 Eski ID
        KREDILI_MEVDUAT_HESABI_151 = 215, // 10134 Eski ID
        KREDILI_MEVDUAT_HESABI_152 = 216, // 10135 Eski ID

        //PERSONEL_KREDISI_50 = 10141,
        //PERSONEL_KREDISI_201 = 10142,
        //PERSONEL_KREDISI_151 = 10143,
        //PERSONEL_KREDISI_152 = 10144,

        PERSONEL_KREDISI_50 = 217, // 10136 Eski ID
        PERSONEL_KREDISI_201 = 218, // 10137 Eski ID
        PERSONEL_KREDISI_151 = 219, // 10138 Eski ID
        PERSONEL_KREDISI_152 = 220, // 10139 Eski ID

        //YETKILI_ODEME_MERKEZI_KREDISI_50 = 10145,
        //YETKILI_ODEME_MERKEZI_KREDISI_201 = 10146,
        //YETKILI_ODEME_MERKEZI_KREDISI_151 = 10147,
        //YETKILI_ODEME_MERKEZI_KREDISI_152 = 10148,

        YETKILI_ODEME_MERKEZI_KREDISI_50 = 221, // 10140 Eski ID
        YETKILI_ODEME_MERKEZI_KREDISI_201 = 222, // 10141 Eski ID
        YETKILI_ODEME_MERKEZI_KREDISI_151 = 223, // 10142 Eski ID
        YETKILI_ODEME_MERKEZI_KREDISI_152 = 224, // 10143 Eski ID

        //KEFALET_KREDISI_50 = 10149,
        //KEFALET_KREDISI_201 = 10150,
        //KEFALET_KREDISI_151 = 10151,
        //KEFALET_KREDISI_152 = 10152,

        KEFALET_KREDISI_50 = 225, // 10144 Eski ID
        KEFALET_KREDISI_201 = 226, // 10145 Eski ID
        KEFALET_KREDISI_151 = 227, // 10146 Eski ID
        KEFALET_KREDISI_152 = 228, // 10147 Eski ID

        //CEK_TAAHHUT_KREDISI_50 = 10153,
        //CEK_TAAHHUT_KREDISI_201 = 10154,
        //CEK_TAAHHUT_KREDISI_151 = 10155,
        //CEK_TAAHHUT_KREDISI_152 = 10156,

        CEK_TAAHHUT_KREDISI_50 = 229, // 10148 Eski ID
        CEK_TAAHHUT_KREDISI_201 = 230, // 10149 Eski ID
        CEK_TAAHHUT_KREDISI_151 = 231, // 10150 Eski ID
        CEK_TAAHHUT_KREDISI_152 = 232, // 10151 Eski ID

        //ISLETME_KREDISI_50 = 10157,
        //ISLETME_KREDISI_201 = 10158,
        //ISLETME_KREDISI_151 = 10159,
        //ISLETME_KREDISI_152 = 10160,

        ISLETME_KREDISI_50 = 233, // 10152 Eski ID
        ISLETME_KREDISI_201 = 234, // 10153 Eski ID
        ISLETME_KREDISI_151 = 235, // 10154 Eski ID
        ISLETME_KREDISI_152 = 236, // 10155 Eski ID

        KIDEM_TAZMINATI_49 = 237, // 10156 Eski ID
        KIDEM_TAZMINATI_153 = 238, // 10157 Eski ID

        IHBAR_TAZMINATI_49 = 239, // 10158 Eski ID
        IHBAR_TAZMINATI_153 = 240, // 10159 Eski ID

        EGITIM_UCRETI_49 = 241, // 10160 Eski ID
        EGITIM_UCRETI_153 = 242, // 10161 Eski ID

        CEZAI_SART_49 = 243, // 10162 Eski ID
        CEZAI_SART_153 = 244, // 10163 Eski ID

        MADDI_TAZMINAT_49 = 245, // 10164 Eski ID
        MADDI_TAZMINAT_153 = 246, // 10165 Eski ID

        MANEVI_TAZMINAT_49 = 247, // 10166 Eski ID
        MANEVI_TAZMINAT_153 = 248, // 10167 Eski ID

        KONUT_KREDISI_49 = 249, // 10168 Eski ID
        KONUT_KREDISI_153 = 250, // 10169 Eski ID

        ARAC_KREDISI_49 = 251, // 10170 Eski ID
        ARAC_KREDISI_153 = 252, // 10171 Eski ID

        TUKETICI_KREDISI_49 = 253, // 10172 Eski ID
        TUKETICI_KREDISI_153 = 254, // 10173 Eski ID

        DOVIZ_KREDISI_49 = 255, // 10174 Eski ID
        DOVIZ_KREDISI_153 = 256, // 10175 Eski ID

        IHRACAAT_KREDISI_49 = 257, // 10176 Eski ID
        IHRACAAT_KREDISI_153 = 258, // 10177 Eski ID

        YATIRIM_KREDISI_49 = 259, // 10178 Eski ID
        YATIRIM_KREDISI_153 = 260, // 10179 Eski ID

        TAKSITLI_TICARI_KREDI_49 = 261, // 10180 Eski ID
        TAKSITLI_TICARI_KREDI_153 = 262, // 10181 Eski ID

        FIRMA_TASIT_KREDISI_49 = 263, // 10182 Eski ID
        FIRMA_TASIT_KREDISI_153 = 264, // 10183 Eski ID

        KONUT_GELISTIRME_KREDISI_49 = 265, // 10184 Eski ID
        KONUT_GELISTIRME_KREDISI_153 = 266, // 10185 Eski ID

        MORGATE_49 = 267, // 10186 Eski ID
        MORGATE_153 = 268, // 10187 Eski ID

        ROTATIF_KREDI = 91,

        IHTIYAC_KREDISI_49 = 269, // 10188 Eski ID
        IHTIYAC_KREDISI_153 = 270, // 10189 Eski ID

        SIRKET_KREDI_KARTI_49 = 271, // 10190 Eski ID
        SIRKET_KREDI_KARTI_153 = 272, // 10191 Eski ID

        KREDILI_MEVDUAT_HESABI_49 = 273, // 10192 Eski ID
        KREDILI_MEVDUAT_HESABI_153 = 274, // 10193 Eski ID

        PERSONEL_KREDISI_49 = 275, // 10194 Eski ID
        PERSONEL_KREDISI_153 = 276, // 10195 Eski ID

        YETKILI_ODEME_MERKEZI_KREDISI_49 = 277, // 10196 Eski ID
        YETKILI_ODEME_MERKEZI_KREDISI_153 = 278, // 10197 Eski ID

        KEFALET_KREDISI_49 = 279, // 10198 Eski ID
        KEFALET_KREDISI_153 = 280, // 10199 Eski ID

        CEK_TAAHHUT_KREDISI_49 = 281, // 10200 Eski ID
        CEK_TAAHHUT_KREDISI_153 = 282, // 10201 Eski ID

        ISLETME_KREDISI_49 = 283, // 10202 Eski ID
        ISLETME_KREDISI_153 = 284, // 10203 Eski ID

        NAFAKA_ISTIRAK_53 = 16,
        ISCI_ALACAGI_KIDEM_TAZMINATI_53 = 25,
        ISIN_YAPILMASI_53 = 19,
        IRTIFAK_HAKKI_TESISI_53 = 21,

        TAZMİN_EDILMIS_TEMINAT_MEKTUBU_151 = 312,
        TAZMİN_EDILMIS_VADELI_AKREDITIF_151 = 318,
        TAZMİN_EDILMIS_AVAL_151 = 324,
        TAZMİN_EDILMIS_BANKA_KEFALETI_151 = 330,
        SPOT_KREDI_151 = 290,
        DOVIZE_ENDEKSLI_SPOT_KREDI_151 = 298,
        TANZIM_EDILMIS_CEK_YAPRAGI_151 = 306,
    }

    public enum AN_URETIP_TIP
    {
        TumBorclularIcin = 0,
        AsilBorclularIcin = 1,
        KefilBorclulariIcin = 2,
        HesapDisi = 3,
        SenetleTakibeKonuldu = 4,
        MunzamSenet = 5
    }

    public enum BaglantiTipi
    {
        VeriTabani = 0,
        WebServices = 1
    }

    public enum BindeYuzde
    {
        Binde = 1,
        Yuzde = 0
    }

    public enum ConnectionTip
    {
        Application_Server = 0,
        Domain_Server = 1,
    }

    /// <summary>
    /// Default 1
    /// </summary>
    public enum DavaDovizIslemTipi
    {
        /// <summary>
        /// Default alan
        /// </summary>
        Olay_Tarihinde_TL = 1,

        Dava_Tarihinde_TL = 2,
        Ödeme_Tarihinde_TL = 3
    }

    public enum DavaFaizIslemTipi
    {
        /// <summary>
        /// Default alan
        /// </summary>
        Değişken = 0,

        Sabit = 1
    }

    public enum DavaGelismeKaynakTip
    {
        Savcılık = 1,
        Taraflar = 2,
        Mahkeme = 3
    }

    /// <summary>
    /// TD_KOD_DAVA_TALEP
    /// </summary>
    public enum DavaTalep
    {
        IHTIYATI_HACIZ = 1,
        IHTIYATI_TEDBIR = 2,
        TESPIT = 3,
        SAVCILIK_TESPIT = 4,
        NOTER_TESPIT = 5,
        TEBLIGATIN_IPTALI = 6,
        MAL_BEYANINDA_BULUNMAMA = 7,
        EMNİYETİ_SUİSTİMAL = 10002,
        İFLASIN_HİLELİ_OLARAK_YAPILMASI = 534,
        TAHLİYESİ_EMROLUNAN_YERİ_KİRALAYANA_ZARAR_VERMEK_MAKSADI_İLE_İŞGAL_ETTİRMEK = 535,
        SENETTE_TAHRİFAT = 531,
        TAAHHUDU_IHLAL = 8,
        SATISIN_IPTAL = 9,
        ITIRAZIN_KALDIRILMASI = 10,
        ITIRAZIN_IPTALI_TALEBI = 11,
        ISTIHKAK = 12,
        TAHLIYE = 13,
        OLUMSUZ_TESPIT = 14,
        BORCTAN_KURTULMA = 15,
        IHTIYATI_HACZE_ITIRAZ = 16,
        IHTIYATI_TEDBIRE_ITIRAZ = 17,
        IFLAS = 18,
        COCUK_TESLIMINDEN_KACINMA = 19,
        ALACAKLIYA_ICRA_DAIRESINDE_TESLIM_EDILEN_TASINMAZ_VEYA_GEMIYE_TEKRAR_GIRMEK = 20,
        NAFAKA = 21,
        KARSILIKSIZ_CEK = 22,
        KARSILIKSIZ_CEK_C = 536,
        TAM_YARGI_DAVASI = 23,
        IPTAL_DAVASI = 24,
        ALACAKLILARI_ZARARA__UGRATAN_BORCLUNUN_CEZALANDILMASI = 43,
        ALTIN_ESYA_IADESI = 44,
        YAGMA = 45,
        EL_ATMANIN_ONLENMESI = 46,
        VERILEN_ARA_KARARINDAN_DONULME_ISTEMI = 47,
        TANIKLARIN_KESIF_MAHALINDE_DINLENMESINI_ISTEME = 48,
        ARAC_SATISININ_IPTALI = 49,
        ARAZI_ZEMININDE_TESPIT_YAPILMASI = 50,
        ARSA_PAYININ_DUZELTILMESI = 51,
        Diger = 52,
        ATAMA_KARARININ_IPTALI = 53,
        AVANS_PAYI_ALACAGI = 54,
        MUVAFAKAT_VERILMESI = 55,
        AVUKATIN_HUKUKI_SORUMLULUGU_CERCEVESINDE_TAZMINAT = 56,
        AYIPLI_MAL_NEDENI_ILE_ODENEN_BEDELIN_IADESI = 57,
        AYIPLI_MAL_AYIPLI_HIZMET = 58,
        AYRI_KONUT_EDINME = 59,
        AYRILIK_KARARI = 60,
        BABALIGIN_TESPITI_VE_TEDBIR_NAFAKASI = 61,
        BASAMAK_YUKSELTME = 62,
        MANEVI_TAZMINAT = 63,
        BEKLEME_SURESININ_UZATILMASI = 64,
        BILIRKISI_RAPORUNA_ITIRAZ = 65,
        BILIRKISI_RAPORUNA_KARSI_ITIRAZLARIMIZIN_SUNULMASI = 66,
        BILIRKISIYE_ITIRAZ = 67,
        BINA_SAHIBININ_HUKUKI_SORUMLULUGUNDAN_DOGAN_TAZMINAT = 68,
        BIRDEN_FAZLA_KISIDEN_HANGISININ_ONCE_OLDUGUNUN_TESPITI_TALEBI = 69,
        BONONUN_IPTALI = 70,
        BORCLU_OLMADIGININ_TESPITI = 71,
        IFLAS_KARARI = 72,
        BORCLUNUN_ODEME_SARTINI_IHLALI = 73,
        BOSANDIGI_KOCASININ_SOYADINI_KULLANMASINA_IZIN_VERILMESI = 74,
        BOSANMA_VELAYET_TAZMINAT_VE_NAFAKA_TALEBI = 75,
        BOSANMA_VE_VELAYETIN_TEVDI = 76,
        BOSANMA_ESYALARIN_IADESI_TAZMINAT_VE_NAFAKA_ISTEMI = 77,
        BOSANMA_NAFAKA_VE_ESYA_DAVASI = 78,
        BOSANMA_NEDENIYLE_VELAYET_TEDBIR_VE_YOKSULLUK_NAFAKASI_TALEBI = 79,
        BOSANMA_ZIYNET_VE_EV_ESYALARININ_IADESI_TAZMINAT_VE_NAFAKA_TALEBI = 80,
        BOZMA_KARARINDAN_OTURU_DURUSMA_GUNU_TAYINI_TALEBI = 81,
        CENIN_SEBEBIYLE_MIRAS_TAKSIMININ_DOGUMA_KADAR_ERTELENMESI_TALEBI = 82,
        CEVABIMIZI_ISLAH = 83,
        CEVAPLARIMIZIN_SUNULMASI_TALEBIDIR = 84,
        CEK_IPTALI = 87,
        COCUGUN_MALLARINI_YONETME = 88,
        COCUKLA_KURULAN_KISISEL_ILISKININ_YENIDEN_DUZENLENMESI = 89,
        DANISMANLIK_EGITIMI_VERILMESI = 90,
        DAVA_DOSYALARININ_BIRLESTIRILMESI = 91,
        DAVADAN_VAZGECME = 92,
        DAVALARIN_AYRILMASI = 93,
        DERNEGIN_FESHI = 94,
        DAVAYA_DAHIL_EDILME = 95,
        DAVAYA_KATILMA_ISTEMI = 96,
        DESTEKTEN_YOKSUN_KALMA_TAZMINATI = 103,
        DIRENME_KARARI_VERILMESI_TALEBI = 104,
        DOGUM_TARIHININ_DUZELTILMESI = 105,
        TAKSIRLE_OLUME_SEBEBIYET_VERMEK = 106,
        EHLIYETIN_GERI_ALINMASI_CEZASININ_IPTALI = 111,
        EK_BILIRKISI_RAPORUNA_KARSI_BEYAN = 112,
        EK_DELIL_DILEKCESININ_SUNULMASI = 113,
        EK_DAVA = 114,
        EK_MADDI_TAZMINAT = 115,
        EK_TEMYIZ_TALEBI = 116,
        EKSIK_VE_AYIPLI_IMALAT_NEDENIYLE_ALACAK = 117,
        EL_KONULAN_ARACIN_TESLIM_ISTEMI = 118,
        MUDAHIL_OLMA_ISTEGI_VE_EL_KONULAN_ARACIN_IADESI = 119,
        EL_KONULAN_PASOPORTLARA_NICIN_EL_KONULDUGUNUN_BILDIRILMESI = 120,
        ELBIRLIGI_MULKIYETIN_PAYLI_MULKIYETE_DONUSTURULMESI = 121,
        EMSAL_SATISLAR = 122,
        ERGIN_KILINMA = 123,
        ESAS_HAKKINDAKI_SAVUNMALARIN_SUNULMASI_ = 124,
        ESKI_HALE_GETIRME_TALEBI = 125,
        ESYA_TESPITI_VE_YEDIEMINLIGIN_TEVDII = 126,
        ESYA_TESPITI_TALEBI = 127,
        HACZE_ITIRAZ = 154,
        MESKENIYET_IDDIASI_DAVASI = 639,
        ICRA_MEMUR_ISLEMINI_SIKAYET = 640,
        YEDDIEMINLI_SUİSTİMAL = 641,
        EVE_VERILEN_ZARARIN_TESPITI = 128,
        EVLAT_EDINME = 129,
        EVLAT_EDINMEDE_RIZANIN_ARANMAMASI = 130,
        EVLATLIK_ILISKISININ_KALDIRILMASI = 131,
        EVLENMENIN_FESHI__MUTLAK_BUTLAN_SEBEBI_ILE_ = 132,
        EVLENMENIN_NISBI_BUTLAN_NEDENI_ILE_FESHI = 133,
        EVLENMEYE_IZIN = 134,
        EVLILIK_BIRLIGININ_TEMELDEN_SARSILMASI_NEDENI_ILE_BOSANMA = 135,
        FAHIS_CEZAI_SARTIN_INDIRILMESI = 136,
        FAIZE_ITIRAZ = 137,
        FSEK_UYARINCA_TECAVUZUN_REFI_MADDI_VE_MANEVI_TAZMINAT_ = 138,
        FUZULI_ISGAL_NEDENI_ILE_TAHLIYE_VE_ECRIMISIL_ISTEMI = 139,
        GEMI_SICILINE_TESCIL_TALEBI = 147,
        GENELGENIN_IPTALI = 148,
        HACZE_KATILMA_SIRA_VE_DERECESINE_ITIRAZ = 155,
        GOREVSIZLIK_KARARI_VERILMESI_TALEBI = 151,
        GOREVSIZLIK_KARARINA_ITIRAZ = 152,
        GREVIN_KANUN_DISI_OLDUGUNUN_TESPITI = 153,
        HACZEDILMEZLIK_SIKAYETI = 156,
        HAKEM_ATANMASI_ISTEMI = 157,
        HAKARET = 541,
        MUESSIR_FIILDE_BULUNMAK = 643,
        MEMURU_DOVMEK_YARALAMAK = 642,
        IPTAL_VE_TAM_YARGI = 167,
        ICRA_VE_IFLAS_GOREVLILERININ_SORUMLULUGUNDAN_DOGAN_TAZMINAT = 189,
        SURE_VE_TALEBI = 190,
        MADDI_TAZMINAT = 191,
        IRTIFAK_HAKKININ_BEDEL_KARSILIGINDA_TERKINI = 220,
        KONKORDATO_ANLASMASININ_ONAYLANMASI_TALEBI = 298,
        MIRASCILIK_BELGESININ_IPTALI_ = 343,
        MIRASCILIKTAN_CIKARMA_KARARININ_IPTALI = 344,
        MIRASIN_REDDI = 345,
        TAKSIMIN_IPTALI_TALEBI = 168,
        HAYATA_KAST_PEK_KOTU_VEYA_ONUR_KIRICI_DAVRANIS_NEDENI_ILE_BOSANMA = 169,
        HAYVAN_TUTANIN_SORUMLULUGUNDAN_DOGAN_TAZMINAT_TALEBI = 170,
        HIZMET_KUSURU_NEDENI_ILE_MADDI_VE_MANEVI_TAZMINAT = 171,
        CINSIYET_DEGISIKLIGI = 85,
        CINSIYET_DEGISIKLIGINE_IZIN = 86,
        DAVAYI_IHBAR = 97,
        DAVAYI_TESMIL = 98,
        DEFTER_TUTULMASINI_ISTEME = 99,
        DELILLERIMIZIN_SUNULMASI = 100,
        DERDESTLIK_ITIRAZI = 101,
        DERNEK_UYELIGINDEN_CIKARMA_KARARININ_IPTALI = 102,
        DOSYAMIN_GOREVLI_MAHKEMEYE_GONDERILMESI_ISTEMI = 107,
        DOSYANIN_GOREVLI_VEYA_YETKILI_MAHKEMEYE_GONDERILMESI = 108,
        DOSYANIN_YETKILI_MAHKEMEYE_GONDERILMESI_ISTEMI = 109,
        MUDAHALENIN_ONLENMESI_ = 110,
        HAKEMIN_REDDI_TALEBI = 160,
        MADDI_VE_MANEVI_TAZMINAT = 161,
        HAKSIZ_FIIL_NEDENI_ILE_TAZMINAT = 162,
        HAKSIZ_IHTIYATI_HACIZDEN_DOGAN_TAZMINAT = 163,
        HAKSIZ_OLARAK_ALINAN_KORUMA_TEDBIRLERI_NEDENI_ILE_TAZMINAT = 164,
        HIZMET_SURESININ_TESPITI = 172,
        HAKSIZ_REKABETIN_TESPITI_VE_MENI_ = 165,
        KIRACININ_ESYALARI_UZERINDE_HAPIS_HAKKI_TANINMASI_TALEBI = 166,
        HIZMET_TESPITI = 173,
        HIZMET_TESPITI_VE_ALACAK = 174,
        HOR_KULLANMA_NEDENIYLE_TAZMINAT = 175,
        IDARI_ISLEMIN_IPTALI_TALEBI = 176,
        HUSUMETE_IZIN_VERILMESI = 177,
        HUKUMLU_LEHINE_YARGILAMANIN_YENILENMESI = 178,
        ICRA_EMRINE_ITIRAZ = 179,
        ADLI_YARDIM_TALEBI = 180,
        ICRA_EMRININ_IPTALI = 181,
        SIKAYET = 182,
        ITIRAZIMIN_SUNULMASI_TALEBI = 183,
        TEMYIZ_TALEBI = 184,
        ICRA_DOSYASINDAKI_ITIRAZIN_KALDIRILMASI = 185,
        ISLEMIN_IPTALI_TALEBI = 186,
        ISIM_TASHIHI = 222,
        ICRA_TAKIBININ_GERI_BIRAKILMASI = 187,
        ICRA_TAKIBININ_IPTALI_TALEBI = 188,
        IDARI_PARA_CEZASININ_IPTALI_TALEBI = 195,
        SOZLESMENIN_GUNUMUZ_SARTLARINA_UYARLANMASI = 196,
        IDDIA_MAKAMININ_MUTALAASINA_KARSI_BEYANLARIMIZIN_SUNULMASI_TALEBI = 197,
        IFLAS_NEDENIYLE_TASINMAZDAN_TAHLIYE_TALEBI = 198,
        IFLASIN_ERTELENMESI = 199,
        IFLASIN_KALDIRILMASI_TALEBI = 200,
        IFLASIN_KAPANMASI_KARARI = 201,
        SIRA_CETVELINE_ITIRAZ = 202,
        IFLASTA_UCUNCU_SAHSIN_ISTIHKAK_IDDIASI = 203,
        IHALENIN_FESHI_TALEBI = 204,
        IHTIYATI_HACIZ_TALEBI = 205,
        IHTIYATI_HACIZ_NEDENIYLE_UGRANILAN_ZARARIN_TAZMINI = 206,
        IHTIYATI_TEDBIR_TALEBI = 207,
        IHTIYATI_TEDBIR_KARARINA_ITIRAZ_TALEBI = 208,
        IHTIYATI_TEDBIR_KARARININ_KALDIRILMASI_TALEBI = 209,
        IKI_HAKLI_IHTAR_ILE_NEDENI_ILE_TAHLIYE = 210,
        KAYITLARDAN_BIRININ_IPTALI = 211,
        ILAVE_DESTEKTEN_YOKSUN_KALMA__MADDI__VE_MANEVI_TAZMINAT_TALEBI = 212,
        IMALATCININ_HUKUKI_SORUMLULUGUNDAN_DOGAN_TAZMINAT = 213,
        IMZAYA_ITIRAZLARIMIN_SUNULMASI_TALEBI = 214,
        INTIFA_HAKKININ_TERKINI = 215,
        IPOTEK_KAYDININ_SILINMESI = 216,
        IPTAL_EDILEN_ATANMA_KARARININ_IPTALINE_KARAR_VERILMESI_TALEBI = 217,
        IRADE_FESADI_NEDENI_ILE_YAPILAN_HUKUKI_ISLEMIN_IPTALI = 218,
        NAFAKA_VE_BOSANMA = 219,
        GABIN_DAVASI = 140,
        GAIPLIK = 141,
        GAIPLIK_NEDENI_ILE_EVLILIGIN_FESHI = 142,
        GECIKMIS_ITIRAZ = 143,
        SIDDETLI_GECIMSIZLIK_NEDENIYLE_BOSANMA = 144,
        GECIT_HAKKI_TESISI = 145,
        GEMI_KURTARMA_MASRAFLARININ_ODENMESI = 146,
        GERCEGE_AYKIRI_MAL_BEYANINDA_BULUNMA = 149,
        GOREV_ITIRAZI = 150,
        HAKEM_UCRETININ_BELIRLENMESI = 158,
        HAKIMIN_REDDI_TALEBI = 159,
        ISTIRDAT = 230,
        ISTISNA_AKDINDEN_DOGAN_ALACAK = 231,
        IS_AKDININ_FESHININ_GECERSIZLIGI_VE_ISE_IADESINE_KARAR_VERILMESI_TALEBI = 232,
        ISLENEN_CURUM_NEDENI_ILE_MADDI_VE_MANEVI_TAZMINAT_TALEBI = 238,
        KAMULASTIRILAN_TASINMAZI_MAL_SAHIBININ_GERI_ALMA_HAKKI = 259,
        KAMULASTIRILAN_TASINMAZIN_BEDEL_TESPITI_VE_TAPUYA_TESCILI = 260,
        KAMULASTIRILAN_TASINMAZIN_TESCILI = 261,
        KAMULASTIRMA_ISLEMININ_IPTALI = 262,
        KAMULASTIRMADAN_ARTA_KALAN_VE_ISE_YA_RAMAYAN_YERIN_KAMULASTIRILMASI = 263,
        KAMULASTIRMASIZ_EL_ATMA = 264,
        KANUNA_AYKIRI_KULLANMA_NEDENI_ILE_TASINMAZIN_DEVRI = 265,
        KAPICI_KONUTUNUN_BOSALTILMASI = 266,
        KAPIDAN_SATIS_SOZLESMESININ_IPTALI_ILE_YAPILAN_ODEMENIN_IADESI = 267,
        KARAR_DUZELTME = 268,
        KARARA_ITIRAZ = 269,
        KAT_MULKIYETI_KANUNUNA_AYKIRI_HAREKET_NEDENIYLE_IHTARAT_YAPILMASI_TALEBI = 276,
        KAT_MULKIYETI_KURULARAK_TAPUYA_TESCILI = 277,
        KAYYIM_ATANMASI_TALEBI = 278,
        KAYYIMLIGIN_KALDIRILMASI_TALEBI = 279,
        ODEME_EMRININ_IPTALI_TALEBi = 280,
        KDV_VE_DAMGA_VERGISININ_IADESI = 281,
        KENDISINE_TESLIM_EDILEN_MALI_ICRA_DAIRESINE_TESLIM_ETMEMEK = 282,
        KIDEM_TAZMINATI_IHBAR_TAZMINATI_FESHIN_GECERSIZLIGI = 283,
        KIDEM_TAZMINATI_IHBAR_TAZMINATI_YILLIK_UCRETI_TAHSILI = 284,
        KIRA_ALACAGININ_TAHSILI_TALEBI = 285,
        TAHLIYE_VE_ALACAK = 286,
        KIRA_BORCUNUN_ODENMEMESI_NEDENI_ILE_TAHLIYE_TALEBI = 287,
        KIRA_SURESI_DOLMADAN_ONCE_CIKMA_VE_HOR_KULLANMA_NEDENI_ILE_TAZMINAT = 288,
        DELIL_TESPITI = 289,
        KIRACININ_OLUMU_NEDENIYLE_TAHLIYE = 290,
        KIRALANANDA_HAYVAN_BESLEME_NEDENI_ILE_TAHLIYE = 291,
        KIRA_BEDELININ_DEGISEN_EKONOMIK_KOSULLAR_ENFLASYONA_GORE_YENIDEN_UYARLANMASI = 292,
        MENFI_TESPIT_VE_ICRA_TAKIBININ_IPTALI = 328,
        MENFI_TESPIT_VE_ISTIRDAT_DAVALARI_ = 329,
        MENFI_TESPIT_ISTIRDAT_VE_SENET_TAKIP_IPTALI = 330,
        CALINAN_MENKUL_MALIN_IADESI = 331,
        MERAYA_EL_ATMANIN_ONLENMESI = 332,
        MERCII_TAYINI_ICIN_YARGITAY_ILGILI_DAIRESINE_GONDERILMESI_TALEBI = 333,
        MESKEN_IHTIYACI_NEDENI_ILE_TAHLIYE = 334,
        MEVCUT_MAL_REJIMININ_DEGISTIRILMESI_TALEBI = 335,
        MIRAS_ORTAKLIGINA_MUMESSIL_TAYINI_TALEBI = 336,
        MIRAS_ORTAKLIGINA_TEMSILCI_ATANMASI_TALEBI = 337,
        MIRAS_ORTAKLIGININ_MUSTEREK_MULKIYETE_DONUSTURULMESI_TALEBI = 338,
        MIRAS_SEBEBI_ILE_ISTIHKAK = 339,
        MIRAS_SOZLESMESININ_IPTALI = 340,
        MIRASCILIK_BELGESI_TALEBI = 341,
        MIRASCILIK_BELGESI = 342,
        ODEME_EMRININ_IPTALI = 192,
        IDARI_PARA_CEZASINA_ITIRAZ = 193,
        IDARI_PARA_CEZASINA_ITIRAZIN_REDDI_KARARINA_ITIRAZ_ = 194,
        IRTIFAK_KAMULASTIRMA_BEDEL_TESPITI_VE_TESCILI = 221,
        ISIM_VE_SOY_ISIM_TASHIHI = 223,
        ISLAH = 224,
        HIRISTIYAN_DININE_MENSUP_OLDUGUM_HALDE_ISLAM_YAZILAN_KAYDIN_KALDIRILMASI = 225,
        ISTIHKAK_IDDIASININ_KABULUNE_KARARVERILMESI_TALEBI = 226,
        ISTIHKAK_IDDIASINA_ITIRAZ = 227,
        ISTIHKAK_IDDIASININ_REDDI_DAVASI = 228,
        ICRA_YOLU_ILE_ODENMEK_ZORUNDA_KALINAN_PARANIN_GERI_ALINMASI = 229,
        ISE_IADE = 233,
        IS_GUCU_KAYBI_NEDENIYLE_MADDI_VE_MANEVI_TAZMINAT_TALEBI = 234,
        TESPIT_TALEBI = 235,
        ISLEMI_SIKAYET_TALEBI = 236,
        ISLEMININ_IPTALI_VE_YURUTMENIN_DURDURULMASI_TALEBI = 237,
        ISLETME_GIDERLERININ_TAHSILI_TALEBI = 239,
        TOPLANTIDA_ITIRAZ_EDILEN_KARARIN_IPTALI = 240,
        ISLETME_TESIS_ALACAGI = 241,
        TARAFLAR_ARASINDAKI_ISTIRAK_HALINDEKI_MULKIYETIN_MUSTEREK_MULKIYETE_CEVRILMESI_TALEBI = 242,
        ISTIRAK_NAFAKASININ_ARTIRILMASI_TALEBI = 243,
        ISYERI_IHTIYACI_NEDENI_ILE_TAHLIYE_TALEBI = 244,
        ITIRAZIN_IPTALI_VE_ICRA_INKAR_TAZMINATINA_KARAR_VERILMESI_TALEBI = 245,
        ITIRAZIN_KALDIRILMASI_VE_ICRA_INKAR_TAZMINATI_TALEBI = 246,
        ITIRAZIN_KALDIRILMASI_VE_IFLAS_TALEBI = 247,
        ITIRAZIN_KALDIRILMASI_VE_TAHLIYE_TALEBI = 248,
        ITIRAZIN_KALDIRILMASI_TAHLIYE_VE_KOTU_NIYET_TAZMINATI_TALEBI = 249,
        ITIRAZIN_KESIN_KALDIRILMASI_TALEBI = 250,
        IVEDI_EL_KOYMA_DURUMUNDA_TASINMAZIN_DURUMUNUN_SAPTANMASI = 251,
        IZALE_I_SUYU__ORTAKLIGIN_GIDERILMESI_ = 252,
        NUFUS_VE_ESYADAN_TAHLIYE = 253,
        KADASTRO_TESPITINE_ITIRAZ = 254,
        KADASTRO_TESPITININ_IPTALI_VE_TESCIL = 255,
        KAMBIYO_SENETLERINDE_IMZAYA_ITIRAZIN_SUNULMASI_TALEBI_ = 256,
        ICRA_TAKIBINE_ITIRAZ = 257,
        DAVANIN_KAMU_GUVENLIGI_NEDENI_ILE_BASKA_BIR_YERE_NAKLI_TALEBI = 258,
        KARARIN_DUZELTILMESI_TALEBI = 270,
        KARSI_DAVA = 271,
        KAT_MALIKININ_HAKSIZ_DAVRANISININ_ONLENMESI_VE_ESKI_HALE_GETIRILMESI = 272,
        KAT_MALIKLERI_KURULU_KARARININ_KALDIRILMASI = 273,
        KAT_MALIKLERININ_HAKLARINA_YAPILAN_TECAVUZUN_ONLENMESI = 274,
        KAT_MULKIYETI_KANUNUNA_AYKIRILIK_NEDENI_ILE_MUDAHALENIN_MENI_VE_KAL = 275,
        KONKORTADO_ISLEMLERININ_BASLATILMASI_TALEBI = 299,
        KONKORTADO_SURESI_VERILMESI_TALEBI = 300,
        KONKORDATO_SURESI_VERILMESI_KARARINA_ITIRAZ = 301,
        KONKORTADO_SURESININ_KALDIRILMASI = 302,
        KONKORDATONUN_FESHI = 303,
        KONKORDATONUN_KALDIRILMASI_TALEBI = 304,
        KONKORDATONUN_ONANMASI_NEDENI_ILE_IFLASIN_KALDIRILMASI = 305,
        KOOPERATIF_GENEL_KURUL_KARARININ_IPTALI = 306,
        KOOPERATIF_UYELIGININ_TESPITI = 307,
        KOOPERATIFTEN_CIKARILMA_KARARINA_ITIRAZ = 308,
        KORUMA_KARARI_VERILMESI_TALEBI = 309,
        KORUMA_KARARININ_KALDIRILMASI_TALEBI = 310,
        VELAYET_ALTINA_ALMA = 293,
        KISILIK_HAKLARINA_YAPILAN_SALDIRININ_ONLENMESI = 294,
        KISISEL_ILISKI_HAKKININ_KALDIRILMASI = 295,
        COCUKLA_SAHSI_ILISKI_KURULMASI = 296,
        KIYMET_TAKDIRINE_ITIRAZ = 297,
        KORUMA_KARARININ_UZATILMASI_TALEBI = 311,
        KUSUR_TESPITI_TALEBI = 312,
        KUSURLU_ESIN_PAYININ_KALDIRILMASI_TALEBI = 313,
        KUCUGUN_GELIRLERININ_KULLANILMASI_NEDENI_ILE_ALACAK = 314,
        MAHKEMECE_VERILEN_KARARDAKI_MADDI_HATANIN_DUZELTILMESI_TALEBI = 315,
        MAL_BEYANINDA_BULUNMAYAN_BORCLUNUN_CEZALANDIRILMASI_TALEBI = 316,
        MAL_BEYANINDA_BULUNUNCAYA_KADAR_HAPSEN_TAZYIK_TALEBI = 317,
        MAL_KACIRMAK_AMACIYLA_YAPILAN_SATISIN_VE_TAPU_KAYDININ_IPTALI_TALEBI = 318,
        MAL_REJIMININ_TASFIYESI = 319,
        HARAP_OLAN_BAGIMSIZ_DAIRENIN_TARAFIMIZA_BEDELI_KARSILIGINDA_DEVRI_TALEBI = 320,
        MASRAFLI_VE_GEREKSIZ_OLAN_ORTAK_YERE_YAPI_YAPMA_KARARININ_KALDIRILMASI_TALEBI = 321,
        MAZERET_KABULU_TALEBI = 322,
        MEN_I_MUDAHALE = 323,
        MENI_MUDAHALE_VE_KAL = 324,
        MENI_MUDAHALE_ECRIMISIL_VE_TASINMAZIN_TESLIMI = 325,
        MENFI_TESPIT = 326,
        MENFI_TESPIT_VE_CEK_IPTALI = 327,
        TASINMAZIN_SATISININ_MURIS_MUVAZAASI_NEDENIYLE_IPTALI = 448,
        TESCIL = 449,
        TAPUDA_YUZOLCUMU_DUZELTILMESI_TALEBI = 450,
        TAVZIH_TALEBI = 451,
        TAYIN_EDILME_ISLEMININ_IPTALI = 452,
        TECAVUZUN_ONLENMESI = 453,
        TEDBIR_NAFAKASI_ARTIRIMI_TALEBI = 454,
        TEDBIR_NAFAKASI = 455,
        ITIRAZI_KALDIRILMASI_VE_TAHLIYE = 456,
        TESPITE_VE_BILIRKISI_RAPORUNA_ITIRAZ = 477,
        KADASTRO_TESPITININ_IPTALI_VE_ADIMIZA_TAPUYA_TESCILIN_SAGLANMASI = 478,
        TEVDI_MAHALLI_TAYINI = 479,
        TEVSII_TAHKIKAT_TALEBI = 480,
        TICARET_SICILINE_TESCIL = 481,
        BROSURLERIN_TOPLATILMASINA_KARAR_VERILMESI_TALEBI = 482,
        TORUNLA_KISISEL_ILISKI_KURULMASI = 483,
        IDARI_PARA_CEZASININ_IPTALINE_KARAR_VERILMESI_TALABI = 484,
        MIRASTA_IADE = 346,
        MUARAZANIN_MENI = 347,
        MUHTESATIN_MULKIYETININ_TESPITI = 348,
        MUNZAM_ZARARIN_TAZMINI = 349,
        MUVAFAKAT_BEYANI_SUNULMASI = 350,
        MUVAZAA_NEDENI_ILE_SATISIN_IPTALI_VE_TESCIL = 351,
        TAPU_IPTALI_VE_TESCIL = 352,
        MUVAZAA_NEDENIYLE_IPTAL_VE_ESIN_KATKI_PA_YININ_TESPITI_ILE_TAZMINI_TALEBI = 353,
        DAVAYA_MUDAHIL_OLMAK_VE_TAZMINAT_TALEBI = 354,
        MUDAHALE_VE_MUARAZANIN_MENI_TALEBI = 355,
        MUDAHALENIN_MENI = 356,
        MUDAHALENIN_MENI_VE_KALI = 357,
        TUTUKLAMA_KARARININ_KALDIRILMASI_TALEBI = 485,
        TUTUKLAMAYA_ITIRAZ = 486,
        KARARIN_KALDIRILMASI_IPTALI_TALEBI = 487,
        USULSUZ_TEBLIG_NEDENI_ILE_ODEME_EMRI_TEBLIG_TARIHININ_DUZELTILMESI_TALEBI = 488,
        TEMYIZ_TALEBINE_KARSI_CEVAPLARIMIZIN_SUNULMASI_ = 511,
        YAS_TASHIHI = 512,
        YAZILI_VAADE_AYKIRI_DAVRANIS_NEDENI_ILE_TAZMINAT = 513,
        YENI_IKTISAP_VE_IHTIYAC_NEDENI_ILE_TAHLIYE = 514,
        YENIDEN_INSA_VE_IMAR_NEDENI_ILE_TAHLIYE = 515,
        YENILEME = 516,
        YER_KULLANMA_BEDELI = 517,
        YETKI_BELGESI_VERILMESI_TALEBI = 518,
        SUC_ISLEME_VE_HAYSIYETSIZ_HAYAT_SURME_NEDENI_ILE_BOSANMA = 415,
        SUYA_EL_ATMANIN_ONLENMESI = 416,
        SURE_BITMESI_NEDENIYLE_TAHLIYE = 417,
        TEMYIZ_VE_SURE_TUTUM_TALEBI = 418,
        KARARIN_TEMYIZ_EDILDIGINE_DAIR_SURE_TUTUM_TALEBININ_SUNULMASI_ = 419,
        SURE_TUTUM_VE_TEMYIZ_TALEBI = 420,
        SARTA_BAGLI_OLARAK_VERILEN_BURSUN_IADESI = 421,
        SIDDETLI_GECIMSIZLIK_NEDENI_ILE_BOSANMA_DAVASI_VE_FERI_SONUCLARI = 422,
        SIKAYETE_KARSI_ITIRAZLARIN_SUNULMASI = 423,
        SIKAYETTEN_VAZGECILMESI_TALEBI = 424,
        SIKAYETTEN_VAZGECME_NEDENI_ILE_MAHKÛMIYET_KARARININ_DUSURULMESI_TALEBI = 425,
        TAAHHUDU_IHLAL_NEDENIYLE_SANIGIN_CEZALANDIRILMASI_TALEBI = 426,
        TAHKIKATIN_GENISLETILMESINE_DAIR_TALEB = 427,
        TAHLIYE_TALEBI = 428,
        TAHLIYE_TAAHHUTNAMESI_NEDENI_ILE_TAHLIYE = 429,
        TAKIBE_KISMI_ITIRAZIN_KALDIRILMASI = 430,
        TAKIBIN_IPTALI_TALEBI = 431,
        TAKIP_TALEBININ_REDDINE_DAIR_KARARIN_IPTALI_TALEBI = 432,
        ATAMA_TALEBININ_ZIMNEN_REDDINE_DAIR_ISLEMIN_IPTALI_ILE_MAHRUM_KALINAN_OZLUK_VE_MADDI_HAKLARIN_IADESI_TALEBI = 433,
        TAPU_KAYDINA_SOYADI_EKLEME_TALEBI = 437,
        ISYERININ_MESKENE_DONUSTURULMESI_TALEBI = 438,
        TAPU_MEMURUNUN_HATALI_ISLEMINDEN_DOLAYI_TAZMINAT_TALEBI_ = 439,
        TAPUDA_ISIM_TASHIHI = 440,
        TAPUDA_MEVCUT_OLAN_KAYDIN_DUZELTILMESI_TALEBI = 441,
        TAPUDA_SOY_ISIM_TASHIHI = 442,
        TASARRUFUN_IPTALI = 443,
        MUARAZANIN_GIDERILMESI = 444,
        TASINMAZ_SATISINA_IZIN_VERILMESI = 445,
        TASINMAZ_ZILYETLIGININ_IADESI = 446,
        TASINMAZIN_IZINSIZ_OLARAK_ALT_KIRACIYA_KIRALANMASI_NEDENI_ILE_TAHLIYE = 447,
        VERASET_BELGESI_TALEBI = 519,
        YETKI_ITIRAZININ_KABULU_TALEBI = 520,
        YETKI_ITIRAZINA_KARSILIK_SAVUNMANIN_SUNULMASI_TALEBI = 521,
        YETKI_ITIRAZININ_SUNULMASI_TALEBI = 522,
        YETKI_ITIRAZINA_CEVAP = 523,
        YOKSULLUK_NAFAKASININ_MIKTARININ_INDIRILMESI = 524,
        YONETIM_KAYYIMI_ATANMASI = 525,
        YONETIM_PLANINDA_DEGISIKLIK_YAPILMASI_TALEBI = 526,
        YURT_DISI_HIZMETLERININ_TESPITI = 527,
        ZAYI_NEDENIYLE_CEK_IPTALI = 528,
        ZINA_NEDENI_ILE_BOSANMA = 529,
        KAPKAC = 530,
        DENEME = 10551,
        MUDAHIL_OLMA_TALEBI = 358,
        TAKASA_ITIRAZ = 359,
        MUFLISE_AIT_MALLARI_VERMEMEK = 360,
        MULKIYETIN_TESPITI = 361,
        MUDAHILLIK_TALEBININ_KABULU_ILE_ARACIN_IADESI_TALEBI_ = 362,
        MUSTEREK_HAYAT_YENIDEN_KURULAMADIGI_ICIN_BOSANMA = 363,
        NAFAKA_BORCU_ICIN_TEMINAT_VERILMESI_TALEBI = 364,
        NAFAKA_BORCUNU_ODEMEYEN_BORCLUNUN_CEZALANDIRILMASI_TALEBI = 365,
        NAFAKANIN_KALDIRILMASI = 366,
        NISANIN_BOZULMASI_NEDENI_ILE_HEDIYELERIN_IADESI = 367,
        NISANIN_BOZULMASI_NEDENI_ILE_MANEVI_TAZMINAT = 368,
        NUFUS_KAYDININ_DUZELTILMESI = 369,
        MUKERRER_KAYDIN_IPTALI = 370,
        NUFUSA_TESCIL_TALEBI = 371,
        NUFUSTA_CINSIYET_KAYDININ_DUZELTILMESI = 372,
        NUFUSTAKI_OLUM_KAYDININ_DUZELTILMESI = 373,
        OLAGANUSTU_ZAMANASIMI_NEDENI_ILE_TASINMAZIN_MULKIYET_HAKKININ_TAPU_KUTUGUNE_TESCILI = 374,
        OLUMSUZ_SICIL_RAPORUNUN_IPTALI_VE_BIR_KA_DEME_ILERLEMENIN_VERILMESI_TALEBI = 375,
        ONARIM_GIDERININ_TAHSILI_TALEBI = 376,
        ORTAK_KONUTUN_TESPITI = 377,
        ORTAK_YERLERE_EL_ATMANIN_ONLENMESI = 378,
        AILE_KONUTU_OLARAK_TAHSIS_TALEBI = 379,
        ODEME_EMRININ_IPTALI_VE_DAVA_SONUCLANINCAYA_KADAR_YURUTMENIN_DURDURULMASI_TALEBI = 380,
        ITIRAZIN_GECICI_OLARAK_KALDIRILMASI_TALEBI = 381,
        ITIRAZIN_KESIN_OLARAK_KALDIRILMASI_TALEBI = 382,
        ODEME_EMRININ_VE_MAAS_HACIZ_ISLEMININ_IPTALI_TALEBI = 383,
        ODEME_NEDENIYLE_DAVANIN_DUSURULMESI_TALEBI = 384,
        ODEME_NEDENI_ILE_ICRA_TAKIBININ_GERI_BIRAKILMASI_TALEBI = 385,
        ODEME_NEDENIYLE_TAKIBIN_DURDURULMASI_TALEBI = 386,
        ODENEN_PARANIN_GERI_VERILMESI_TALEBI = 387,
        ODENMEYEN_ILAC_BEDELININ_ODENMESI_TALEBI = 388,
        MUVEKKILIN_MURISININ_OLUMUNUN_TESPITINE_KARAR_VERILMESI_TALEBI = 389,
        ON_ALIM = 390,
        OZ_SERMAYE_TESPITI = 391,
        OZEL_USULSUZLUK_CEZASININ_IPTALI = 392,
        PARA_CEZASI_ISLEMININ_IPTALI = 393,
        PRIM_BORCUNUN_IPTALI = 394,
        PRIM_BORCUNUN_VE_ODEME_EMIRLERININ_IPTALI = 395,
        SATIS_BEDELININ_IADESI = 396,
        SATIS_TALEBI = 397,
        SATIS_SURETI_ILE_IZALE_I_SUYU = 398,
        SATIS_VAADI_SOZLESMESINE_DAYILI_TAPU_IPTALI_VE_TESCIL = 399,
        SATIS_YERININ_DEGISTIRILMESI_TALEBI = 400,
        SATISA_IZIN_VERILMESI = 401,
        SAVUNMA_BEYANI = 402,
        SEBEPSIZ_ZENGINLESME_NEDENI_ILE_ALACAK = 403,
        SEBEPSIZ_ZENGINLESME_ = 404,
        SECIMLIK_MAL_TESLIMI_ = 405,
        SENET_IPTALI = 406,
        ZORUNLU_BAG_KUR_SIGORTALILIGININ_TESPITI = 407,
        SOYADI_DEGISTIRME = 408,
        SOYBAGININ_KURULMASI = 409,
        SOYBAGININ_REDDI = 410,
        SOZLESMENIN_FESHI_VE_CEKLERIN_IADESI = 411,
        SU_BASKINI_SEBEBIYLE_ISYERINDE_MEYDANA_GELEN_HASARIN_TESPITI_TALEBI = 412,
        SU_BORCU_ASLINA_VE_FAIZINE_ILISKIN_BORCUN_OLMADIGININ_TESPITI = 413,
        SU_BORCUNUN_OLMADIGININ_TESPITI = 414,
        ISLAH_TALEBI = 434,
        TEKZIP = 457,
        TEKZIBIN_YAYINLAMASINA_KARAR_VERILMESI_TALEBI = 458,
        CEVAP_VE_DUZELTME_TALEBI = 459,
        ZARAR_TAZMINI = 460,
        TEMSIL_YETKISININ_GERI_VERILMESI = 461,
        KISMI_TEMYIZ_TALEBI = 462,
        TEMYIZ_DILEKCESINE_CEVAP_ = 463,
        TEMYIZE_CEVAP_ = 464,
        KARSI_TEMYIZ_EDEN_VE_TEMYIZE_CEVAP = 465,
        YABANCI_ULKEDE_VERILEN_KARARIN_TENFIZI__TALEBI = 466,
        TENKIS = 467,
        TEREKENIN_TESPITI_TALEBI = 468,
        TEREKEYE_TEMSILCI_TAYINI = 469,
        TERK_NEDENI_ILE_BOSANMALARINA_KARAR_VERILMESI_TALEBI = 470,
        TERK_NEDENIYLE_BOSANMA = 471,
        TERK_NEDENI_ILE_IHTAR_KARARI_VERILMESI_TALEBI = 472,
        TESCILE_ITIRAZ = 473,
        UYELIK_VE_BORCU_BULUNUP_BULUNMADIGININ_TESPITI = 474,
        TESPIT_KARARINA_ITIRAZ_ = 475,
        TESPITE_ITIRAZ = 476,
        UST_HAKKI_TESISI = 489,
        VAKIF_RESMI_SENEDININ_SICILE_TESCILI = 490,
        VASI_ATANMASI = 491,
        VASININ_AZLI_TALEBI = 492,
        VASIYETNAMEDEN_RUCU_ISLEMININ_IPTALI = 493,
        VASIYETNAMENIN_ACILMASI_OKUNMA_VE_YERINE_GETIRILMESI = 494,
        VASIYETNAMENIN_IPTALI = 495,
        VASIYETNAMENIN_YERINE_GETIRILMESI_DAVASI = 496,
        VEKALETSIZ_IS_GORME_NEDENIYLE_TAZMINAT = 497,
        VELAYETIN_DEGISTIRILMESI = 498,
        VELAYETIN_NEZI_VE_COCUGUN_VELAYETININ_BABAYA_TEVDII = 499,
        VELAYETIN_TEDBIR_MAHIYETINDE_TEVDII = 500,
        KARARIN_BOZULMASI_TALEBI = 501,
        YABANCI_MAHKEME_KARARININ_TANINMASI = 502,
        YABANCI_MAHKEME_KARARININ_TANINMASI_VE_TENFIZI = 503,
        YAKALAMA_KARARINA_ITIRAZ = 504,
        HUKUKA_AYKIRI_VE_HAKSIZ_YAKALAMAYA_ITIRAZ = 505,
        YARDIM_NAFAKASI_ARTIRIMI = 506,
        YARDIM_NAFAKASI = 507,
        YARDIMCI_SAHSIN_FIILINDEN_DOGAN_SORUMLULUK = 508,
        YARGILAMANIN_YENILENMESI_TALEBI = 509,
        TAZMINAT = 25,
        TEDBIRSIZLIK_VE_DIKKATSIZLIKLE_ADAM_OLDURME = 26,
        ZORUNLU_MALI_SORUMLULUK__TAZMINAT_ = 27,
        RUCUEN_TAZMINAT = 28,
        BELEDIYEYE_KARSI = 29,
        KIRA_BEDEL_TESPITI = 30,
        ADAM_OLDURMEK = 31,
        ECRIMISIL = 32,
        BOSANMA = 33,
        IPTAL = 34,
        ACIZ_SEBEBIYLE_DOGRUDAN_DOGRUYA_IFLAS = 35,
        ACZINE_KENDI_FIILI_ILE_SEBEBIYET_VERME = 36,
        AD_VE_SOYADIN_DEGISTIRILMESI = 37,
        IHTIYATI_HACIZ_KARARININ_IPTALI = 38,
        ADLI_TIP_KURUMU_RAPORUNA_ITIRAZ_DILEKCESI = 39,
        TUTUKLAMA_KARARINA_KARSI_ITIRAZ = 40,
        AILE_KONUTU_OLARAK_TAHSIS_VE_TAPUYA_SERH_VERILMESI = 41,
        ALACAK = 42,
        TANIKLARA_SORU_SORULMASI_TALEBI = 435,
        TANIMAYA_ITIRAZ = 436,
        KARAR_DUZELTME_TALEBINE_KARSI_CEVAP = 510,
    }

    public enum DavaTazminatHesapTipi
    {
        /// <summary>
        /// Default değer
        /// </summary>
        Nispi = 1,

        Maktu = 0
    }

    public enum FaturaHedefTip
    {
        Dosyaya_Bağlı_Değil = 0,
        Icra_Dosyası = 1,
        Soruşturma_Dosyası = 4,
        Dava_Dosyası = 3
    }

    public enum FaturaKapsamTip
    {
        Dosya_Geneline_İlişkin = 0,
        Nedene_İlişkin = 1
    }

    public enum FormKonusu
    {
        Form49_ADI_ALACAK = 1,
        Form153_ADI_ALACAK = 15,
        Form56_YAZILI_SOZLESMEYLE_TAHLIYE = 12,
        Form50_MENKUL_REHN_ = 2,
        Form53_NAFAKA = 5,
        Form53_ISIN_YAPILMASI = 7,
        Form53_IRTIFAK_HAKKI = 8,
        Form53_ISCI_ALACAGI = 6,
        Form54_GAYRIMENKUL_TAHLIYE_TESLIMI = 10,
        Form54_MENKUL_TESLIMI = 9,
        Form55_COCUK_TESLIMI = 11,
        Form151_IPOTEGIN_PARAYA_CEVRILMESI = 13,
        Form52_KAMBIYO_ALACAGI = 4,
        Form163_KAMBİYO_ALACAGI = 16,
        Form51_KIRA = 3,
        Form152_IPOTEGIN_PARAYA_CEVRILMESI = 14,
        Form201_MENKUL_REHNI = 17,
        Form53_ILAMLI_ALACAK = 18,
    }

    public enum FormTipi
    {
        NULL = 0,
        KambiyoSenetleri_163 = 163,
        KambiyoSenetleri_52 = 52,

        IlamsizOdemeEmri_49 = 49,
        IlamsizOdemeEmri_153 = 153,

        MenkulRehninParayaCevrilmesi_50 = 50,
        MenukulRehninParayaCevrilmesi_201 = 201,

        ParaTeminatIcraEmri_53 = 53,
        CocukTeslimi_55 = 55,

        MenukulTeslimiveyaGayrimenkul_51 = 51,
        MenkulTeslimiveyaGayrimenkul_54 = 54,
        MenkulTeslimiveyaGayrimenkul_56 = 56,

        IpoteginParayaCevrilmesi_151 = 151,
        IpoteginParayaCevrilmesi_152 = 152,
    }

    public enum FormTipleri
    {
        Form49 = 1,
        Form153 = 12,
        Form56 = 9,
        Form50 = 2,
        Form53 = 4,
        Form54 = 6,
        Form55 = 5,
        Form151 = 7,
        Form52 = 11,
        Form163 = 3,
        Form51 = 10,
        Form152 = 8,
        Form201 = 13,
    }

    public enum GorusmeYonu
    {
        İçeri = 0,
        Dışarı = 1
    }

    public enum HacizKaynak
    {
        İhtiyati_Haciz = 2,
        İhtiyati_Tedbir = 3,
        Normal_Haciz = 1
    }

    /// <summary>
    /// Default 1
    /// </summary>
    public enum IcraDovizIslemTipi
    {
        /// <summary>
        /// Default alan
        /// </summary>
        Vade_Tarihinde_TL = 1,

        Takip_Tarihinde_TL = 2,
        Fiili_Ödeme_Tarihinde_TL = 3
    }

    public enum IcraGelismeKaynakTip
    {
        Taraflar = 1,
        İcra_Müdürlüğü = 2,
        Mahkeme = 3,
        Savcılık = 4
    }

    public enum ItirazBeyanSekli
    {
        Yazılı = 0,
        Sözlü = 1
    }

    public enum ItirazSonucu
    {
        NULL = 0,
        KABUL_EDILDI = 1,
        REDDEDILDI = 3,
        INCELENIYOR = 4,
    }

    public enum KEvrakAhzolunmaSekli
    {
        Malen = 0,
        Nakten = 1
    }

    public enum KEvrakSonucu
    {
        Karşılığı_Yok,
        Kısmen_Karşılığı_var,
        Karşılığı_var,
        Beklemede,
        Ödemeden_Men_Talimatı
    }

    public enum KEvrapTipi
    {
        Çek = 1,
        Bono = 2,
        Poliçe = 3
    }

    /// <summary>
    /// TDI_KOD_KIYMETLI_EVRAK_TARAF_TIP
    /// </summary>
    public enum KiymetliEvrakTarafTip
    {
        Alacakli = 1,
        Kesideci_Borclu = 2,
        Ciranta_Borclu = 3,
        Avalist = 4,
        Lehtar = 5,
        Muhatap = 6, //10001,
        Borclu = 7, //10002,
        Hamil = 8  //10003
    }

    public enum MasrafAvansHedefTip
    {
        İcra_Dosyası = 1,
        Dava_Dosyası = 2,
        Hazırlık_Dosyası = 3,
        Rücu_Dosyası = 4
    }

    public enum MasrafAvansTip
    {
        Masraf = 1,
        Avans = 2
    }

    public enum OturumAcmaModu
    {
        User_Specified = 0,
        Windows_LDAP = 1
    }

    /// <summary>
    /// TDIE_KOD_SABLON_ALT_KATEGORI tablosundan oluşturulmuştur.
    /// </summary>
    public enum SablonAltKategori
    {
        Ihtarname = 24,
        Rapor_Ornekleri = 25,
        Dava_Muzekkereleri = 26,
        Karar_Sablonlari = 27,
        Ibranameler = 28,
        Sozlesmeler = 29,
        Icra_Yazismalari = 30,
        Sorusturma_Yazismalari = 23,
        Is_Mevzuati = 11,
        Kira = 12,
        Dava_Yazismalari = 14,
        Icra_Formlari = 15,
        Muzekkereler = 16,
        Muvekkil_Mektuplari = 19,
        Karsi_Taraf_Mektuplari = 20,
        Diger = 21,
        Tumu = 22
    }

    public enum SatisIlanSekli
    {
        İlan_Panosu = 0,
        Gazete_İlanı = 1
    }

    //public enum HangiTaraf
    //{
    //    TAKİP_EDEN = 1,
    //    TAKİP_EDİLEN = 2
    //}
    public enum SorumluTip
    {
        Sorumlu = 0,
        Avukat = 1
    }

    /// <summary>
    /// TDI_KOD_SOZLESME_ALT_TIP
    /// </summary>
    public enum SozlesmeAltTip
    {
        Menkul_Kira_Sozlesmesi = 1,
        Gayrimenkul_Kira_Sozlesmesi = 2,
        Hasilat_Kira_Sozlesmesi = 3,
        Kredi_Karti_Sozlesmesi = 4,
        Gayrimenkul_Ipotegi = 5,
        Gemi_Ipotegi = 6,
        Hava_Araci_Ipotegi = 7,
        Arac_Rehni = 8,
        Ticari_Isletme_Rehni = 9,
        Menkul_Mal_Rehni = 10,
        Menkul_Kiymet_Rehni = 11,
        Mevduat_Rehni = 12,
        Ticari_Senet_Rehni = 13,
        Genel_Kredi_Sozlesmesi = 14,
        Esas_Sozlesmesi__Komandit_Sirket_ = 65,
        Esas_Sozlesmesi__Limited_Sirket_ = 66,
        Eserin_Yayin_Hakkinin_Devri_Sozlesmesi = 67,
        Evlat_Edinme_Senedi_Sozlesmesi = 68,
        Faktoring_Hizmetleri_Sozlesmesi = 69,
        Finansal_Kiralama_Sozlesmesi = 70,
        Finansman_Sozlesmesi = 71,
        FOB_Satis_Sozlesmesi = 72,
        Franchise_Sozlesmesi = 73,
        Garanti_Sozlesmesi = 74,
        Gayrimenkul_Satis_Vaadi_Sozlesmesi = 75,
        Gelir_Paylasim_Sozlesmesi = 76,
        Genel_Cerrahi_Sozlesmesi = 77,
        Gizlilik_Sozlesmesi = 78,
        Gorsel_Urun_Kullanim_Sozlesmesi = 79,
        Gozetim_ve_Danismanlik_Hizmetleri_Sozlesmesi = 80,
        Grup_Hayat_Sigorta_Sozlesmesi = 81,
        Guvenlik_Hizmetleri_Sozlesmesi = 82,
        Hesap_Rehin_Sozlesmesi = 83,
        Hisse_Devir_Sozlesmesi = 84,
        Hisse_Opsiyon_Sozlesmesi = 85,
        Hisse_Rehni_Sozlesmesi = 86,
        Hisse_Satis_ve_Devir_Sozlesmesi = 87,
        Holding_Ana_Sozlesmesi = 88,
        Hukuki_Danismanlik_Sozlesmesi = 89,
        ISO_Danismanlik_Sozlesmesi = 90,
        Ibra_Sozlesmesi = 91,
        Icraci_Oyuncu_Sozlesmesi = 92,
        Icerik_Lisans_Sozlesmesi = 93,
        Ihracatlarda_Aracilik_Yapilmasina_Dair_Sozlesme = 94,
        Imalatci_Kodlandirma_Sozlesmesi = 95,
        Imtiyaz_Sozlesmesi = 96,
        Inhisari_Lisans_Sozlesmesi = 97,
        Internet_Abonman_Sozlesmesi = 98,
        Internet_Alisveris_Sitesi_Uye_Isyeri_Sozlesmesi = 99,
        Internet_Erisim_ve_Hizmet_Sozlesmesi = 100,
        Intifa_Hakki_Tesis_ve_Temlik_Sozlesmesi = 101,
        Irtifak_Hakki_Sozlesmesi = 102,
        Istisna__Yapim__Sozlesmesi = 103,
        Isbirligi_Sozlesmesi = 104,
        Istira_Sozlesmesi = 105,
        Isyeri_Hekimligi_Sozlesmesi = 106,
        Joint_Venture_Sozlesmesi = 107,
        Kaydi_Hayatla_Irat_Sozlesmesi = 108,
        Kayit_Mekanik_Lisans_Sozlesmesi = 109,
        Konsinye_Satis_Sozlesmesi = 110,
        Konsorsiyum_Sozlesmesi = 111,
        Konut_Tahsis_Sozlesmesi = 112,
        Kooperatif_Ana_Sozlesmesi = 113,
        Kosgeb_Destekleri_Protokolu = 114,
        Kredi_Karti_Uye_Isyeri_Programi_Sozlesmesi = 115,
        Kredi_Karti_Uyelik_Sozlesmesi = 116,
        Kredili_Menkul_Kiymet_Sozlesmesi = 117,
        Kullandirma_Sozlesmesi = 118,
        Kurumsal_Itibar_Arastirmasi_Sozlesmesi = 119,
        Link_Ekle_Kazan_Sozlesmesi = 120,
        Lisans_Sozlesmesi = 121,
        Mail_Order_Sozlesmesi = 122,
        Mal_Ayriligi_Sozlesmesi = 123,
        Mal_Ortakligi_Sozlesmesi = 124,
        Mal_Rejimi__Edinilmis_Mallara_Katilma__Sozlesmesi = 125,
        Mali_Haklarin_Devri_Sozlesmesi = 126,
        Malzeme_Devir_Sozlesmesi = 127,
        Marka_Devir_Sozlesmesi = 128,
        Marka_Lisans_Sozlesmesi = 129,
        Menajerlik_Sozlesmesi = 130,
        Mimarlik_Hizmetleri_Sozlesmesi = 131,
        Miras_Mukavelesi = 132,
        Miras_Payinin_Devri_Sozlesmesi = 133,
        Miras_Paylastirmasi_Sozlesmesi = 134,
        Mirastan_Feragat_Sozlesmesi = 135,
        Muhasebe_Hizmetleri_Sozlesmesi = 136,
        Mulkiyeti_Muhafaza_Kaydi_ile_Satis_Sozlesmesi = 137,
        Munhasir_Yetkili_Satici_Sozlesmesi = 138,
        Musterek_Hesap_Sozlesmesi = 139,
        Opsiyonlu_Satis_Sozlesmesi = 140,
        Ortak_Girisim_Beyannamesi = 141,
        Ortak_Yaratim_Lisans_Sozlesmesi = 142,
        Otomobil_Kiralama_Sozlesmesi = 143,
        Otoproduktor_Sozlesmesi = 144,
        Patent_Devir_Sozlesmesi = 145,
        Patent_Lisans_Sozlesmesi = 146,
        Produksiyon_Sozlesmesi = 147,
        Promosyonel_Isbirligi_Sozlesmesi = 148,
        Rekabet_Etmeme_Sozlesmesi = 149,
        Sanati_Icra_Sozlesmesi = 150,
        Satis_Sozlesmesi = 151,
        Sureli_Hizmet_Sozlesmesi = 152,
        Suresiz_Hizmet_Sozlesmesi = 153,
        Tanitim_Sozlesmesi = 154,
        Tasarim_Yatirim_ve_Insa_Sozlesmesi = 155,
        Tasima_Hizmetleri_Sozlesmesi = 156,
        Teknik_Servis_Hizmet_Sozlesmesi = 157,
        Telif_Ucreti_Sozlesmesi = 158,
        Test_Sozlesmesi = 159,
        Tibbi_Tetkik_ve_Tedavi_Sozlesmesi = 160,
        Transfer_Sozlesmesi = 161,
        Uzlasma_Sozlesmesi = 162,
        Urun_Satin_Alim_Sozlesmesi = 163,
        Vekalet_Ucret_Sozlesmesi = 164,
        Yapit_Yayim_Sozlesmesi = 165,
        Yonetmen_Sozlesmesi = 166,
        Abonelik_Sozlesmesi = 15,
        Abonman_Sozlesmesi = 16,
        Acentelik_Sozlesmesi = 17,
        Akreditif_Sozlesmesi = 18,
        Alan_Adi_Kullanici_Sozlesmesi = 19,
        Alim_Satim_Aracilik_Sozlesmesi = 20,
        Alt_Kiralama_Sozlesmesi = 21,
        Alt_Muteahhitlik_Sozlesmesi = 22,
        Alt_Tasima_Sozlesmesi = 23,
        Alt_Yayimcilik_Sozlesmesi = 24,
        Arac_Satis_Sozlesmesi = 25,
        Arastirma_Sozlesmesi = 26,
        Ardiye_Sozlesmesi = 27,
        Ariyet_Sozlesmesi = 28,
        Kat_Karsiligi_Insaat_Sozlesmesi = 29,
        Arsa_Tahsis_Sozlesmesi = 30,
        Av_Ort_Ana_Sozlesmesi = 31,
        Avukatlik_Sozlesmesi = 32,
        Bagimsiz_Ozel_Denetim_Sozlesmesi = 33,
        Bagislama_Sozlesmesi = 34,
        Banka_Teminat_Mektubu = 35,
        Bankacilik_Islemleri_Sozlesmesi = 36,
        Barkod_Hizmet_Sozlesmesi = 37,
        Barter__Takas__Sozlesmesi = 38,
        Basin_Danismanligi_ve_Menajerlik_Sozlesmesi = 39,
        Bayilik_Sozlesmesi = 40,
        Belirli_Sureli_Is_Sozlesmesi = 41,
        Bilet_Satis_Sozlesmesi = 42,
        Birlesme_Sozlesmesi = 43,
        Birlik_Kurma_Sozlesmesi = 44,
        Borcu_Ustlenme_Sozlesmesi = 45,
        Borc_Yapilandirma_Sozlesmesi = 46,
        Bolunme_Sozlesmesi = 47,
        Buluslar_ve_Patentler_Hakkinda_Is_Sozlesmesi = 48,
        Cari_Hesap_Sozlesmesi = 49,
        CFR_Satis_Sozlesmesi = 50,
        Ceviri_Yapit_Sozlesmesi = 51,
        Ciraklik_Sozlesmesi = 52,
        Dagitici_Sozlesmesi = 53,
        Danismanlik_Sozlesmesi = 54,
        Delil_Sozlesmesi = 55,
        Depolama_ve_Sevkiyat_Sozlesmesi = 56,
        Destek_Hizmetleri_Sozlesmesi = 57,
        Devir_ve_Satis_Sozlesmesi = 58,
        Devre_Mulk___Tatil_Sozlesmesi = 59,
        Distributorluk_Sozlesmesi = 60,
        Dizi_Sozlesmesi = 61,
        Doviz_Alim_Satim_Sozlesmesi = 62,
        Esas_Sozlesmesi__Anonim_Sirket_ = 63,
        Esas_Sozlesmesi__Kollektif_Sirket_ = 64,
        Noterden_Borc_Ikrari = 177,
        Resen_Duzenlenmis_Noter_Senedi = 178,
        Hat_Rehni = 172,
        Marka_Rehni = 173,
        Ticari_Plaka_Rehni = 174,
    }

    /// <summary>
    /// TDI_KOD_SOZLESME_TIP
    /// </summary>
    public enum SozlesmeAnaTip
    {
        //TebligatSozlesmesi,
        //KiraSozlesmesi,
        //KrediSozlesmesi,
        //TeminatSozlesmesi

        Kira_Sozlemesi = 1,
        Kredi_Sozlemesi = 2,
        Resmi_Senet = 3,
        Genel_Sozleme = 4,
        Hakem_Sozlemesi = 5, //10007,
        Marka_Patent_Sozlemesi = 6, //10008
    }

    /// <summary>
    /// TDI_KOD_SOZLESME_DURUM
    /// </summary>
    public enum SozlesmeDurum
    {
        Faal = 1,
        Arsiv = 2,
        Taslak = 3,
        Imzada = 4,
        Incelemede = 5,
        Tadil = 6,
        Ihtilaf = 7,
        Iptal = 8,
        Adli_Yargi_Surecinde = 9,
        Yenileme = 10,
        Tahkim_Surecinde_ = 11,
    }

    #region <CC-20090612>

    //Faiz detayları önce sonramısı için eklendi

    public enum FaizTakipdenOnce
    {
        Faiz_Takipden_Önce = 1,
        Faiz_Takipden_Sonra = 0
    }

    #endregion <CC-20090612>

    #region <CC-20090613>

    //MASRAF BİLGİLERİ ONAY DURUMU IÇIN  ONAY DURUM EKLENDİ eklendi

    public enum MasrafOnay
    {
        Değerlendirilmedi = 0,
        bOnay = 1,
        iOnay = 2,
        uOnay = 3,
        Reddedildi = 4
    }

    #endregion <CC-20090613>

    /// <summary>
    /// TDI_KOD_SOZLESME_TARAF_SIFAT
    /// </summary>
    public enum SozlesmeTarafTip
    {
        Muhatap = 24,//10024
        SozlesmeYapan = 29,//10029,
        RehinAlan = 32,//10032,
        Kiracı = 46,//10046,
        Kiralayan = 47,//10047,
        RehinVeren = 50,//10051,
        KrediVeren = 51,//10052,
        KrediAlan = 52,//10053,

        IHTAR_EDEN = 1,
        FESIH_EDEN = 2,
        ITIRAZ_EDEN = 3,
        AZIL_EDEN = 4,
        ISTIFA_EDEN = 5,
        SOZLESME_TARAFI = 6,
        KEFIL_OLAN = 7,
        TANIK = 8,
        TESPIT_ISTEYEN = 9,
        REHIN_EDEN = 10,
        HIBE_EDEN = 11,
        TEMLIK_EDEN = 12,
        ALACAKLI = 13,
        PROTESTO_EDEN = 14,
        VASIYET_EDEN = 15,
        FERAGAT_EDEN = 16,
        EVLATLIK_VEREN = 17,
        EMANET_EDEN = 18,
        IBRA_EDEN = 19,
        TAAHHUT_EDEN = 20,
        VEKIL_EDEN = 21,
        SULH_OLAN = 22,
        MUVAFAKAT_EDEN = 23,

        //MUHATAP = 24,
        IHTAR_EDILEN = 25,

        FESIH_EDILEN = 26,
        ITIRAZ_EDILEN = 27,
        AZIL_EDILEN = 28,

        //SOZLESME_YAPAN = 29,
        KEFALET_ALAN = 30,

        TESPIT_ISTENEN = 31,

        //REHIN_ALAN = 32,
        HIBE_ALAN = 33,

        TEMELLUK_EDEN = 34,
        BORCLU = 35,
        PROTESTO_OLUNAN = 36,
        VASIYET_OLUNAN = 37,
        EVLATLIK_ALAN = 38,
        EVLATLIK_OLAN = 39,
        EMANET_ALAN = 40,
        IBRA_OLUNAN = 41,
        TAAHHUT_ALAN = 42,
        VEKIL_OLAN = 43,
        SULH_OLAN_2 = 44,
        MUVAFAKAT_ALAN = 45,

        //KIRACI = 46,
        //KIRALAYAN = 47,
        KESIDECI = 48,

        REHIN_EDILEN = 49,
        //REHIN_VEREN = 50,
        //KREDI_VEREN = 51,
        //KREDI_ALAN = 52,
    }

    public enum TarafKodlari
    {
        M = 1,
        D = 2,
        K = 3,
        V = 4
    }

    public enum TarafKodu
    {
        Null = 0,
        Muvekkil = 1,
        Diger = 2,
        KarsiTaraf = 3,
        Vekil = 4
    }

    public enum TebligatHedefTip
    {
        İcra = 1,
        Dava = 2,
        Soruşturma = 3,
        Rücu = 4,
        Sözleşme = 5,
        Muhasebe = 6,
        Genel = 7,
        Belge = 8,
        Tebligat = 9,
        İş = 10
    }

    /// <summary>
    /// TDI_KOD_TEBLIGAT_KONU
    /// </summary>
    public enum TebligatKonu
    {
        HI_89_1 = 162,
        HI_89_2 = 163,
        HI_89_3 = 450,
        HESAP_KAT_IHTARNAMESI = 481 //10009
    }

    public enum TemsilYetkiKullanmaSekli
    {
        /// <summary>
        /// Default Değer
        /// </summary>
        Tek_Başına = 1,

        Birlikte = 2,
        Birlikte_ve_Tek_Başına = 3
    }

    public enum UygulamaTipi
    {
        Server = 0,
        Client = 1
    }
}