CREATE PROC _MalTakipDavalariByHacizChildId (
 @ID INT
)
AS
SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
                      AV001_TI_BIL_ISTIHKAK ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_ISTIHKAK.DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TI_BIL_ISTIHKAK.HACIZ_CHILD_ID = AV001_TI_BIL_HACIZ_CHILD.ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID
UNION
SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_HACIZ_CHILD.MESKENIYET_DAVA_FOY_ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID


UNION


SELECT    AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
                      AV001_TI_BIL_SATIS_CHILD ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_SATIS_CHILD.SATIS_ISLEMINI_SIKAYET_DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TI_BIL_SATIS_CHILD.HACIZ_CHILD_ID = AV001_TI_BIL_HACIZ_CHILD.ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID
UNION
SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_HACIZ_CHILD.MESKENIYET_DAVA_FOY_ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID


UNION


SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
                      AV001_TI_BIL_KIYMET_TAKDIRI ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_KIYMET_TAKDIRI.ITIRAZ_DAVA_FOY_ID OR AV001_TD_BIL_FOY.ID = AV001_TI_BIL_KIYMET_TAKDIRI.SIKAYET_DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TI_BIL_KIYMET_TAKDIRI.HACIZ_CHILD_ID = AV001_TI_BIL_HACIZ_CHILD.ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID
UNION
SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_HACIZ_CHILD.MESKENIYET_DAVA_FOY_ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID


UNION


SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
					  NN_DAVA_GAYRIMENKUL ON AV001_TD_BIL_FOY.ID = NN_DAVA_GAYRIMENKUL.DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON NN_DAVA_GAYRIMENKUL.GAYRIMENKUL_ID = AV001_TI_BIL_HACIZ_CHILD.GAYRIMENKUL_BILGI_ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID
UNION
SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
					  NN_DAVA_GAYRIMENKUL ON AV001_TD_BIL_FOY.ID = NN_DAVA_GAYRIMENKUL.DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_HACIZ_CHILD.MESKENIYET_DAVA_FOY_ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID


UNION


SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
					  NN_DAVA_GEMI_UCAK_ARAC ON AV001_TD_BIL_FOY.ID = NN_DAVA_GEMI_UCAK_ARAC.DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON NN_DAVA_GEMI_UCAK_ARAC.GEMI_UCAK_ARAC_ID = AV001_TI_BIL_HACIZ_CHILD.ARAC_BILGI_ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID
UNION
SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
					  NN_DAVA_GAYRIMENKUL ON AV001_TD_BIL_FOY.ID = NN_DAVA_GAYRIMENKUL.DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_HACIZ_CHILD.MESKENIYET_DAVA_FOY_ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID

UNION


SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
					  NN_DAVA_HACIZLI_MAL ON AV001_TD_BIL_FOY.ID = NN_DAVA_HACIZLI_MAL.DAVA_FOY_ID LEFT OUTER JOIN
                      AV001_TI_BIL_HACIZ_CHILD ON NN_DAVA_HACIZLI_MAL.HACIZ_CHILD_ID = AV001_TI_BIL_HACIZ_CHILD.ID
WHERE AV001_TI_BIL_HACIZ_CHILD.ID = @ID


