CREATE PROC [dbo].[_TUM_DOSYALAR_BulFoyNo_v3]
(
	@FOY_NO NVARCHAR(200),
	@SUBE_KOD_ID INT
)
AS
IF (@SUBE_KOD_ID != 2)
BEGIN
	SELECT DISTINCT
		I_FOY.ID, 
		I_FOY.FOY_NO, 
		I_FOY.ESAS_NO,
		I_FOY.ADLI_BIRIM_ADLIYE_ID,
		I_FOY.ADLI_BIRIM_NO_ID,
		I_FOY.ADLI_BIRIM_GOREV_ID,
		I_FOY.TAKIP_TARIHI,
		'ÝCRA' AS TIPI 
	FROM AV001_TI_BIL_FOY AS I_FOY 
	WHERE I_FOY.FOY_NO LIKE '%' + @FOY_NO + '%' AND I_FOY.SUBE_KOD_ID = @SUBE_KOD_ID
	UNION
	SELECT DISTINCT 
		D_FOY.ID,
		D_FOY.FOY_NO,
		D_FOY.ESAS_NO,
		D_FOY.ADLI_BIRIM_ADLIYE_ID,
		D_FOY.ADLI_BIRIM_NO_ID,
		D_FOY.ADLI_BIRIM_GOREV_ID,
		D_FOY.DAVA_TARIHI,
		'DAVA' AS TIPI 
	FROM AV001_TD_BIL_FOY AS D_FOY
	WHERE D_FOY.FOY_NO LIKE '%' + @FOY_NO + '%' AND D_FOY.SUBE_KOD_ID=@SUBE_KOD_ID
	UNION
	SELECT DISTINCT
		H_FOY.ID,
		H_FOY.HAZIRLIK_NO,
		H_FOY.HAZIRLIK_ESAS_NO,
		H_FOY.ADLI_BIRIM_ADLIYE_ID,
		H_FOY.ADLI_BIRIM_NO_ID,
		H_FOY.ADLI_BIRIM_GOREV_ID,
		H_FOY.HAZIRLIK_TARIH ,
		'SORUÞTURMA' AS TIPI
	FROM AV001_TD_BIL_HAZIRLIK AS H_FOY
	WHERE H_FOY.HAZIRLIK_NO LIKE '%' + @FOY_NO + '%' AND H_FOY.SUBE_KOD_ID=@SUBE_KOD_ID
	UNION 
	SELECT DISTINCT
		S_FOY.ID, 
		S_FOY.SOZLESME_NO, 
		S_FOY.NOTER_YEVMIYE_NO,
		S_FOY.ADLI_BIRIM_ADLIYE_ID,
		S_FOY.ADLI_BIRIM_NO_ID,
		S_FOY.ADLI_BIRIM_GOREV_ID,
		S_FOY.IMZA_TARIHI,
		'SÖZLEÞME' AS TIPI
	FROM AV001_TDI_BIL_SOZLESME  AS S_FOY 
	WHERE S_FOY.SOZLESME_NO LIKE '%' + @FOY_NO + '%' AND S_FOY.SUBE_KOD_ID=@SUBE_KOD_ID	
	UNION
	SELECT DISTINCT
		T_FOY.ID,
		T_FOY.TEBLIGAT_REFERANS_NO,
		T_FOY.TEBLIGAT_ESAS_NO,
		T_FOY.ADLI_BIRIM_ADLIYE_ID,
		T_FOY.ADLI_BIRIM_NO_ID,
		T_FOY.ADLI_BIRIM_GOREV_ID,
		T_FOY.HAZIRLAMA_TARIH ,
		'TEBLÝGAT' AS TIPI
	FROM AV001_TDI_BIL_TEBLIGAT AS T_FOY
	WHERE T_FOY.TEBLIGAT_REFERANS_NO LIKE  '%' +@FOY_NO + '%' AND T_FOY.SUBE_KOD_ID=@SUBE_KOD_ID
	UNION
	SELECT DISTINCT
		B_FOY.ID,
		B_FOY.BELGE_NO,
		B_FOY.ESAS_NO,
		B_FOY.ADLI_BIRIM_ADLIYE_ID,
		B_FOY.ADLI_BIRIM_NO_ID,
		B_FOY.ADLI_BIRIM_GOREV_ID,
		B_FOY.YAZILMA_TARIHI ,
		'BELGE' AS TIPI
	FROM AV001_TDIE_BIL_BELGE AS B_FOY
	WHERE B_FOY.BELGE_NO LIKE  '%' +@FOY_NO + '%' AND B_FOY.SUBE_KOD_ID=@SUBE_KOD_ID
	UNION
	SELECT DISTINCT
		P_FOY.ID,
		P_FOY.KOD AS FOY_NO,
		NULL AS ESAS_NO,
		NULL AS ADLIYE,
		NULL AS BIRIM,
		NULL AS GOREV,
		P_FOY.BASLANGIC_TARIHI ,
		'KLASÖR' AS TIPI
	FROM AV001_TDIE_BIL_PROJE AS P_FOY
	WHERE P_FOY.KOD LIKE '%' +@FOY_NO + '%' AND P_FOY.SUBE_KOD_ID=@SUBE_KOD_ID
END
ELSE
BEGIN
	SELECT DISTINCT
		I_FOY.ID, 
		I_FOY.FOY_NO, 
		I_FOY.ESAS_NO,
		I_FOY.ADLI_BIRIM_ADLIYE_ID,
		I_FOY.ADLI_BIRIM_NO_ID,
		I_FOY.ADLI_BIRIM_GOREV_ID,
		I_FOY.TAKIP_TARIHI,
		'ÝCRA' AS TIPI 
	FROM AV001_TI_BIL_FOY AS I_FOY 
	WHERE I_FOY.FOY_NO LIKE '%' + @FOY_NO + '%'
	UNION
	SELECT DISTINCT 
		D_FOY.ID,
		D_FOY.FOY_NO,
		D_FOY.ESAS_NO,
		D_FOY.ADLI_BIRIM_ADLIYE_ID,
		D_FOY.ADLI_BIRIM_NO_ID,
		D_FOY.ADLI_BIRIM_GOREV_ID,
		D_FOY.DAVA_TARIHI,
		'DAVA' AS TIPI 
	FROM AV001_TD_BIL_FOY AS D_FOY
	WHERE D_FOY.FOY_NO LIKE '%' + @FOY_NO + '%'
	UNION
	SELECT DISTINCT
		H_FOY.ID,
		H_FOY.HAZIRLIK_NO,
		H_FOY.HAZIRLIK_ESAS_NO,
		H_FOY.ADLI_BIRIM_ADLIYE_ID,
		H_FOY.ADLI_BIRIM_NO_ID,
		H_FOY.ADLI_BIRIM_GOREV_ID,
		H_FOY.HAZIRLIK_TARIH ,
		'SORUÞTURMA' AS TIPI
	FROM AV001_TD_BIL_HAZIRLIK AS H_FOY
	WHERE H_FOY.HAZIRLIK_NO LIKE '%' + @FOY_NO + '%'
	UNION 
	SELECT DISTINCT
		S_FOY.ID, 
		S_FOY.SOZLESME_NO, 
		S_FOY.NOTER_YEVMIYE_NO,
		S_FOY.ADLI_BIRIM_ADLIYE_ID,
		S_FOY.ADLI_BIRIM_NO_ID,
		S_FOY.ADLI_BIRIM_GOREV_ID,
		S_FOY.IMZA_TARIHI,
		'SÖZLEÞME' AS TIPI
	FROM AV001_TDI_BIL_SOZLESME  AS S_FOY 
	WHERE S_FOY.SOZLESME_NO LIKE '%' + @FOY_NO + '%'
	UNION
	SELECT DISTINCT
		T_FOY.ID,
		T_FOY.TEBLIGAT_REFERANS_NO,
		T_FOY.TEBLIGAT_ESAS_NO,
		T_FOY.ADLI_BIRIM_ADLIYE_ID,
		T_FOY.ADLI_BIRIM_NO_ID,
		T_FOY.ADLI_BIRIM_GOREV_ID,
		T_FOY.HAZIRLAMA_TARIH ,
		'TEBLÝGAT' AS TIPI
	FROM AV001_TDI_BIL_TEBLIGAT AS T_FOY
	WHERE T_FOY.TEBLIGAT_REFERANS_NO LIKE  '%' +@FOY_NO + '%'
	UNION
	SELECT DISTINCT
		B_FOY.ID,
		B_FOY.BELGE_NO,
		B_FOY.ESAS_NO,
		B_FOY.ADLI_BIRIM_ADLIYE_ID,
		B_FOY.ADLI_BIRIM_NO_ID,
		B_FOY.ADLI_BIRIM_GOREV_ID,
		B_FOY.YAZILMA_TARIHI ,
		'BELGE' AS TIPI
	FROM AV001_TDIE_BIL_BELGE AS B_FOY
	WHERE B_FOY.BELGE_NO LIKE  '%' +@FOY_NO + '%'
	UNION
	SELECT DISTINCT
		P_FOY.ID,
		P_FOY.KOD AS FOY_NO,
		NULL AS ESAS_NO,
		NULL AS ADLIYE,
		NULL AS BIRIM,
		NULL AS GOREV,
		P_FOY.BASLANGIC_TARIHI ,
		'KLASÖR' AS TIPI
	FROM AV001_TDIE_BIL_PROJE AS P_FOY
	WHERE P_FOY.KOD LIKE '%' +@FOY_NO + '%'
END
