//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace AdimAdimDavaKaydi.Util.UyapHelper {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdimAdimDavaKaydi.Util.UyapHelper.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to adres_.
        /// </summary>
        public static string adresIdPrefix
        {
            get
            {
                return ResourceManager.GetString("adresIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to alacakKalem_.
        /// </summary>
        public static string alacakKalemIdPrefix
        {
            get
            {
                return ResourceManager.GetString("alacakKalemIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Asıl Alacak.
        /// </summary>
        public static string AsilAlacak
        {
            get
            {
                return ResourceManager.GetString("AsilAlacak", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string AsilAlacakIlam
        {
            get
            {
                return ResourceManager.GetString("AsilAlacakIlam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7168.
        /// </summary>
        public static string AsilAlacakKalemKod
        {
            get
            {
                return ResourceManager.GetString("AsilAlacakKalemKod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string AsilAlacakKalemKodTipi
        {
            get
            {
                return ResourceManager.GetString("AsilAlacakKalemKodTipi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string AsilAlacakKalemKodTuru
        {
            get
            {
                return ResourceManager.GetString("AsilAlacakKalemKodTuru", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BSMV.
        /// </summary>
        public static string BSMV
        {
            get
            {
                return ResourceManager.GetString("BSMV", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string BSMVIlam
        {
            get
            {
                return ResourceManager.GetString("BSMVIlam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7177.
        /// </summary>
        public static string BSMVKod
        {
            get
            {
                return ResourceManager.GetString("BSMVKod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string BSMVKodTipi
        {
            get
            {
                return ResourceManager.GetString("BSMVKodTipi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string BSMVKodTuru
        {
            get
            {
                return ResourceManager.GetString("BSMVKodTuru", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  -.
        /// </summary>
        public static string CariAdAyirac
        {
            get
            {
                return ResourceManager.GetString("CariAdAyirac", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Çek Tazminatı.
        /// </summary>
        public static string CekTazminati
        {
            get
            {
                return ResourceManager.GetString("CekTazminati", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string CekTazminatiIlam
        {
            get
            {
                return ResourceManager.GetString("CekTazminatiIlam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7176.
        /// </summary>
        public static string CekTazminatiKod
        {
            get
            {
                return ResourceManager.GetString("CekTazminatiKod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string CekTazminatiKodTipi
        {
            get
            {
                return ResourceManager.GetString("CekTazminatiKodTipi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string CekTazminatiKodTuru
        {
            get
            {
                return ResourceManager.GetString("CekTazminatiKodTuru", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string CinsiyetBayan
        {
            get
            {
                return ResourceManager.GetString("CinsiyetBayan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string CinsiyetErkek
        {
            get
            {
                return ResourceManager.GetString("CinsiyetErkek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DosyaBelirleyicisi
        {
            get
            {
                return ResourceManager.GetString("DosyaBelirleyicisi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dosya_.
        /// </summary>
        public static string dosyaIdPrefix
        {
            get
            {
                return ResourceManager.GetString("dosyaIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E
        {
            get
            {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string Evet
        {
            get
            {
                return ResourceManager.GetString("Evet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to exchange.dtd.
        /// </summary>
        public static string ExchangeDosyasiAdresi
        {
            get
            {
                return ResourceManager.GetString("ExchangeDosyasiAdresi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GecmisGunFaizi
        {
            get
            {
                return ResourceManager.GetString("GecmisGunFaizi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Genel İcra Dairesi.
        /// </summary>
        public static string GenelIcraDairesi
        {
            get
            {
                return ResourceManager.GetString("GenelIcraDairesi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string H
        {
            get
            {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string Hayir
        {
            get
            {
                return ResourceManager.GetString("Hayir", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to taraf_.
        /// </summary>
        public static string icraAlacakNedenTarafIdPrefix
        {
            get
            {
                return ResourceManager.GetString("icraAlacakNedenTarafIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to taraf_.
        /// </summary>
        public static string icraDosyaTarafIdPrefix
        {
            get
            {
                return ResourceManager.GetString("icraDosyaTarafIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kisiKurumBilgileri_.
        /// </summary>
        public static string kisiKurumIdPrefix
        {
            get
            {
                return ResourceManager.GetString("kisiKurumIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kisiTumBilgileri_.
        /// </summary>
        public static string kisiTumBilgileriIdPrefix
        {
            get
            {
                return ResourceManager.GetString("kisiTumBilgileriIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Komisyon.
        /// </summary>
        public static string Komisyon
        {
            get
            {
                return ResourceManager.GetString("Komisyon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string KomisyonIlam
        {
            get
            {
                return ResourceManager.GetString("KomisyonIlam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7174.
        /// </summary>
        public static string KomisyonKod
        {
            get
            {
                return ResourceManager.GetString("KomisyonKod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string KomisyonKodTip
        {
            get
            {
                return ResourceManager.GetString("KomisyonKodTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string KomisyonKodTur
        {
            get
            {
                return ResourceManager.GetString("KomisyonKodTur", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kontrat_.
        /// </summary>
        public static string kontratIdPrefix
        {
            get
            {
                return ResourceManager.GetString("kontratIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kontratKefil_.
        /// </summary>
        public static string kontratKefilIdPrefix
        {
            get
            {
                return ResourceManager.GetString("kontratKefilIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.00.
        /// </summary>
        public static string OlmasiGerekenPulDegeriDefault
        {
            get
            {
                return ResourceManager.GetString("OlmasiGerekenPulDegeriDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Protesto masrafı.
        /// </summary>
        public static string ProtestoMasrafi
        {
            get
            {
                return ResourceManager.GetString("ProtestoMasrafi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string ProtestoMasrafiIlam
        {
            get
            {
                return ResourceManager.GetString("ProtestoMasrafiIlam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7169.
        /// </summary>
        public static string ProtestoMasrafiKalemKod
        {
            get
            {
                return ResourceManager.GetString("ProtestoMasrafiKalemKod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string ProtestoMasrafiKodTipi
        {
            get
            {
                return ResourceManager.GetString("ProtestoMasrafiKodTipi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string ProtestoMasrafiKodTuru
        {
            get
            {
                return ResourceManager.GetString("ProtestoMasrafiKodTuru", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string SozlesmeTurB
        {
            get
            {
                return ResourceManager.GetString("SozlesmeTurB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SozlesmeTurS
        {
            get
            {
                return ResourceManager.GetString("SozlesmeTurS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to taraf_.
        /// </summary>
        public static string taraf
        {
            get
            {
                return ResourceManager.GetString("taraf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.00.
        /// </summary>
        public static string UzerindekiPulDegeriDefault
        {
            get
            {
                return ResourceManager.GetString("UzerindekiPulDegeriDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to vekil_.
        /// </summary>
        public static string vekilIdPrefix
        {
            get
            {
                return ResourceManager.GetString("vekilIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VekilKisi_.
        /// </summary>
        public static string vekilKisiIdPrefix
        {
            get
            {
                return ResourceManager.GetString("vekilKisiIdPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string VekilTipiB
        {
            get
            {
                return ResourceManager.GetString("VekilTipiB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.1.
        /// </summary>
        public static string XmlHeaderVersion
        {
            get
            {
                return ResourceManager.GetString("XmlHeaderVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;.
        /// </summary>
        public static string XmlReplace2StringPart1
        {
            get
            {
                return ResourceManager.GetString("XmlReplace2StringPart1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string XmlReplace2StringPart2
        {
            get
            {
                return ResourceManager.GetString("XmlReplace2StringPart2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;.
        /// </summary>
        public static string XmlReplaceStringPart1
        {
            get
            {
                return ResourceManager.GetString("XmlReplaceStringPart1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;  encoding=&quot;ISO-8859-9&quot;?&gt;.
        /// </summary>
        public static string XmlReplaceStringPart21
        {
            get
            {
                return ResourceManager.GetString("XmlReplaceStringPart21", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE exchangeData SYSTEM &quot;{0}&quot;&gt;.
        /// </summary>
        public static string XmlReplaceStringPart22
        {
            get
            {
                return ResourceManager.GetString("XmlReplaceStringPart22", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to yeni alacak kalemi.
        /// </summary>
        public static string YeniAlacakKalemi
        {
            get
            {
                return ResourceManager.GetString("YeniAlacakKalemi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string YeniAlacakKalemiIlam
        {
            get
            {
                return ResourceManager.GetString("YeniAlacakKalemiIlam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7937.
        /// </summary>
        public static string YeniAlacakKalemiKod
        {
            get
            {
                return ResourceManager.GetString("YeniAlacakKalemiKod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string YeniAlacakKalemiKodTipi
        {
            get
            {
                return ResourceManager.GetString("YeniAlacakKalemiKodTipi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string YeniAlacakKalemiKodTuru
        {
            get
            {
                return ResourceManager.GetString("YeniAlacakKalemiKodTuru", resourceCulture);
            }
        }
    }
}
