//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvukatProLib.GlobalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stringler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvukatProLib.GlobalResource.Stringler", typeof(Stringler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
                
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;-&quot;.
        /// </summary>
        internal static string Ayrac1 {
            get {
                return ResourceManager.GetString("Ayrac1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/&quot;.
        /// </summary>
        internal static string Ayrac2 {
            get {
                return ResourceManager.GetString("Ayrac2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database=.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to @&quot;HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\&quot;.
        /// </summary>
        internal static string LocalAdres {
            get {
                return ResourceManager.GetString("LocalAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pwd=.
        /// </summary>
        internal static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server=.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to uid=.
        /// </summary>
        internal static string uid {
            get {
                return ResourceManager.GetString("uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;avp&quot;.
        /// </summary>
        internal static string Value1 {
            get {
                return ResourceManager.GetString("Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;pro&quot;.
        /// </summary>
        internal static string Value2 {
            get {
                return ResourceManager.GetString("Value2", resourceCulture);
            }
        }
        
                
    }
}
