//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVPUpdater.Properties {
    
    
    //[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    //[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    //internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
    //    private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
    //    public static Settings Default {
    //        get {
    //            return defaultInstance;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("2")]
    //    public int KontrolTipi {
    //        get {
    //            return ((int)(this["KontrolTipi"]));
    //        }
    //        set {
    //            this["KontrolTipi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("0")]
    //    public int KontrolGunu {
    //        get {
    //            return ((int)(this["KontrolGunu"]));
    //        }
    //        set {
    //            this["KontrolGunu"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("01/01/2012 17:00:00")]
    //    public global::System.DateTime KontrolSaati {
    //        get {
    //            return ((global::System.DateTime)(this["KontrolSaati"]));
    //        }
    //        set {
    //            this["KontrolSaati"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool ProgramiGuncelle {
    //        get {
    //            return ((bool)(this["ProgramiGuncelle"]));
    //        }
    //        set {
    //            this["ProgramiGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool TablolariGuncelle {
    //        get {
    //            return ((bool)(this["TablolariGuncelle"]));
    //        }
    //        set {
    //            this["TablolariGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool VerileriGuncelle {
    //        get {
    //            return ((bool)(this["VerileriGuncelle"]));
    //        }
    //        set {
    //            this["VerileriGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool ViewleriGuncelle {
    //        get {
    //            return ((bool)(this["ViewleriGuncelle"]));
    //        }
    //        set {
    //            this["ViewleriGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool ProcedureleriGuncelle {
    //        get {
    //            return ((bool)(this["ProcedureleriGuncelle"]));
    //        }
    //        set {
    //            this["ProcedureleriGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool TriggerlariGuncelle {
    //        get {
    //            return ((bool)(this["TriggerlariGuncelle"]));
    //        }
    //        set {
    //            this["TriggerlariGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("ProjeYedek")]
    //    public string ProgramYedekKlasoru {
    //        get {
    //            return ((string)(this["ProgramYedekKlasoru"]));
    //        }
    //        set {
    //            this["ProgramYedekKlasoru"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("SQLYedek")]
    //    public string SQLYedekKlasoru {
    //        get {
    //            return ((string)(this["SQLYedekKlasoru"]));
    //        }
    //        set {
    //            this["SQLYedekKlasoru"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("ftp://94.138.206.50")]
    //    public string SunucuAdresi {
    //        get {
    //            return ((string)(this["SunucuAdresi"]));
    //        }
    //        set {
    //            this["SunucuAdresi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool FunctionlariGuncelle {
    //        get {
    //            return ((bool)(this["FunctionlariGuncelle"]));
    //        }
    //        set {
    //            this["FunctionlariGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("data source=94.138.206.50\\SQLEXPRESS;database=AVPYONETIM;uid=avp;pwd=PASSWRD1;")]
    //    public string cnString {
    //        get {
    //            return ((string)(this["cnString"]));
    //        }
    //        set {
    //            this["cnString"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool CetvelleriGuncelle {
    //        get {
    //            return ((bool)(this["CetvelleriGuncelle"]));
    //        }
    //        set {
    //            this["CetvelleriGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool RaporlariGuncelle {
    //        get {
    //            return ((bool)(this["RaporlariGuncelle"]));
    //        }
    //        set {
    //            this["RaporlariGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    //    public bool SablonlariGuncelle {
    //        get {
    //            return ((bool)(this["SablonlariGuncelle"]));
    //        }
    //        set {
    //            this["SablonlariGuncelle"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("aykutbastug")]
    //    public string ftpUid {
    //        get {
    //            return ((string)(this["ftpUid"]));
    //        }
    //        set {
    //            this["ftpUid"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("PASSWRD1")]
    //    public string ftpPwd {
    //        get {
    //            return ((string)(this["ftpPwd"]));
    //        }
    //        set {
    //            this["ftpPwd"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool SqlYedekAlindi {
    //        get {
    //            return ((bool)(this["SqlYedekAlindi"]));
    //        }
    //        set {
    //            this["SqlYedekAlindi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool ProgramYedekAlindi {
    //        get {
    //            return ((bool)(this["ProgramYedekAlindi"]));
    //        }
    //        set {
    //            this["ProgramYedekAlindi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool DosyaIndirmeYapildi {
    //        get {
    //            return ((bool)(this["DosyaIndirmeYapildi"]));
    //        }
    //        set {
    //            this["DosyaIndirmeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool DosyaGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["DosyaGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["DosyaGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool TabloGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["TabloGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["TabloGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool TanimGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["TanimGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["TanimGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool CetvelGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["CetvelGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["CetvelGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool RaporGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["RaporGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["RaporGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool SablonGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["SablonGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["SablonGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool KeyGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["KeyGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["KeyGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool ViewGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["ViewGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["ViewGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool ProcedureGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["ProcedureGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["ProcedureGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool FunctionGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["FunctionGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["FunctionGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool TriggerGuncellemeYapildi {
    //        get {
    //            return ((bool)(this["TriggerGuncellemeYapildi"]));
    //        }
    //        set {
    //            this["TriggerGuncellemeYapildi"] = value;
    //        }
    //    }
        
    //    [global::System.Configuration.UserScopedSettingAttribute()]
    //    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    //    public bool VeritabaniYedegiAlinsin {
    //        get {
    //            return ((bool)(this["VeritabaniYedegiAlinsin"]));
    //        }
    //        set {
    //            this["VeritabaniYedegiAlinsin"] = value;
    //        }
    //    }
    //}
}
