//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvukatProRaporlar.Raport.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
                
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvukatProRaporlar.Raport.Util.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap ayar_16x16 {
            get {
                object obj = ResourceManager.GetObject("ayar_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ayar_40x40 {
            get {
                object obj = ResourceManager.GetObject("ayar_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap belgeler40x40 {
            get {
                object obj = ResourceManager.GetObject("belgeler40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buro_istatistikleri40x40 {
            get {
                object obj = ResourceManager.GetObject("buro_istatistikleri40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_add {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_cevir {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_cevir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_delete {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_editor {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_email {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_excel {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_first {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_fscreen {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_fscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_getir {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_getir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_last {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_next {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_previous {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_printer {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dnext_12x12_tick {
            get {
                object obj = ResourceManager.GetObject("dnext_12x12_tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap doc {
            get {
                object obj = ResourceManager.GetObject("doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EV {
            get {
                object obj = ResourceManager.GetObject("EV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EV_40X40 {
            get {
                object obj = ResourceManager.GetObject("EV_40X40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap excel03 {
            get {
                object obj = ResourceManager.GetObject("excel03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap favorite_22x22 {
            get {
                object obj = ResourceManager.GetObject("favorite_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap gonder12x12 {
            get {
                object obj = ResourceManager.GetObject("gonder12x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap gonder40x40 {
            get {
                object obj = ResourceManager.GetObject("gonder40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap gorusmeler40x40 {
            get {
                object obj = ResourceManager.GetObject("gorusmeler40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hesapla_40x40 {
            get {
                object obj = ResourceManager.GetObject("hesapla_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap html {
            get {
                object obj = ResourceManager.GetObject("html", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap iliskili_dosyalar_red_40x40 {
            get {
                object obj = ResourceManager.GetObject("iliskili_dosyalar_red_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap kapat_40x40 {
            get {
                object obj = ResourceManager.GetObject("kapat_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap kutuphane_40x40 {
            get {
                object obj = ResourceManager.GetObject("kutuphane_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap kutuphane2_40x40 {
            get {
                object obj = ResourceManager.GetObject("kutuphane2_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mahkeme_40x40 {
            get {
                object obj = ResourceManager.GetObject("mahkeme_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Mail2_40X40 {
            get {
                object obj = ResourceManager.GetObject("Mail2_40X40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap meslek_rehberi40x40 {
            get {
                object obj = ResourceManager.GetObject("meslek_rehberi40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Micr_Office_Word_40x40 {
            get {
                object obj = ResourceManager.GetObject("Micr_Office_Word_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pdf_40x40 {
            get {
                object obj = ResourceManager.GetObject("pdf_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap posta2_40x40 {
            get {
                object obj = ResourceManager.GetObject("posta2_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap proje40x40 {
            get {
                object obj = ResourceManager.GetObject("proje40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap projeicon_40x40 {
            get {
                object obj = ResourceManager.GetObject("projeicon_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap savcilik_40x40 {
            get {
                object obj = ResourceManager.GetObject("savcilik_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sihirbaz1_16x16 {
            get {
                object obj = ResourceManager.GetObject("sihirbaz1_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sihirbaz2 {
            get {
                object obj = ResourceManager.GetObject("sihirbaz2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tablo_40x40 {
            get {
                object obj = ResourceManager.GetObject("tablo_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap takip_islemleri40x40 {
            get {
                object obj = ResourceManager.GetObject("takip_islemleri40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap taraf_renklerini_belirle40x40 {
            get {
                object obj = ResourceManager.GetObject("taraf_renklerini_belirle40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tarihce {
            get {
                object obj = ResourceManager.GetObject("tarihce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap yardim {
            get {
                object obj = ResourceManager.GetObject("yardim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap yazdir_40x40 {
            get {
                object obj = ResourceManager.GetObject("yazdir_40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
