//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvukatProLib.Hesap.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
                
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvukatProLib.Hesap.Views.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[_AV001_TDI_BIL_MASRAF_AVANS_CariHesapOlustur_V4]
        ///(
        ///	@MASRAF_AVANS_ID INT
        ///)
        ///AS
        ///
        ///DECLARE @TARAF_TABLOSU TABLE(ID INT)
        ///
        ///DECLARE
        ///
        ///@TAMPON_BORC MONEY,
        ///@ONCEKI_HESAP_ID INT,
        ///
        ///--MASRAF AVANS TABLOSUNDAN ALINACAKLAR
        ///@CARI_ID INT  ,
        ///@REFERANS_NO NVARCHAR(200),
        ///@ACIKLAMA NVARCHAR(MAX),
        ///@KAYIT_TARIHI datetime,
        ///@KLASOR_KODU NVARCHAR(250),
        ///@SUBE_KODU smallint,
        ///@KONTROL_NE_ZAMAN datetime,
        ///@KONTROL_KIM NVARCHAR(250),
        ///@KONTROL_VERSIYON int,
        ///@STAMP smallint,
        ///@KONTROL_KIM_ID INT ,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _AV001_TDI_BIL_MASRAF_AVANS_CariHesapOlustur {
            get {
                return ResourceManager.GetString("_AV001_TDI_BIL_MASRAF_AVANS_CariHesapOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[_AV001_TI_BIL_BORCLU_ODEME_CariHesapOlustur_V3]
        ///(
        ///	@ODEME_ID INT
        ///)
        ///AS
        ///
        ///DECLARE @TARAF_TABLOSU TABLE( CARI_ID INT, ODEYEN BIT)
        ///DECLARE
        ///	@ODEME_TIP_ID int	,
        ///	@ICRA_FOY_ID int	,
        ///	@ODEME_TARIHI smalldatetime	,
        ///	@ODEME_MIKTAR_DOVIZ_ID int	,
        ///	@ODEME_MIKTAR money	,
        ///	@ACIKLAMA NVARCHAR(150)	,
        ///	@KAYIT_TARIHI datetime	,
        ///	@KLASOR_KODU NVARCHAR(200)	,
        ///	@SUBE_KODU smallint	,
        ///	@KONTROL_NE_ZAMAN datetime	,
        ///	@KONTROL_KIM NVARCHAR(200)	,
        ///	@KONTROL_VERSIYON int	,
        ///	@STAMP smallint	,
        ///	@K [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _AV001_TI_BIL_BORCLU_ODEME_CariHesapOlustur {
            get {
                return ResourceManager.GetString("_AV001_TI_BIL_BORCLU_ODEME_CariHesapOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[_AV001_TI_BIL_MUVEKKILE_ODEME_CariHesapOlustur_V2]
        ///(
        ///	@MUVEKKILE_ODEME_ID INT
        ///)
        ///AS
        ///DECLARE @TARAF_TABLOSU TABLE ( CARI_ID INT, ODEYENMI BIT )
        ///DECLARE
        ///	@CARI_ID INT,
        ///	@ODEYENMI BIT,
        ///
        ///	@ODEME_TIP_ID int	,
        ///	@ICRA_FOY_ID INT ,
        ///	@DAVA_FOY_ID INT ,
        ///	@HAZIRLIK_FOY_ID INT ,
        ///	@ODEME_TARIHI SMALLDATETIME ,
        ///	@MIKTAR_DOVIZ_ID INT ,
        ///	@MIKTAR money ,	
        ///	@ACIKLAMA NVARCHAR(MAX),
        ///	@KAYIT_TARIHI DATETIME ,
        ///	@KLASOR_KODU NVARCHAR(200) ,
        ///	@SUBE_KODU SMALLINT ,
        ///	@KONTROL_NE_ZAMAN DATETIME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _AV001_TI_BIL_MUVEKKILE_ODEME_CariHesapOlustur {
            get {
                return ResourceManager.GetString("_AV001_TI_BIL_MUVEKKILE_ODEME_CariHesapOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC _MalTakipDavalariByHacizChildId (
        /// @ID INT
        ///)
        ///AS
        ///SELECT     AV001_TD_BIL_FOY.ID,AV001_TD_BIL_FOY.FOY_NO,AV001_TD_BIL_FOY.ESAS_NO,AV001_TD_BIL_FOY.ADLI_BIRIM_ADLIYE_ID,AV001_TD_BIL_FOY.ADLI_BIRIM_NO_ID,
        ///AV001_TD_BIL_FOY.ADLI_BIRIM_GOREV_ID,AV001_TD_BIL_FOY.DAVA_TARIHI,AV001_TD_BIL_FOY.DAVA_TALEP_ID,AV001_TD_BIL_FOY.SUBE_KOD_ID
        ///FROM         AV001_TD_BIL_FOY LEFT OUTER JOIN
        ///                      AV001_TI_BIL_ISTIHKAK ON AV001_TD_BIL_FOY.ID = AV001_TI_BIL_ISTIHKAK.DAVA_FOY_ID LEFT OUTER JOIN
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _MalTakipDavalariByHacizChildId {
            get {
                return ResourceManager.GetString("_MalTakipDavalariByHacizChildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[_TUM_DOSYALAR_BulCariId_V3]
        ///(
        ///	@CARI_ID INT,
        ///	@SUBE_KOD_ID INT
        ///)
        ///AS
        ///IF (@SUBE_KOD_ID != 2)
        ///BEGIN
        ///	SELECT DISTINCT
        ///		I_FOY.ID, 
        ///		I_FOY.FOY_NO, 
        ///		I_FOY.ESAS_NO,
        ///		I_FOY.ADLI_BIRIM_ADLIYE_ID,
        ///		I_FOY.ADLI_BIRIM_NO_ID,
        ///		I_FOY.ADLI_BIRIM_GOREV_ID,
        ///		I_FOY.TAKIP_TARIHI,
        ///		&apos;İCRA&apos; AS TIPI 
        ///	FROM AV001_TI_BIL_FOY AS I_FOY 
        ///		LEFT JOIN AV001_TI_BIL_FOY_TARAF AS I_TARAF ON I_FOY.ID = I_TARAF.ICRA_FOY_ID 
        ///		LEFT JOIN AV001_TI_BIL_FOY_SORUMLU_AVUKAT AS I_SORUMLU ON  I_FOY.ID = I_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_TUM_DOSYALAR_BulCari {
            get {
                return ResourceManager.GetString("SP_TUM_DOSYALAR_BulCari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[_TUM_DOSYALAR_BulEsasNo_V2]
        ///(
        ///	@ESAS_NO NVARCHAR(200),
        ///	@SUBE_KOD_ID INT
        ///)
        ///AS
        ///IF (@SUBE_KOD_ID != 2)
        ///BEGIN
        ///	SELECT DISTINCT
        ///		I_FOY.ID, 
        ///		I_FOY.FOY_NO, 
        ///		I_FOY.ESAS_NO,
        ///		I_FOY.ADLI_BIRIM_ADLIYE_ID,
        ///		I_FOY.ADLI_BIRIM_NO_ID,
        ///		I_FOY.ADLI_BIRIM_GOREV_ID,
        ///		I_FOY.TAKIP_TARIHI,
        ///		&apos;İCRA&apos; AS TIPI 
        ///	FROM AV001_TI_BIL_FOY AS I_FOY 
        ///	WHERE I_FOY.ESAS_NO LIKE &apos;%&apos; + @ESAS_NO + &apos;%&apos; AND I_FOY.SUBE_KOD_ID=@SUBE_KOD_ID
        ///	 UNION
        ///	SELECT DISTINCT 
        ///		D_FOY.ID,
        ///		D_FOY.FOY_NO,
        ///		D_F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_TUM_DOSYALAR_BulEsasNo {
            get {
                return ResourceManager.GetString("SP_TUM_DOSYALAR_BulEsasNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[_TUM_DOSYALAR_BulFoyNo_v3]
        ///(
        ///	@FOY_NO NVARCHAR(200),
        ///	@SUBE_KOD_ID INT
        ///)
        ///AS
        ///IF (@SUBE_KOD_ID != 2)
        ///BEGIN
        ///	SELECT DISTINCT
        ///		I_FOY.ID, 
        ///		I_FOY.FOY_NO, 
        ///		I_FOY.ESAS_NO,
        ///		I_FOY.ADLI_BIRIM_ADLIYE_ID,
        ///		I_FOY.ADLI_BIRIM_NO_ID,
        ///		I_FOY.ADLI_BIRIM_GOREV_ID,
        ///		I_FOY.TAKIP_TARIHI,
        ///		&apos;İCRA&apos; AS TIPI 
        ///	FROM AV001_TI_BIL_FOY AS I_FOY 
        ///	WHERE I_FOY.FOY_NO LIKE &apos;%&apos; + @FOY_NO + &apos;%&apos; AND I_FOY.SUBE_KOD_ID = @SUBE_KOD_ID
        ///	UNION
        ///	SELECT DISTINCT 
        ///		D_FOY.ID,
        ///		D_FOY.FOY_NO,
        ///		D_FOY. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP_TUM_DOSYALAR_BulFoyNo {
            get {
                return ResourceManager.GetString("SP_TUM_DOSYALAR_BulFoyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROCedure [dbo].[spDeleteRows]
        ////* 
        ///Recursive row delete procedure. 
        ///
        ///It deletes all rows in the table specified that conform to the criteria selected, 
        ///while also deleting any child/grandchild records and so on.  This is designed to do the 
        ///same sort of thing as Access&apos;s cascade delete function. It first reads the sysforeignkeys 
        ///table to find any child tables, then deletes the soon-to-be orphan records from them using 
        ///recursive calls to this procedure. Once all child records are gone, the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spDeleteRows {
            get {
                return ResourceManager.GetString("spDeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROCedure [dbo].[spDeleteRowsPreview]
        ////* 
        ///Recursive row delete procedure. 
        ///
        ///It deletes all rows in the table specified that conform to the criteria selected, 
        ///while also deleting any child/grandchild records and so on.  This is designed to do the 
        ///same sort of thing as Access&apos;s cascade delete function. It first reads the sysforeignkeys 
        ///table to find any child tables, then deletes the soon-to-be orphan records from them using 
        ///recursive calls to this procedure. Once all child records are go [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spDeleteRowsPreview {
            get {
                return ResourceManager.GetString("spDeleteRowsPreview", resourceCulture);
            }
        }
    }
}
