//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvukatProLib.Bakim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stringler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
                
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvukatProLib.Bakim.Stringler", typeof(Stringler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;AsistanAyarlari&quot;.
        /// </summary>
        internal static string AsistanAyarlari {
            get {
                return ResourceManager.GetString("AsistanAyarlari", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        internal static string Bos {
            get {
                return ResourceManager.GetString("Bos", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to &quot;DNSAyarlari&quot;.
        /// </summary>
        internal static string DNSAyarlari {
            get {
                return ResourceManager.GetString("DNSAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;FirmaTanimlari&quot;.
        /// </summary>
        internal static string FirmaTanimlari {
            get {
                return ResourceManager.GetString("FirmaTanimlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;GrupTanimlari&quot;.
        /// </summary>
        internal static string GrupTanimlari {
            get {
                return ResourceManager.GetString("GrupTanimlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;InternetKontrolAdresi&quot;.
        /// </summary>
        internal static string InternetKontrolAdresi {
            get {
                return ResourceManager.GetString("InternetKontrolAdresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;IslemYetkileri&quot;.
        /// </summary>
        internal static string IslemYetkileri {
            get {
                return ResourceManager.GetString("IslemYetkileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;KanunRaporSablonYukle&quot;.
        /// </summary>
        internal static string KanunRaporSablonYukle {
            get {
                return ResourceManager.GetString("KanunRaporSablonYukle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;KayitliKullaniciBilgileri&quot;.
        /// </summary>
        internal static string KayıtliKullaniciBilgileri {
            get {
                return ResourceManager.GetString("KayıtliKullaniciBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;KopyaKorumaCihazi&quot;.
        /// </summary>
        internal static string KopyaKorumaCihazi {
            get {
                return ResourceManager.GetString("KopyaKorumaCihazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;KullaniciGruplari&quot;.
        /// </summary>
        internal static string KullaniciGruplari {
            get {
                return ResourceManager.GetString("KullaniciGruplari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;KullaniciTanımlari&quot;.
        /// </summary>
        internal static string KullaniciTanimlari {
            get {
                return ResourceManager.GetString("KullaniciTanimlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;LisansSonucu&quot;.
        /// </summary>
        internal static string LisansSonucu {
            get {
                return ResourceManager.GetString("LisansSonucu", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to &quot;OtomatikGiderAyari&quot;.
        /// </summary>
        internal static string OtomatikGiderAyari {
            get {
                return ResourceManager.GetString("OtomatikGiderAyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        internal static string ProgramIsmi {
            get {
                return ResourceManager.GetString("ProgramIsmi", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to &quot;SMSAyarlari&quot;.
        /// </summary>
        internal static string SMSAyarlari {
            get {
                return ResourceManager.GetString("SMSAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;SunucuKurulumTopluAyarlari&quot;.
        /// </summary>
        internal static string SunucuKurulumTopluAyarlari {
            get {
                return ResourceManager.GetString("SunucuKurulumTopluAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Tamir&quot;.
        /// </summary>
        internal static string Tamir {
            get {
                return ResourceManager.GetString("Tamir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;TarihceAyarlari&quot;.
        /// </summary>
        internal static string TarihceAyarlari {
            get {
                return ResourceManager.GetString("TarihceAyarlari", resourceCulture);
            }
        }
               
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VeriTabaniHataKontrol&quot;.
        /// </summary>
        internal static string VeriTabaniHataKontrol {
            get {
                return ResourceManager.GetString("VeriTabaniHataKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VeriTabaniKullanicilari&quot;.
        /// </summary>
        internal static string VeriTabaniKullanicilari {
            get {
                return ResourceManager.GetString("VeriTabaniKullanicilari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VeriTabaniOlustur&quot;.
        /// </summary>
        internal static string VeriTabaniOlustur {
            get {
                return ResourceManager.GetString("VeriTabaniOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VeritabaniSunucuİslemleri&quot;.
        /// </summary>
        internal static string VeriTabaniSunucuİslemleri {
            get {
                return ResourceManager.GetString("VeriTabaniSunucuİslemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VeriTabaniYazilim&quot;.
        /// </summary>
        internal static string VeriTabaniYazilim {
            get {
                return ResourceManager.GetString("VeriTabaniYazilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Yüklü Bir Veri Tabani Yazılımı Bulunmamaktadır Yüklemek İçin Butona Tıklayınız .
        /// </summary>
        internal static string VeriTabaniYazilimBilgisi {
            get {
                return ResourceManager.GetString("VeriTabaniYazilimBilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteminiz de .
        /// </summary>
        internal static string VeriTabaniYazilimBilgisi1 {
            get {
                return ResourceManager.GetString("VeriTabaniYazilimBilgisi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Uyumlu Bir Veri Tabani Yüklüdür .
        /// </summary>
        internal static string VeriTabaniYazilimBilgisi2 {
            get {
                return ResourceManager.GetString("VeriTabaniYazilimBilgisi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemdeki Veri Tabani Yaziliminin Verisonu : .
        /// </summary>
        internal static string VeriTabaniYazilimBilgisi3 {
            get {
                return ResourceManager.GetString("VeriTabaniYazilimBilgisi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemdeki Veri Tabani Yaziliminin SP Versiyonu: .
        /// </summary>
        internal static string VeriTabaniYazilimBilgisi4 {
            get {
                return ResourceManager.GetString("VeriTabaniYazilimBilgisi4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AvukatPro VeriTabanını Sisteminizde Yüklü Veri Tabanı Yönetim Sistemini Kullanarak Çalıştırabilirsiniz..
        /// </summary>
        internal static string VeriTabaniYazilimBilgisi5 {
            get {
                return ResourceManager.GetString("VeriTabaniYazilimBilgisi5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;YedegiSistemeDon&quot;.
        /// </summary>
        internal static string YedegiSistemeDon {
            get {
                return ResourceManager.GetString("YedegiSistemeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;YedekAl&quot;.
        /// </summary>
        internal static string YedekAl {
            get {
                return ResourceManager.GetString("YedekAl", resourceCulture);
            }
        }
    }
}
