//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdimAdimDavaKaydi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesSqlQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourcesSqlQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdimAdimDavaKaydi.ResourcesSqlQuery", typeof(ResourcesSqlQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [MUSTERI]
        ///GO
        ////****** Object:  StoredProcedure [dbo].[spDeleteRows]    Script Date: 12/19/2009 17:06:02 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE Procedure [dbo].[spDeleteRows]
        ////* 
        ///Recursive row delete procedure. 
        ///
        ///It deletes all rows in the table specified that conform to the criteria selected, 
        ///while also deleting any child/grandchild records and so on.  This is designed to do the 
        ///same sort of thing as Access&apos;s cascade delete function. It first reads the sysforeignke [rest of string was truncated]&quot;;.
        /// </summary>
        public static string spDeleteRows {
            get {
                return ResourceManager.GetString("spDeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [MUSTERI]
        ///GO
        ////****** Object:  StoredProcedure [dbo].[spDeleteRowsPreview]    Script Date: 12/19/2009 17:06:33 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE Procedure [dbo].[spDeleteRowsPreview]
        ////* 
        ///Recursive row delete procedure. 
        ///
        ///It deletes all rows in the table specified that conform to the criteria selected, 
        ///while also deleting any child/grandchild records and so on.  This is designed to do the 
        ///same sort of thing as Access&apos;s cascade delete function. It first reads th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string spDeleteRowsPreview {
            get {
                return ResourceManager.GetString("spDeleteRowsPreview", resourceCulture);
            }
        }
    }
}
