#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvukatProLib.PaketYonetimi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AVP_MYS")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCS_KOD_PAKET(CS_KOD_PAKET instance);
    partial void UpdateCS_KOD_PAKET(CS_KOD_PAKET instance);
    partial void DeleteCS_KOD_PAKET(CS_KOD_PAKET instance);
    partial void InsertCS_KOD_PAKET_NN_FORM(CS_KOD_PAKET_NN_FORM instance);
    partial void UpdateCS_KOD_PAKET_NN_FORM(CS_KOD_PAKET_NN_FORM instance);
    partial void DeleteCS_KOD_PAKET_NN_FORM(CS_KOD_PAKET_NN_FORM instance);
    partial void InsertCS_KOD_FORM_LISTESI(CS_KOD_FORM_LISTESI instance);
    partial void UpdateCS_KOD_FORM_LISTESI(CS_KOD_FORM_LISTESI instance);
    partial void DeleteCS_KOD_FORM_LISTESI(CS_KOD_FORM_LISTESI instance);
    partial void InsertCS_KOD_KONTROL_LISTESI(CS_KOD_KONTROL_LISTESI instance);
    partial void UpdateCS_KOD_KONTROL_LISTESI(CS_KOD_KONTROL_LISTESI instance);
    partial void DeleteCS_KOD_KONTROL_LISTESI(CS_KOD_KONTROL_LISTESI instance);
    partial void InsertCS_KOD_KONTROL_OZELLIKLERI(CS_KOD_KONTROL_OZELLIKLERI instance);
    partial void UpdateCS_KOD_KONTROL_OZELLIKLERI(CS_KOD_KONTROL_OZELLIKLERI instance);
    partial void DeleteCS_KOD_KONTROL_OZELLIKLERI(CS_KOD_KONTROL_OZELLIKLERI instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::AvukatProLib.Properties.Settings.Default.AVP_MYSConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CS_KOD_PAKET> CS_KOD_PAKETs
		{
			get
			{
				return this.GetTable<CS_KOD_PAKET>();
			}
		}
		
		public System.Data.Linq.Table<CS_KOD_PAKET_NN_FORM> CS_KOD_PAKET_NN_FORMs
		{
			get
			{
				return this.GetTable<CS_KOD_PAKET_NN_FORM>();
			}
		}
		
		public System.Data.Linq.Table<CS_KOD_FORM_LISTESI> CS_KOD_FORM_LISTESIs
		{
			get
			{
				return this.GetTable<CS_KOD_FORM_LISTESI>();
			}
		}
		
		public System.Data.Linq.Table<CS_KOD_KONTROL_LISTESI> CS_KOD_KONTROL_LISTESIs
		{
			get
			{
				return this.GetTable<CS_KOD_KONTROL_LISTESI>();
			}
		}
		
		public System.Data.Linq.Table<CS_KOD_KONTROL_OZELLIKLERI> CS_KOD_KONTROL_OZELLIKLERIs
		{
			get
			{
				return this.GetTable<CS_KOD_KONTROL_OZELLIKLERI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_PAKET")]
	public partial class CS_KOD_PAKET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _MODUL_NO;
		
		private string _PAKET_ADI;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private short _stamp;
		
		private EntitySet<CS_KOD_PAKET_NN_FORM> _CS_KOD_PAKET_NN_FORMs;
		
		private EntitySet<CS_KOD_KONTROL_OZELLIKLERI> _CS_KOD_KONTROL_OZELLIKLERIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMODUL_NOChanging(int value);
    partial void OnMODUL_NOChanged();
    partial void OnPAKET_ADIChanging(string value);
    partial void OnPAKET_ADIChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnstampChanging(short value);
    partial void OnstampChanged();
    #endregion
		
		public CS_KOD_PAKET()
		{
			this._CS_KOD_PAKET_NN_FORMs = new EntitySet<CS_KOD_PAKET_NN_FORM>(new Action<CS_KOD_PAKET_NN_FORM>(this.attach_CS_KOD_PAKET_NN_FORMs), new Action<CS_KOD_PAKET_NN_FORM>(this.detach_CS_KOD_PAKET_NN_FORMs));
			this._CS_KOD_KONTROL_OZELLIKLERIs = new EntitySet<CS_KOD_KONTROL_OZELLIKLERI>(new Action<CS_KOD_KONTROL_OZELLIKLERI>(this.attach_CS_KOD_KONTROL_OZELLIKLERIs), new Action<CS_KOD_KONTROL_OZELLIKLERI>(this.detach_CS_KOD_KONTROL_OZELLIKLERIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODUL_NO", DbType="Int NOT NULL")]
		public int MODUL_NO
		{
			get
			{
				return this._MODUL_NO;
			}
			set
			{
				if ((this._MODUL_NO != value))
				{
					this.OnMODUL_NOChanging(value);
					this.SendPropertyChanging();
					this._MODUL_NO = value;
					this.SendPropertyChanged("MODUL_NO");
					this.OnMODUL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAKET_ADI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PAKET_ADI
		{
			get
			{
				return this._PAKET_ADI;
			}
			set
			{
				if ((this._PAKET_ADI != value))
				{
					this.OnPAKET_ADIChanging(value);
					this.SendPropertyChanging();
					this._PAKET_ADI = value;
					this.SendPropertyChanged("PAKET_ADI");
					this.OnPAKET_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stamp", DbType="SmallInt NOT NULL")]
		public short stamp
		{
			get
			{
				return this._stamp;
			}
			set
			{
				if ((this._stamp != value))
				{
					this.OnstampChanging(value);
					this.SendPropertyChanging();
					this._stamp = value;
					this.SendPropertyChanged("stamp");
					this.OnstampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_PAKET_NN_FORMs", ThisKey="ID", OtherKey="PAKET_ID")]
		public EntitySet<CS_KOD_PAKET_NN_FORM> CS_KOD_PAKET_NN_FORMs
		{
			get
			{
				return this._CS_KOD_PAKET_NN_FORMs;
			}
			set
			{
				this._CS_KOD_PAKET_NN_FORMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_CS_KOD_KONTROL_OZELLIKLERI", Storage="_CS_KOD_KONTROL_OZELLIKLERIs", ThisKey="ID", OtherKey="PAKET_ID")]
		public EntitySet<CS_KOD_KONTROL_OZELLIKLERI> CS_KOD_KONTROL_OZELLIKLERIs
		{
			get
			{
				return this._CS_KOD_KONTROL_OZELLIKLERIs;
			}
			set
			{
				this._CS_KOD_KONTROL_OZELLIKLERIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = this;
		}
		
		private void detach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = null;
		}
		
		private void attach_CS_KOD_KONTROL_OZELLIKLERIs(CS_KOD_KONTROL_OZELLIKLERI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = this;
		}
		
		private void detach_CS_KOD_KONTROL_OZELLIKLERIs(CS_KOD_KONTROL_OZELLIKLERI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_PAKET_NN_FORM")]
	public partial class CS_KOD_PAKET_NN_FORM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PAKET_ID;
		
		private int _FORM_ID;
		
		private EntityRef<CS_KOD_PAKET> _CS_KOD_PAKET;
		
		private EntityRef<CS_KOD_FORM_LISTESI> _CS_KOD_FORM_LISTESI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPAKET_IDChanging(int value);
    partial void OnPAKET_IDChanged();
    partial void OnFORM_IDChanging(int value);
    partial void OnFORM_IDChanged();
    #endregion
		
		public CS_KOD_PAKET_NN_FORM()
		{
			this._CS_KOD_PAKET = default(EntityRef<CS_KOD_PAKET>);
			this._CS_KOD_FORM_LISTESI = default(EntityRef<CS_KOD_FORM_LISTESI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAKET_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PAKET_ID
		{
			get
			{
				return this._PAKET_ID;
			}
			set
			{
				if ((this._PAKET_ID != value))
				{
					if (this._CS_KOD_PAKET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAKET_IDChanging(value);
					this.SendPropertyChanging();
					this._PAKET_ID = value;
					this.SendPropertyChanged("PAKET_ID");
					this.OnPAKET_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FORM_ID
		{
			get
			{
				return this._FORM_ID;
			}
			set
			{
				if ((this._FORM_ID != value))
				{
					if (this._CS_KOD_FORM_LISTESI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFORM_IDChanging(value);
					this.SendPropertyChanging();
					this._FORM_ID = value;
					this.SendPropertyChanged("FORM_ID");
					this.OnFORM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_PAKET", ThisKey="PAKET_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_PAKET CS_KOD_PAKET
		{
			get
			{
				return this._CS_KOD_PAKET.Entity;
			}
			set
			{
				CS_KOD_PAKET previousValue = this._CS_KOD_PAKET.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_PAKET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_PAKET.Entity = null;
						previousValue.CS_KOD_PAKET_NN_FORMs.Remove(this);
					}
					this._CS_KOD_PAKET.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_PAKET_NN_FORMs.Add(this);
						this._PAKET_ID = value.ID;
					}
					else
					{
						this._PAKET_ID = default(int);
					}
					this.SendPropertyChanged("CS_KOD_PAKET");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_FORM_LISTESI_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_FORM_LISTESI", ThisKey="FORM_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_FORM_LISTESI CS_KOD_FORM_LISTESI
		{
			get
			{
				return this._CS_KOD_FORM_LISTESI.Entity;
			}
			set
			{
				CS_KOD_FORM_LISTESI previousValue = this._CS_KOD_FORM_LISTESI.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_FORM_LISTESI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_FORM_LISTESI.Entity = null;
						previousValue.CS_KOD_PAKET_NN_FORMs.Remove(this);
					}
					this._CS_KOD_FORM_LISTESI.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_PAKET_NN_FORMs.Add(this);
						this._FORM_ID = value.ID;
					}
					else
					{
						this._FORM_ID = default(int);
					}
					this.SendPropertyChanged("CS_KOD_FORM_LISTESI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_FORM_LISTESI")]
	public partial class CS_KOD_FORM_LISTESI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FULL_ADI;
		
		private string _FORM_TEXT;
		
		private string _FORM_ACIKLAMA;
		
		private string _MENU_NESNE_ADI;
		
		private string _SUZME_KRITER;
		
		private System.Nullable<int> _FORM_GRUP_ID;
		
		private string _DB_TABLO_ADI;
		
		private string _BUTTON_GORUNUM_LIST;
		
		private System.Nullable<int> _MODUL;
		
		private System.Nullable<int> _MODUL2;
		
		private int _SUBE_ID;
		
		private bool _ADMIN_KAYIT_MI;
		
		private System.DateTime _KONTROL_NE_ZAMAN;
		
		private int _KONTROL_KIM_ID;
		
		private int _KONTROL_VERSIYON;
		
		private short _STAMP;
		
		private EntitySet<CS_KOD_PAKET_NN_FORM> _CS_KOD_PAKET_NN_FORMs;
		
		private EntitySet<CS_KOD_KONTROL_LISTESI> _CS_KOD_KONTROL_LISTESIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFULL_ADIChanging(string value);
    partial void OnFULL_ADIChanged();
    partial void OnFORM_TEXTChanging(string value);
    partial void OnFORM_TEXTChanged();
    partial void OnFORM_ACIKLAMAChanging(string value);
    partial void OnFORM_ACIKLAMAChanged();
    partial void OnMENU_NESNE_ADIChanging(string value);
    partial void OnMENU_NESNE_ADIChanged();
    partial void OnSUZME_KRITERChanging(string value);
    partial void OnSUZME_KRITERChanged();
    partial void OnFORM_GRUP_IDChanging(System.Nullable<int> value);
    partial void OnFORM_GRUP_IDChanged();
    partial void OnDB_TABLO_ADIChanging(string value);
    partial void OnDB_TABLO_ADIChanged();
    partial void OnBUTTON_GORUNUM_LISTChanging(string value);
    partial void OnBUTTON_GORUNUM_LISTChanged();
    partial void OnMODULChanging(System.Nullable<int> value);
    partial void OnMODULChanged();
    partial void OnMODUL2Changing(System.Nullable<int> value);
    partial void OnMODUL2Changed();
    partial void OnSUBE_IDChanging(int value);
    partial void OnSUBE_IDChanged();
    partial void OnADMIN_KAYIT_MIChanging(bool value);
    partial void OnADMIN_KAYIT_MIChanged();
    partial void OnKONTROL_NE_ZAMANChanging(System.DateTime value);
    partial void OnKONTROL_NE_ZAMANChanged();
    partial void OnKONTROL_KIM_IDChanging(int value);
    partial void OnKONTROL_KIM_IDChanged();
    partial void OnKONTROL_VERSIYONChanging(int value);
    partial void OnKONTROL_VERSIYONChanged();
    partial void OnSTAMPChanging(short value);
    partial void OnSTAMPChanged();
    #endregion
		
		public CS_KOD_FORM_LISTESI()
		{
			this._CS_KOD_PAKET_NN_FORMs = new EntitySet<CS_KOD_PAKET_NN_FORM>(new Action<CS_KOD_PAKET_NN_FORM>(this.attach_CS_KOD_PAKET_NN_FORMs), new Action<CS_KOD_PAKET_NN_FORM>(this.detach_CS_KOD_PAKET_NN_FORMs));
			this._CS_KOD_KONTROL_LISTESIs = new EntitySet<CS_KOD_KONTROL_LISTESI>(new Action<CS_KOD_KONTROL_LISTESI>(this.attach_CS_KOD_KONTROL_LISTESIs), new Action<CS_KOD_KONTROL_LISTESI>(this.detach_CS_KOD_KONTROL_LISTESIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULL_ADI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FULL_ADI
		{
			get
			{
				return this._FULL_ADI;
			}
			set
			{
				if ((this._FULL_ADI != value))
				{
					this.OnFULL_ADIChanging(value);
					this.SendPropertyChanging();
					this._FULL_ADI = value;
					this.SendPropertyChanged("FULL_ADI");
					this.OnFULL_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_TEXT", DbType="NVarChar(MAX)")]
		public string FORM_TEXT
		{
			get
			{
				return this._FORM_TEXT;
			}
			set
			{
				if ((this._FORM_TEXT != value))
				{
					this.OnFORM_TEXTChanging(value);
					this.SendPropertyChanging();
					this._FORM_TEXT = value;
					this.SendPropertyChanged("FORM_TEXT");
					this.OnFORM_TEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_ACIKLAMA", DbType="NVarChar(MAX)")]
		public string FORM_ACIKLAMA
		{
			get
			{
				return this._FORM_ACIKLAMA;
			}
			set
			{
				if ((this._FORM_ACIKLAMA != value))
				{
					this.OnFORM_ACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._FORM_ACIKLAMA = value;
					this.SendPropertyChanged("FORM_ACIKLAMA");
					this.OnFORM_ACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_NESNE_ADI", DbType="NVarChar(64)")]
		public string MENU_NESNE_ADI
		{
			get
			{
				return this._MENU_NESNE_ADI;
			}
			set
			{
				if ((this._MENU_NESNE_ADI != value))
				{
					this.OnMENU_NESNE_ADIChanging(value);
					this.SendPropertyChanging();
					this._MENU_NESNE_ADI = value;
					this.SendPropertyChanged("MENU_NESNE_ADI");
					this.OnMENU_NESNE_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUZME_KRITER", DbType="NVarChar(32)")]
		public string SUZME_KRITER
		{
			get
			{
				return this._SUZME_KRITER;
			}
			set
			{
				if ((this._SUZME_KRITER != value))
				{
					this.OnSUZME_KRITERChanging(value);
					this.SendPropertyChanging();
					this._SUZME_KRITER = value;
					this.SendPropertyChanged("SUZME_KRITER");
					this.OnSUZME_KRITERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_GRUP_ID", DbType="Int")]
		public System.Nullable<int> FORM_GRUP_ID
		{
			get
			{
				return this._FORM_GRUP_ID;
			}
			set
			{
				if ((this._FORM_GRUP_ID != value))
				{
					this.OnFORM_GRUP_IDChanging(value);
					this.SendPropertyChanging();
					this._FORM_GRUP_ID = value;
					this.SendPropertyChanged("FORM_GRUP_ID");
					this.OnFORM_GRUP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_TABLO_ADI", DbType="NVarChar(128)")]
		public string DB_TABLO_ADI
		{
			get
			{
				return this._DB_TABLO_ADI;
			}
			set
			{
				if ((this._DB_TABLO_ADI != value))
				{
					this.OnDB_TABLO_ADIChanging(value);
					this.SendPropertyChanging();
					this._DB_TABLO_ADI = value;
					this.SendPropertyChanged("DB_TABLO_ADI");
					this.OnDB_TABLO_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUTTON_GORUNUM_LIST", DbType="NVarChar(30)")]
		public string BUTTON_GORUNUM_LIST
		{
			get
			{
				return this._BUTTON_GORUNUM_LIST;
			}
			set
			{
				if ((this._BUTTON_GORUNUM_LIST != value))
				{
					this.OnBUTTON_GORUNUM_LISTChanging(value);
					this.SendPropertyChanging();
					this._BUTTON_GORUNUM_LIST = value;
					this.SendPropertyChanged("BUTTON_GORUNUM_LIST");
					this.OnBUTTON_GORUNUM_LISTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODUL", DbType="Int")]
		public System.Nullable<int> MODUL
		{
			get
			{
				return this._MODUL;
			}
			set
			{
				if ((this._MODUL != value))
				{
					this.OnMODULChanging(value);
					this.SendPropertyChanging();
					this._MODUL = value;
					this.SendPropertyChanged("MODUL");
					this.OnMODULChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODUL2", DbType="Int")]
		public System.Nullable<int> MODUL2
		{
			get
			{
				return this._MODUL2;
			}
			set
			{
				if ((this._MODUL2 != value))
				{
					this.OnMODUL2Changing(value);
					this.SendPropertyChanging();
					this._MODUL2 = value;
					this.SendPropertyChanged("MODUL2");
					this.OnMODUL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE_ID", DbType="Int NOT NULL")]
		public int SUBE_ID
		{
			get
			{
				return this._SUBE_ID;
			}
			set
			{
				if ((this._SUBE_ID != value))
				{
					this.OnSUBE_IDChanging(value);
					this.SendPropertyChanging();
					this._SUBE_ID = value;
					this.SendPropertyChanged("SUBE_ID");
					this.OnSUBE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMIN_KAYIT_MI", DbType="Bit NOT NULL")]
		public bool ADMIN_KAYIT_MI
		{
			get
			{
				return this._ADMIN_KAYIT_MI;
			}
			set
			{
				if ((this._ADMIN_KAYIT_MI != value))
				{
					this.OnADMIN_KAYIT_MIChanging(value);
					this.SendPropertyChanging();
					this._ADMIN_KAYIT_MI = value;
					this.SendPropertyChanged("ADMIN_KAYIT_MI");
					this.OnADMIN_KAYIT_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_NE_ZAMAN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime KONTROL_NE_ZAMAN
		{
			get
			{
				return this._KONTROL_NE_ZAMAN;
			}
			set
			{
				if ((this._KONTROL_NE_ZAMAN != value))
				{
					this.OnKONTROL_NE_ZAMANChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_NE_ZAMAN = value;
					this.SendPropertyChanged("KONTROL_NE_ZAMAN");
					this.OnKONTROL_NE_ZAMANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_KIM_ID", DbType="Int NOT NULL")]
		public int KONTROL_KIM_ID
		{
			get
			{
				return this._KONTROL_KIM_ID;
			}
			set
			{
				if ((this._KONTROL_KIM_ID != value))
				{
					this.OnKONTROL_KIM_IDChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_KIM_ID = value;
					this.SendPropertyChanged("KONTROL_KIM_ID");
					this.OnKONTROL_KIM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_VERSIYON", DbType="Int NOT NULL")]
		public int KONTROL_VERSIYON
		{
			get
			{
				return this._KONTROL_VERSIYON;
			}
			set
			{
				if ((this._KONTROL_VERSIYON != value))
				{
					this.OnKONTROL_VERSIYONChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_VERSIYON = value;
					this.SendPropertyChanged("KONTROL_VERSIYON");
					this.OnKONTROL_VERSIYONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAMP", DbType="SmallInt NOT NULL")]
		public short STAMP
		{
			get
			{
				return this._STAMP;
			}
			set
			{
				if ((this._STAMP != value))
				{
					this.OnSTAMPChanging(value);
					this.SendPropertyChanging();
					this._STAMP = value;
					this.SendPropertyChanged("STAMP");
					this.OnSTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_FORM_LISTESI_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_PAKET_NN_FORMs", ThisKey="ID", OtherKey="FORM_ID")]
		public EntitySet<CS_KOD_PAKET_NN_FORM> CS_KOD_PAKET_NN_FORMs
		{
			get
			{
				return this._CS_KOD_PAKET_NN_FORMs;
			}
			set
			{
				this._CS_KOD_PAKET_NN_FORMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_FORM_LISTESI_CS_KOD_KONTROL_LISTESI", Storage="_CS_KOD_KONTROL_LISTESIs", ThisKey="ID", OtherKey="FORM_ID")]
		public EntitySet<CS_KOD_KONTROL_LISTESI> CS_KOD_KONTROL_LISTESIs
		{
			get
			{
				return this._CS_KOD_KONTROL_LISTESIs;
			}
			set
			{
				this._CS_KOD_KONTROL_LISTESIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_FORM_LISTESI = this;
		}
		
		private void detach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_FORM_LISTESI = null;
		}
		
		private void attach_CS_KOD_KONTROL_LISTESIs(CS_KOD_KONTROL_LISTESI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_FORM_LISTESI = this;
		}
		
		private void detach_CS_KOD_KONTROL_LISTESIs(CS_KOD_KONTROL_LISTESI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_FORM_LISTESI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_KONTROL_LISTESI")]
	public partial class CS_KOD_KONTROL_LISTESI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _FORM_ID;
		
		private System.Nullable<int> _PARENT_ID;
		
		private string _KONTROL_ADI;
		
		private string _KONTROL_TEXT;
		
		private string _KONTROL_ACIKLAMA;
		
		private string _RELATIVE_PATH;
		
		private string _TIP_ADI;
		
		private System.Nullable<int> _UNIQUE_ID;
		
		private string _SUZME_KRITER;
		
		private System.Nullable<int> _SUBE_ID;
		
		private bool _ADMIN_KAYIT_MI;
		
		private System.DateTime _KONTROL_NE_ZAMAN;
		
		private int _KONTROL_KIM_ID;
		
		private int _KONTROL_VERSIYON;
		
		private short _STAMP;
		
		private EntitySet<CS_KOD_KONTROL_LISTESI> _CS_KOD_KONTROL_LISTESIs;
		
		private EntitySet<CS_KOD_KONTROL_OZELLIKLERI> _CS_KOD_KONTROL_OZELLIKLERIs;
		
		private EntityRef<CS_KOD_FORM_LISTESI> _CS_KOD_FORM_LISTESI;
		
		private EntityRef<CS_KOD_KONTROL_LISTESI> _CS_KOD_KONTROL_LISTESI1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFORM_IDChanging(int value);
    partial void OnFORM_IDChanged();
    partial void OnPARENT_IDChanging(System.Nullable<int> value);
    partial void OnPARENT_IDChanged();
    partial void OnKONTROL_ADIChanging(string value);
    partial void OnKONTROL_ADIChanged();
    partial void OnKONTROL_TEXTChanging(string value);
    partial void OnKONTROL_TEXTChanged();
    partial void OnKONTROL_ACIKLAMAChanging(string value);
    partial void OnKONTROL_ACIKLAMAChanged();
    partial void OnRELATIVE_PATHChanging(string value);
    partial void OnRELATIVE_PATHChanged();
    partial void OnTIP_ADIChanging(string value);
    partial void OnTIP_ADIChanged();
    partial void OnUNIQUE_IDChanging(System.Nullable<int> value);
    partial void OnUNIQUE_IDChanged();
    partial void OnSUZME_KRITERChanging(string value);
    partial void OnSUZME_KRITERChanged();
    partial void OnSUBE_IDChanging(System.Nullable<int> value);
    partial void OnSUBE_IDChanged();
    partial void OnADMIN_KAYIT_MIChanging(bool value);
    partial void OnADMIN_KAYIT_MIChanged();
    partial void OnKONTROL_NE_ZAMANChanging(System.DateTime value);
    partial void OnKONTROL_NE_ZAMANChanged();
    partial void OnKONTROL_KIM_IDChanging(int value);
    partial void OnKONTROL_KIM_IDChanged();
    partial void OnKONTROL_VERSIYONChanging(int value);
    partial void OnKONTROL_VERSIYONChanged();
    partial void OnSTAMPChanging(short value);
    partial void OnSTAMPChanged();
    #endregion
		
		public CS_KOD_KONTROL_LISTESI()
		{
			this._CS_KOD_KONTROL_LISTESIs = new EntitySet<CS_KOD_KONTROL_LISTESI>(new Action<CS_KOD_KONTROL_LISTESI>(this.attach_CS_KOD_KONTROL_LISTESIs), new Action<CS_KOD_KONTROL_LISTESI>(this.detach_CS_KOD_KONTROL_LISTESIs));
			this._CS_KOD_KONTROL_OZELLIKLERIs = new EntitySet<CS_KOD_KONTROL_OZELLIKLERI>(new Action<CS_KOD_KONTROL_OZELLIKLERI>(this.attach_CS_KOD_KONTROL_OZELLIKLERIs), new Action<CS_KOD_KONTROL_OZELLIKLERI>(this.detach_CS_KOD_KONTROL_OZELLIKLERIs));
			this._CS_KOD_FORM_LISTESI = default(EntityRef<CS_KOD_FORM_LISTESI>);
			this._CS_KOD_KONTROL_LISTESI1 = default(EntityRef<CS_KOD_KONTROL_LISTESI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_ID", DbType="Int NOT NULL")]
		public int FORM_ID
		{
			get
			{
				return this._FORM_ID;
			}
			set
			{
				if ((this._FORM_ID != value))
				{
					if (this._CS_KOD_FORM_LISTESI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFORM_IDChanging(value);
					this.SendPropertyChanging();
					this._FORM_ID = value;
					this.SendPropertyChanged("FORM_ID");
					this.OnFORM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Int")]
		public System.Nullable<int> PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					if (this._CS_KOD_KONTROL_LISTESI1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPARENT_IDChanging(value);
					this.SendPropertyChanging();
					this._PARENT_ID = value;
					this.SendPropertyChanged("PARENT_ID");
					this.OnPARENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_ADI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string KONTROL_ADI
		{
			get
			{
				return this._KONTROL_ADI;
			}
			set
			{
				if ((this._KONTROL_ADI != value))
				{
					this.OnKONTROL_ADIChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_ADI = value;
					this.SendPropertyChanged("KONTROL_ADI");
					this.OnKONTROL_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_TEXT", DbType="NVarChar(MAX)")]
		public string KONTROL_TEXT
		{
			get
			{
				return this._KONTROL_TEXT;
			}
			set
			{
				if ((this._KONTROL_TEXT != value))
				{
					this.OnKONTROL_TEXTChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_TEXT = value;
					this.SendPropertyChanged("KONTROL_TEXT");
					this.OnKONTROL_TEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_ACIKLAMA", DbType="NVarChar(MAX)")]
		public string KONTROL_ACIKLAMA
		{
			get
			{
				return this._KONTROL_ACIKLAMA;
			}
			set
			{
				if ((this._KONTROL_ACIKLAMA != value))
				{
					this.OnKONTROL_ACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_ACIKLAMA = value;
					this.SendPropertyChanged("KONTROL_ACIKLAMA");
					this.OnKONTROL_ACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELATIVE_PATH", DbType="NVarChar(MAX)")]
		public string RELATIVE_PATH
		{
			get
			{
				return this._RELATIVE_PATH;
			}
			set
			{
				if ((this._RELATIVE_PATH != value))
				{
					this.OnRELATIVE_PATHChanging(value);
					this.SendPropertyChanging();
					this._RELATIVE_PATH = value;
					this.SendPropertyChanged("RELATIVE_PATH");
					this.OnRELATIVE_PATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIP_ADI", DbType="NVarChar(MAX)")]
		public string TIP_ADI
		{
			get
			{
				return this._TIP_ADI;
			}
			set
			{
				if ((this._TIP_ADI != value))
				{
					this.OnTIP_ADIChanging(value);
					this.SendPropertyChanging();
					this._TIP_ADI = value;
					this.SendPropertyChanged("TIP_ADI");
					this.OnTIP_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIQUE_ID", DbType="Int")]
		public System.Nullable<int> UNIQUE_ID
		{
			get
			{
				return this._UNIQUE_ID;
			}
			set
			{
				if ((this._UNIQUE_ID != value))
				{
					this.OnUNIQUE_IDChanging(value);
					this.SendPropertyChanging();
					this._UNIQUE_ID = value;
					this.SendPropertyChanged("UNIQUE_ID");
					this.OnUNIQUE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUZME_KRITER", DbType="NVarChar(32)")]
		public string SUZME_KRITER
		{
			get
			{
				return this._SUZME_KRITER;
			}
			set
			{
				if ((this._SUZME_KRITER != value))
				{
					this.OnSUZME_KRITERChanging(value);
					this.SendPropertyChanging();
					this._SUZME_KRITER = value;
					this.SendPropertyChanged("SUZME_KRITER");
					this.OnSUZME_KRITERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE_ID", DbType="Int")]
		public System.Nullable<int> SUBE_ID
		{
			get
			{
				return this._SUBE_ID;
			}
			set
			{
				if ((this._SUBE_ID != value))
				{
					this.OnSUBE_IDChanging(value);
					this.SendPropertyChanging();
					this._SUBE_ID = value;
					this.SendPropertyChanged("SUBE_ID");
					this.OnSUBE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMIN_KAYIT_MI", DbType="Bit NOT NULL")]
		public bool ADMIN_KAYIT_MI
		{
			get
			{
				return this._ADMIN_KAYIT_MI;
			}
			set
			{
				if ((this._ADMIN_KAYIT_MI != value))
				{
					this.OnADMIN_KAYIT_MIChanging(value);
					this.SendPropertyChanging();
					this._ADMIN_KAYIT_MI = value;
					this.SendPropertyChanged("ADMIN_KAYIT_MI");
					this.OnADMIN_KAYIT_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_NE_ZAMAN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime KONTROL_NE_ZAMAN
		{
			get
			{
				return this._KONTROL_NE_ZAMAN;
			}
			set
			{
				if ((this._KONTROL_NE_ZAMAN != value))
				{
					this.OnKONTROL_NE_ZAMANChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_NE_ZAMAN = value;
					this.SendPropertyChanged("KONTROL_NE_ZAMAN");
					this.OnKONTROL_NE_ZAMANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_KIM_ID", DbType="Int NOT NULL")]
		public int KONTROL_KIM_ID
		{
			get
			{
				return this._KONTROL_KIM_ID;
			}
			set
			{
				if ((this._KONTROL_KIM_ID != value))
				{
					this.OnKONTROL_KIM_IDChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_KIM_ID = value;
					this.SendPropertyChanged("KONTROL_KIM_ID");
					this.OnKONTROL_KIM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_VERSIYON", DbType="Int NOT NULL")]
		public int KONTROL_VERSIYON
		{
			get
			{
				return this._KONTROL_VERSIYON;
			}
			set
			{
				if ((this._KONTROL_VERSIYON != value))
				{
					this.OnKONTROL_VERSIYONChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_VERSIYON = value;
					this.SendPropertyChanged("KONTROL_VERSIYON");
					this.OnKONTROL_VERSIYONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAMP", DbType="SmallInt NOT NULL")]
		public short STAMP
		{
			get
			{
				return this._STAMP;
			}
			set
			{
				if ((this._STAMP != value))
				{
					this.OnSTAMPChanging(value);
					this.SendPropertyChanging();
					this._STAMP = value;
					this.SendPropertyChanged("STAMP");
					this.OnSTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_KONTROL_LISTESI_CS_KOD_KONTROL_LISTESI", Storage="_CS_KOD_KONTROL_LISTESIs", ThisKey="ID", OtherKey="PARENT_ID")]
		public EntitySet<CS_KOD_KONTROL_LISTESI> CS_KOD_KONTROL_LISTESIs
		{
			get
			{
				return this._CS_KOD_KONTROL_LISTESIs;
			}
			set
			{
				this._CS_KOD_KONTROL_LISTESIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_KONTROL_LISTESI_CS_KOD_KONTROL_OZELLIKLERI", Storage="_CS_KOD_KONTROL_OZELLIKLERIs", ThisKey="ID", OtherKey="KONTROL_ID")]
		public EntitySet<CS_KOD_KONTROL_OZELLIKLERI> CS_KOD_KONTROL_OZELLIKLERIs
		{
			get
			{
				return this._CS_KOD_KONTROL_OZELLIKLERIs;
			}
			set
			{
				this._CS_KOD_KONTROL_OZELLIKLERIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_FORM_LISTESI_CS_KOD_KONTROL_LISTESI", Storage="_CS_KOD_FORM_LISTESI", ThisKey="FORM_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_FORM_LISTESI CS_KOD_FORM_LISTESI
		{
			get
			{
				return this._CS_KOD_FORM_LISTESI.Entity;
			}
			set
			{
				CS_KOD_FORM_LISTESI previousValue = this._CS_KOD_FORM_LISTESI.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_FORM_LISTESI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_FORM_LISTESI.Entity = null;
						previousValue.CS_KOD_KONTROL_LISTESIs.Remove(this);
					}
					this._CS_KOD_FORM_LISTESI.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_KONTROL_LISTESIs.Add(this);
						this._FORM_ID = value.ID;
					}
					else
					{
						this._FORM_ID = default(int);
					}
					this.SendPropertyChanged("CS_KOD_FORM_LISTESI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_KONTROL_LISTESI_CS_KOD_KONTROL_LISTESI", Storage="_CS_KOD_KONTROL_LISTESI1", ThisKey="PARENT_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_KONTROL_LISTESI CS_KOD_KONTROL_LISTESI1
		{
			get
			{
				return this._CS_KOD_KONTROL_LISTESI1.Entity;
			}
			set
			{
				CS_KOD_KONTROL_LISTESI previousValue = this._CS_KOD_KONTROL_LISTESI1.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_KONTROL_LISTESI1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_KONTROL_LISTESI1.Entity = null;
						previousValue.CS_KOD_KONTROL_LISTESIs.Remove(this);
					}
					this._CS_KOD_KONTROL_LISTESI1.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_KONTROL_LISTESIs.Add(this);
						this._PARENT_ID = value.ID;
					}
					else
					{
						this._PARENT_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("CS_KOD_KONTROL_LISTESI1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CS_KOD_KONTROL_LISTESIs(CS_KOD_KONTROL_LISTESI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_KONTROL_LISTESI1 = this;
		}
		
		private void detach_CS_KOD_KONTROL_LISTESIs(CS_KOD_KONTROL_LISTESI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_KONTROL_LISTESI1 = null;
		}
		
		private void attach_CS_KOD_KONTROL_OZELLIKLERIs(CS_KOD_KONTROL_OZELLIKLERI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_KONTROL_LISTESI = this;
		}
		
		private void detach_CS_KOD_KONTROL_OZELLIKLERIs(CS_KOD_KONTROL_OZELLIKLERI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_KONTROL_LISTESI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_KONTROL_OZELLIKLERI")]
	public partial class CS_KOD_KONTROL_OZELLIKLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _KONTROL_ID;
		
		private int _PAKET_ID;
		
		private System.Nullable<bool> _GORUNUR_MU;
		
		private System.Nullable<bool> _AKTIF_MI;
		
		private System.Nullable<bool> _SEPETTE_GOSTERILSIN_MI;
		
		private System.Nullable<bool> _YETKILENDIRMEDE_KULLANILSIN_MI;
		
		private System.Nullable<bool> _PARENT_GORUNUR_MU;
		
		private EntityRef<CS_KOD_KONTROL_LISTESI> _CS_KOD_KONTROL_LISTESI;
		
		private EntityRef<CS_KOD_PAKET> _CS_KOD_PAKET;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKONTROL_IDChanging(int value);
    partial void OnKONTROL_IDChanged();
    partial void OnPAKET_IDChanging(int value);
    partial void OnPAKET_IDChanged();
    partial void OnGORUNUR_MUChanging(System.Nullable<bool> value);
    partial void OnGORUNUR_MUChanged();
    partial void OnAKTIF_MIChanging(System.Nullable<bool> value);
    partial void OnAKTIF_MIChanged();
    partial void OnSEPETTE_GOSTERILSIN_MIChanging(System.Nullable<bool> value);
    partial void OnSEPETTE_GOSTERILSIN_MIChanged();
    partial void OnYETKILENDIRMEDE_KULLANILSIN_MIChanging(System.Nullable<bool> value);
    partial void OnYETKILENDIRMEDE_KULLANILSIN_MIChanged();
    partial void OnPARENT_GORUNUR_MUChanging(System.Nullable<bool> value);
    partial void OnPARENT_GORUNUR_MUChanged();
    #endregion
		
		public CS_KOD_KONTROL_OZELLIKLERI()
		{
			this._CS_KOD_KONTROL_LISTESI = default(EntityRef<CS_KOD_KONTROL_LISTESI>);
			this._CS_KOD_PAKET = default(EntityRef<CS_KOD_PAKET>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_ID", DbType="Int NOT NULL")]
		public int KONTROL_ID
		{
			get
			{
				return this._KONTROL_ID;
			}
			set
			{
				if ((this._KONTROL_ID != value))
				{
					if (this._CS_KOD_KONTROL_LISTESI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKONTROL_IDChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_ID = value;
					this.SendPropertyChanged("KONTROL_ID");
					this.OnKONTROL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAKET_ID", DbType="Int NOT NULL")]
		public int PAKET_ID
		{
			get
			{
				return this._PAKET_ID;
			}
			set
			{
				if ((this._PAKET_ID != value))
				{
					if (this._CS_KOD_PAKET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAKET_IDChanging(value);
					this.SendPropertyChanging();
					this._PAKET_ID = value;
					this.SendPropertyChanged("PAKET_ID");
					this.OnPAKET_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GORUNUR_MU", DbType="Bit")]
		public System.Nullable<bool> GORUNUR_MU
		{
			get
			{
				return this._GORUNUR_MU;
			}
			set
			{
				if ((this._GORUNUR_MU != value))
				{
					this.OnGORUNUR_MUChanging(value);
					this.SendPropertyChanging();
					this._GORUNUR_MU = value;
					this.SendPropertyChanged("GORUNUR_MU");
					this.OnGORUNUR_MUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKTIF_MI", DbType="Bit")]
		public System.Nullable<bool> AKTIF_MI
		{
			get
			{
				return this._AKTIF_MI;
			}
			set
			{
				if ((this._AKTIF_MI != value))
				{
					this.OnAKTIF_MIChanging(value);
					this.SendPropertyChanging();
					this._AKTIF_MI = value;
					this.SendPropertyChanged("AKTIF_MI");
					this.OnAKTIF_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEPETTE_GOSTERILSIN_MI", DbType="Bit")]
		public System.Nullable<bool> SEPETTE_GOSTERILSIN_MI
		{
			get
			{
				return this._SEPETTE_GOSTERILSIN_MI;
			}
			set
			{
				if ((this._SEPETTE_GOSTERILSIN_MI != value))
				{
					this.OnSEPETTE_GOSTERILSIN_MIChanging(value);
					this.SendPropertyChanging();
					this._SEPETTE_GOSTERILSIN_MI = value;
					this.SendPropertyChanged("SEPETTE_GOSTERILSIN_MI");
					this.OnSEPETTE_GOSTERILSIN_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILENDIRMEDE_KULLANILSIN_MI", DbType="Bit")]
		public System.Nullable<bool> YETKILENDIRMEDE_KULLANILSIN_MI
		{
			get
			{
				return this._YETKILENDIRMEDE_KULLANILSIN_MI;
			}
			set
			{
				if ((this._YETKILENDIRMEDE_KULLANILSIN_MI != value))
				{
					this.OnYETKILENDIRMEDE_KULLANILSIN_MIChanging(value);
					this.SendPropertyChanging();
					this._YETKILENDIRMEDE_KULLANILSIN_MI = value;
					this.SendPropertyChanged("YETKILENDIRMEDE_KULLANILSIN_MI");
					this.OnYETKILENDIRMEDE_KULLANILSIN_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_GORUNUR_MU", DbType="Bit")]
		public System.Nullable<bool> PARENT_GORUNUR_MU
		{
			get
			{
				return this._PARENT_GORUNUR_MU;
			}
			set
			{
				if ((this._PARENT_GORUNUR_MU != value))
				{
					this.OnPARENT_GORUNUR_MUChanging(value);
					this.SendPropertyChanging();
					this._PARENT_GORUNUR_MU = value;
					this.SendPropertyChanged("PARENT_GORUNUR_MU");
					this.OnPARENT_GORUNUR_MUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_KONTROL_LISTESI_CS_KOD_KONTROL_OZELLIKLERI", Storage="_CS_KOD_KONTROL_LISTESI", ThisKey="KONTROL_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_KONTROL_LISTESI CS_KOD_KONTROL_LISTESI
		{
			get
			{
				return this._CS_KOD_KONTROL_LISTESI.Entity;
			}
			set
			{
				CS_KOD_KONTROL_LISTESI previousValue = this._CS_KOD_KONTROL_LISTESI.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_KONTROL_LISTESI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_KONTROL_LISTESI.Entity = null;
						previousValue.CS_KOD_KONTROL_OZELLIKLERIs.Remove(this);
					}
					this._CS_KOD_KONTROL_LISTESI.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_KONTROL_OZELLIKLERIs.Add(this);
						this._KONTROL_ID = value.ID;
					}
					else
					{
						this._KONTROL_ID = default(int);
					}
					this.SendPropertyChanged("CS_KOD_KONTROL_LISTESI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_CS_KOD_KONTROL_OZELLIKLERI", Storage="_CS_KOD_PAKET", ThisKey="PAKET_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_PAKET CS_KOD_PAKET
		{
			get
			{
				return this._CS_KOD_PAKET.Entity;
			}
			set
			{
				CS_KOD_PAKET previousValue = this._CS_KOD_PAKET.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_PAKET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_PAKET.Entity = null;
						previousValue.CS_KOD_KONTROL_OZELLIKLERIs.Remove(this);
					}
					this._CS_KOD_PAKET.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_KONTROL_OZELLIKLERIs.Add(this);
						this._PAKET_ID = value.ID;
					}
					else
					{
						this._PAKET_ID = default(int);
					}
					this.SendPropertyChanged("CS_KOD_PAKET");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
