//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdimAdimDavaKaydi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.9.0.145/AVPNG/AVP_NG_DOVIZ_SOAP_API_NENC.asmx")]
        public string AdimAdimDavaKaydi_DovizAPI_AVP_NG_DOVIZ_SOAP_API_NENC {
            get {
                return ((string)(this["AdimAdimDavaKaydi_DovizAPI_AVP_NG_DOVIZ_SOAP_API_NENC"]));
            }
        }
                
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Update/ERRORHANDLER_SOAP_API_NENC.asmx")]
        public string avpng_ErrorHandlerSOAPAPI_ERRORHANDLER_SOAP_API_NENC {
            get {
                return ((string)(this["avpng_ErrorHandlerSOAPAPI_ERRORHANDLER_SOAP_API_NENC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pttws.ptt.gov.tr/GonderiTakipV2/services/Sorgu.SorguHttpSoap11Endpoint/")]
        public string avpng_tr_gov_ptt_pttws_SorguService {
            get {
                return ((string)(this["avpng_tr_gov_ptt_pttws_SorguService"]));
            }
        }
    }
}
