#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVPLisans
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AVP_MYS")]
	public partial class DbLisansDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTMYS_MUSTERI(TMYS_MUSTERI instance);
    partial void UpdateTMYS_MUSTERI(TMYS_MUSTERI instance);
    partial void DeleteTMYS_MUSTERI(TMYS_MUSTERI instance);
    partial void InsertTMYS_URUN_ANAHTARI(TMYS_URUN_ANAHTARI instance);
    partial void UpdateTMYS_URUN_ANAHTARI(TMYS_URUN_ANAHTARI instance);
    partial void DeleteTMYS_URUN_ANAHTARI(TMYS_URUN_ANAHTARI instance);
    partial void InsertCS_KOD_PAKET(CS_KOD_PAKET instance);
    partial void UpdateCS_KOD_PAKET(CS_KOD_PAKET instance);
    partial void DeleteCS_KOD_PAKET(CS_KOD_PAKET instance);
    partial void InsertCS_KOD_PAKET_NN_FORM(CS_KOD_PAKET_NN_FORM instance);
    partial void UpdateCS_KOD_PAKET_NN_FORM(CS_KOD_PAKET_NN_FORM instance);
    partial void DeleteCS_KOD_PAKET_NN_FORM(CS_KOD_PAKET_NN_FORM instance);
    partial void InsertCS_KOD_FORM_LISTESI(CS_KOD_FORM_LISTESI instance);
    partial void UpdateCS_KOD_FORM_LISTESI(CS_KOD_FORM_LISTESI instance);
    partial void DeleteCS_KOD_FORM_LISTESI(CS_KOD_FORM_LISTESI instance);
    #endregion
		
		public DbLisansDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AVP_MYSConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbLisansDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLisansDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLisansDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLisansDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TMYS_MUSTERI> TMYS_MUSTERIs
		{
			get
			{
				return this.GetTable<TMYS_MUSTERI>();
			}
		}
		
		public System.Data.Linq.Table<TMYS_URUN_ANAHTARI> TMYS_URUN_ANAHTARIs
		{
			get
			{
				return this.GetTable<TMYS_URUN_ANAHTARI>();
			}
		}
		
		public System.Data.Linq.Table<CS_KOD_PAKET> CS_KOD_PAKETs
		{
			get
			{
				return this.GetTable<CS_KOD_PAKET>();
			}
		}
		
		public System.Data.Linq.Table<CS_KOD_PAKET_NN_FORM> CS_KOD_PAKET_NN_FORMs
		{
			get
			{
				return this.GetTable<CS_KOD_PAKET_NN_FORM>();
			}
		}
		
		public System.Data.Linq.Table<CS_KOD_FORM_LISTESI> CS_KOD_FORM_LISTESIs
		{
			get
			{
				return this.GetTable<CS_KOD_FORM_LISTESI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMYS_MUSTERI")]
	public partial class TMYS_MUSTERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Guid _EUID;
		
		private string _MUSTERI_TIPI;
		
		private string _AD_SOYAD;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private byte _DURUM;
		
		private System.Nullable<int> _MODUL_NO;
		
		private System.Nullable<int> _ICRA_KULLANICI;
		
		private System.Nullable<int> _DAVA_KULLANICI;
		
		private System.Nullable<int> _SORUSTURMA_KULLANICI;
		
		private System.Nullable<System.DateTime> _LISANS_BITIS_TARIHI;
		
		private System.Nullable<int> _ICRA_KAYIT_SAYISI;
		
		private System.Nullable<int> _DAVA_KAYIT_SAYISI;
		
		private System.Nullable<int> _SORUSTURMA_KAYIT_SAYISI;
		
		private EntitySet<TMYS_URUN_ANAHTARI> _TMYS_URUN_ANAHTARIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEUIDChanging(System.Guid value);
    partial void OnEUIDChanged();
    partial void OnMUSTERI_TIPIChanging(string value);
    partial void OnMUSTERI_TIPIChanged();
    partial void OnAD_SOYADChanging(string value);
    partial void OnAD_SOYADChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnDURUMChanging(byte value);
    partial void OnDURUMChanged();
    partial void OnMODUL_NOChanging(System.Nullable<int> value);
    partial void OnMODUL_NOChanged();
    partial void OnICRA_KULLANICIChanging(System.Nullable<int> value);
    partial void OnICRA_KULLANICIChanged();
    partial void OnDAVA_KULLANICIChanging(System.Nullable<int> value);
    partial void OnDAVA_KULLANICIChanged();
    partial void OnSORUSTURMA_KULLANICIChanging(System.Nullable<int> value);
    partial void OnSORUSTURMA_KULLANICIChanged();
    partial void OnLISANS_BITIS_TARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnLISANS_BITIS_TARIHIChanged();
    partial void OnICRA_KAYIT_SAYISIChanging(System.Nullable<int> value);
    partial void OnICRA_KAYIT_SAYISIChanged();
    partial void OnDAVA_KAYIT_SAYISIChanging(System.Nullable<int> value);
    partial void OnDAVA_KAYIT_SAYISIChanged();
    partial void OnSORUSTURMA_KAYIT_SAYISIChanging(System.Nullable<int> value);
    partial void OnSORUSTURMA_KAYIT_SAYISIChanged();
    #endregion
		
		public TMYS_MUSTERI()
		{
			this._TMYS_URUN_ANAHTARIs = new EntitySet<TMYS_URUN_ANAHTARI>(new Action<TMYS_URUN_ANAHTARI>(this.attach_TMYS_URUN_ANAHTARIs), new Action<TMYS_URUN_ANAHTARI>(this.detach_TMYS_URUN_ANAHTARIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EUID
		{
			get
			{
				return this._EUID;
			}
			set
			{
				if ((this._EUID != value))
				{
					this.OnEUIDChanging(value);
					this.SendPropertyChanging();
					this._EUID = value;
					this.SendPropertyChanged("EUID");
					this.OnEUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUSTERI_TIPI", DbType="NVarChar(255)")]
		public string MUSTERI_TIPI
		{
			get
			{
				return this._MUSTERI_TIPI;
			}
			set
			{
				if ((this._MUSTERI_TIPI != value))
				{
					this.OnMUSTERI_TIPIChanging(value);
					this.SendPropertyChanging();
					this._MUSTERI_TIPI = value;
					this.SendPropertyChanged("MUSTERI_TIPI");
					this.OnMUSTERI_TIPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AD_SOYAD", DbType="NVarChar(255)")]
		public string AD_SOYAD
		{
			get
			{
				return this._AD_SOYAD;
			}
			set
			{
				if ((this._AD_SOYAD != value))
				{
					this.OnAD_SOYADChanging(value);
					this.SendPropertyChanging();
					this._AD_SOYAD = value;
					this.SendPropertyChanged("AD_SOYAD");
					this.OnAD_SOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="TinyInt NOT NULL")]
		public byte DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODUL_NO", DbType="Int")]
		public System.Nullable<int> MODUL_NO
		{
			get
			{
				return this._MODUL_NO;
			}
			set
			{
				if ((this._MODUL_NO != value))
				{
					this.OnMODUL_NOChanging(value);
					this.SendPropertyChanging();
					this._MODUL_NO = value;
					this.SendPropertyChanged("MODUL_NO");
					this.OnMODUL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICRA_KULLANICI", DbType="Int")]
		public System.Nullable<int> ICRA_KULLANICI
		{
			get
			{
				return this._ICRA_KULLANICI;
			}
			set
			{
				if ((this._ICRA_KULLANICI != value))
				{
					this.OnICRA_KULLANICIChanging(value);
					this.SendPropertyChanging();
					this._ICRA_KULLANICI = value;
					this.SendPropertyChanged("ICRA_KULLANICI");
					this.OnICRA_KULLANICIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAVA_KULLANICI", DbType="Int")]
		public System.Nullable<int> DAVA_KULLANICI
		{
			get
			{
				return this._DAVA_KULLANICI;
			}
			set
			{
				if ((this._DAVA_KULLANICI != value))
				{
					this.OnDAVA_KULLANICIChanging(value);
					this.SendPropertyChanging();
					this._DAVA_KULLANICI = value;
					this.SendPropertyChanged("DAVA_KULLANICI");
					this.OnDAVA_KULLANICIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORUSTURMA_KULLANICI", DbType="Int")]
		public System.Nullable<int> SORUSTURMA_KULLANICI
		{
			get
			{
				return this._SORUSTURMA_KULLANICI;
			}
			set
			{
				if ((this._SORUSTURMA_KULLANICI != value))
				{
					this.OnSORUSTURMA_KULLANICIChanging(value);
					this.SendPropertyChanging();
					this._SORUSTURMA_KULLANICI = value;
					this.SendPropertyChanged("SORUSTURMA_KULLANICI");
					this.OnSORUSTURMA_KULLANICIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LISANS_BITIS_TARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> LISANS_BITIS_TARIHI
		{
			get
			{
				return this._LISANS_BITIS_TARIHI;
			}
			set
			{
				if ((this._LISANS_BITIS_TARIHI != value))
				{
					this.OnLISANS_BITIS_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._LISANS_BITIS_TARIHI = value;
					this.SendPropertyChanged("LISANS_BITIS_TARIHI");
					this.OnLISANS_BITIS_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICRA_KAYIT_SAYISI", DbType="Int")]
		public System.Nullable<int> ICRA_KAYIT_SAYISI
		{
			get
			{
				return this._ICRA_KAYIT_SAYISI;
			}
			set
			{
				if ((this._ICRA_KAYIT_SAYISI != value))
				{
					this.OnICRA_KAYIT_SAYISIChanging(value);
					this.SendPropertyChanging();
					this._ICRA_KAYIT_SAYISI = value;
					this.SendPropertyChanged("ICRA_KAYIT_SAYISI");
					this.OnICRA_KAYIT_SAYISIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAVA_KAYIT_SAYISI", DbType="Int")]
		public System.Nullable<int> DAVA_KAYIT_SAYISI
		{
			get
			{
				return this._DAVA_KAYIT_SAYISI;
			}
			set
			{
				if ((this._DAVA_KAYIT_SAYISI != value))
				{
					this.OnDAVA_KAYIT_SAYISIChanging(value);
					this.SendPropertyChanging();
					this._DAVA_KAYIT_SAYISI = value;
					this.SendPropertyChanged("DAVA_KAYIT_SAYISI");
					this.OnDAVA_KAYIT_SAYISIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORUSTURMA_KAYIT_SAYISI", DbType="Int")]
		public System.Nullable<int> SORUSTURMA_KAYIT_SAYISI
		{
			get
			{
				return this._SORUSTURMA_KAYIT_SAYISI;
			}
			set
			{
				if ((this._SORUSTURMA_KAYIT_SAYISI != value))
				{
					this.OnSORUSTURMA_KAYIT_SAYISIChanging(value);
					this.SendPropertyChanging();
					this._SORUSTURMA_KAYIT_SAYISI = value;
					this.SendPropertyChanged("SORUSTURMA_KAYIT_SAYISI");
					this.OnSORUSTURMA_KAYIT_SAYISIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_MUSTERI_TMYS_URUN_ANAHTARI", Storage="_TMYS_URUN_ANAHTARIs", ThisKey="ID", OtherKey="MUSTERI_ID")]
		public EntitySet<TMYS_URUN_ANAHTARI> TMYS_URUN_ANAHTARIs
		{
			get
			{
				return this._TMYS_URUN_ANAHTARIs;
			}
			set
			{
				this._TMYS_URUN_ANAHTARIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TMYS_URUN_ANAHTARIs(TMYS_URUN_ANAHTARI entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_MUSTERI = this;
		}
		
		private void detach_TMYS_URUN_ANAHTARIs(TMYS_URUN_ANAHTARI entity)
		{
			this.SendPropertyChanging();
			entity.TMYS_MUSTERI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMYS_URUN_ANAHTARI")]
	public partial class TMYS_URUN_ANAHTARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _URUN_ANAHTARI;
		
		private int _MUSTERI_ID;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private byte _DURUM;
		
		private System.Guid _EUID;
		
		private System.Nullable<int> _PAKET_ID;
		
		private EntityRef<TMYS_MUSTERI> _TMYS_MUSTERI;
		
		private EntityRef<CS_KOD_PAKET> _CS_KOD_PAKET;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnURUN_ANAHTARIChanging(string value);
    partial void OnURUN_ANAHTARIChanged();
    partial void OnMUSTERI_IDChanging(int value);
    partial void OnMUSTERI_IDChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnDURUMChanging(byte value);
    partial void OnDURUMChanged();
    partial void OnEUIDChanging(System.Guid value);
    partial void OnEUIDChanged();
    partial void OnPAKET_IDChanging(System.Nullable<int> value);
    partial void OnPAKET_IDChanged();
    #endregion
		
		public TMYS_URUN_ANAHTARI()
		{
			this._TMYS_MUSTERI = default(EntityRef<TMYS_MUSTERI>);
			this._CS_KOD_PAKET = default(EntityRef<CS_KOD_PAKET>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUN_ANAHTARI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string URUN_ANAHTARI
		{
			get
			{
				return this._URUN_ANAHTARI;
			}
			set
			{
				if ((this._URUN_ANAHTARI != value))
				{
					this.OnURUN_ANAHTARIChanging(value);
					this.SendPropertyChanging();
					this._URUN_ANAHTARI = value;
					this.SendPropertyChanged("URUN_ANAHTARI");
					this.OnURUN_ANAHTARIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUSTERI_ID", DbType="Int NOT NULL")]
		public int MUSTERI_ID
		{
			get
			{
				return this._MUSTERI_ID;
			}
			set
			{
				if ((this._MUSTERI_ID != value))
				{
					if (this._TMYS_MUSTERI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMUSTERI_IDChanging(value);
					this.SendPropertyChanging();
					this._MUSTERI_ID = value;
					this.SendPropertyChanged("MUSTERI_ID");
					this.OnMUSTERI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="TinyInt NOT NULL")]
		public byte DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EUID
		{
			get
			{
				return this._EUID;
			}
			set
			{
				if ((this._EUID != value))
				{
					this.OnEUIDChanging(value);
					this.SendPropertyChanging();
					this._EUID = value;
					this.SendPropertyChanged("EUID");
					this.OnEUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAKET_ID", DbType="Int")]
		public System.Nullable<int> PAKET_ID
		{
			get
			{
				return this._PAKET_ID;
			}
			set
			{
				if ((this._PAKET_ID != value))
				{
					if (this._CS_KOD_PAKET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAKET_IDChanging(value);
					this.SendPropertyChanging();
					this._PAKET_ID = value;
					this.SendPropertyChanged("PAKET_ID");
					this.OnPAKET_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMYS_MUSTERI_TMYS_URUN_ANAHTARI", Storage="_TMYS_MUSTERI", ThisKey="MUSTERI_ID", OtherKey="ID", IsForeignKey=true)]
		public TMYS_MUSTERI TMYS_MUSTERI
		{
			get
			{
				return this._TMYS_MUSTERI.Entity;
			}
			set
			{
				TMYS_MUSTERI previousValue = this._TMYS_MUSTERI.Entity;
				if (((previousValue != value) 
							|| (this._TMYS_MUSTERI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMYS_MUSTERI.Entity = null;
						previousValue.TMYS_URUN_ANAHTARIs.Remove(this);
					}
					this._TMYS_MUSTERI.Entity = value;
					if ((value != null))
					{
						value.TMYS_URUN_ANAHTARIs.Add(this);
						this._MUSTERI_ID = value.ID;
					}
					else
					{
						this._MUSTERI_ID = default(int);
					}
					this.SendPropertyChanged("TMYS_MUSTERI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_TMYS_URUN_ANAHTARI", Storage="_CS_KOD_PAKET", ThisKey="PAKET_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_PAKET CS_KOD_PAKET
		{
			get
			{
				return this._CS_KOD_PAKET.Entity;
			}
			set
			{
				CS_KOD_PAKET previousValue = this._CS_KOD_PAKET.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_PAKET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_PAKET.Entity = null;
						previousValue.TMYS_URUN_ANAHTARIs.Remove(this);
					}
					this._CS_KOD_PAKET.Entity = value;
					if ((value != null))
					{
						value.TMYS_URUN_ANAHTARIs.Add(this);
						this._PAKET_ID = value.ID;
					}
					else
					{
						this._PAKET_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("CS_KOD_PAKET");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_PAKET")]
	public partial class CS_KOD_PAKET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _MODUL_NO;
		
		private string _PAKET_ADI;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private short _stamp;
		
		private EntitySet<TMYS_URUN_ANAHTARI> _TMYS_URUN_ANAHTARIs;
		
		private EntitySet<CS_KOD_PAKET_NN_FORM> _CS_KOD_PAKET_NN_FORMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMODUL_NOChanging(int value);
    partial void OnMODUL_NOChanged();
    partial void OnPAKET_ADIChanging(string value);
    partial void OnPAKET_ADIChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnstampChanging(short value);
    partial void OnstampChanged();
    #endregion
		
		public CS_KOD_PAKET()
		{
			this._TMYS_URUN_ANAHTARIs = new EntitySet<TMYS_URUN_ANAHTARI>(new Action<TMYS_URUN_ANAHTARI>(this.attach_TMYS_URUN_ANAHTARIs), new Action<TMYS_URUN_ANAHTARI>(this.detach_TMYS_URUN_ANAHTARIs));
			this._CS_KOD_PAKET_NN_FORMs = new EntitySet<CS_KOD_PAKET_NN_FORM>(new Action<CS_KOD_PAKET_NN_FORM>(this.attach_CS_KOD_PAKET_NN_FORMs), new Action<CS_KOD_PAKET_NN_FORM>(this.detach_CS_KOD_PAKET_NN_FORMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODUL_NO", DbType="Int NOT NULL")]
		public int MODUL_NO
		{
			get
			{
				return this._MODUL_NO;
			}
			set
			{
				if ((this._MODUL_NO != value))
				{
					this.OnMODUL_NOChanging(value);
					this.SendPropertyChanging();
					this._MODUL_NO = value;
					this.SendPropertyChanged("MODUL_NO");
					this.OnMODUL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAKET_ADI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PAKET_ADI
		{
			get
			{
				return this._PAKET_ADI;
			}
			set
			{
				if ((this._PAKET_ADI != value))
				{
					this.OnPAKET_ADIChanging(value);
					this.SendPropertyChanging();
					this._PAKET_ADI = value;
					this.SendPropertyChanged("PAKET_ADI");
					this.OnPAKET_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stamp", DbType="SmallInt NOT NULL")]
		public short stamp
		{
			get
			{
				return this._stamp;
			}
			set
			{
				if ((this._stamp != value))
				{
					this.OnstampChanging(value);
					this.SendPropertyChanging();
					this._stamp = value;
					this.SendPropertyChanged("stamp");
					this.OnstampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_TMYS_URUN_ANAHTARI", Storage="_TMYS_URUN_ANAHTARIs", ThisKey="ID", OtherKey="PAKET_ID")]
		public EntitySet<TMYS_URUN_ANAHTARI> TMYS_URUN_ANAHTARIs
		{
			get
			{
				return this._TMYS_URUN_ANAHTARIs;
			}
			set
			{
				this._TMYS_URUN_ANAHTARIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_PAKET_NN_FORMs", ThisKey="ID", OtherKey="PAKET_ID")]
		public EntitySet<CS_KOD_PAKET_NN_FORM> CS_KOD_PAKET_NN_FORMs
		{
			get
			{
				return this._CS_KOD_PAKET_NN_FORMs;
			}
			set
			{
				this._CS_KOD_PAKET_NN_FORMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TMYS_URUN_ANAHTARIs(TMYS_URUN_ANAHTARI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = this;
		}
		
		private void detach_TMYS_URUN_ANAHTARIs(TMYS_URUN_ANAHTARI entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = null;
		}
		
		private void attach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = this;
		}
		
		private void detach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_PAKET = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_PAKET_NN_FORM")]
	public partial class CS_KOD_PAKET_NN_FORM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PAKET_ID;
		
		private int _FORM_ID;
		
		private EntityRef<CS_KOD_PAKET> _CS_KOD_PAKET;
		
		private EntityRef<CS_KOD_FORM_LISTESI> _CS_KOD_FORM_LISTESI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPAKET_IDChanging(int value);
    partial void OnPAKET_IDChanged();
    partial void OnFORM_IDChanging(int value);
    partial void OnFORM_IDChanged();
    #endregion
		
		public CS_KOD_PAKET_NN_FORM()
		{
			this._CS_KOD_PAKET = default(EntityRef<CS_KOD_PAKET>);
			this._CS_KOD_FORM_LISTESI = default(EntityRef<CS_KOD_FORM_LISTESI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAKET_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PAKET_ID
		{
			get
			{
				return this._PAKET_ID;
			}
			set
			{
				if ((this._PAKET_ID != value))
				{
					if (this._CS_KOD_PAKET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAKET_IDChanging(value);
					this.SendPropertyChanging();
					this._PAKET_ID = value;
					this.SendPropertyChanged("PAKET_ID");
					this.OnPAKET_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FORM_ID
		{
			get
			{
				return this._FORM_ID;
			}
			set
			{
				if ((this._FORM_ID != value))
				{
					if (this._CS_KOD_FORM_LISTESI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFORM_IDChanging(value);
					this.SendPropertyChanging();
					this._FORM_ID = value;
					this.SendPropertyChanged("FORM_ID");
					this.OnFORM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_PAKET_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_PAKET", ThisKey="PAKET_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_PAKET CS_KOD_PAKET
		{
			get
			{
				return this._CS_KOD_PAKET.Entity;
			}
			set
			{
				CS_KOD_PAKET previousValue = this._CS_KOD_PAKET.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_PAKET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_PAKET.Entity = null;
						previousValue.CS_KOD_PAKET_NN_FORMs.Remove(this);
					}
					this._CS_KOD_PAKET.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_PAKET_NN_FORMs.Add(this);
						this._PAKET_ID = value.ID;
					}
					else
					{
						this._PAKET_ID = default(int);
					}
					this.SendPropertyChanged("CS_KOD_PAKET");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_FORM_LISTESI_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_FORM_LISTESI", ThisKey="FORM_ID", OtherKey="ID", IsForeignKey=true)]
		public CS_KOD_FORM_LISTESI CS_KOD_FORM_LISTESI
		{
			get
			{
				return this._CS_KOD_FORM_LISTESI.Entity;
			}
			set
			{
				CS_KOD_FORM_LISTESI previousValue = this._CS_KOD_FORM_LISTESI.Entity;
				if (((previousValue != value) 
							|| (this._CS_KOD_FORM_LISTESI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CS_KOD_FORM_LISTESI.Entity = null;
						previousValue.CS_KOD_PAKET_NN_FORMs.Remove(this);
					}
					this._CS_KOD_FORM_LISTESI.Entity = value;
					if ((value != null))
					{
						value.CS_KOD_PAKET_NN_FORMs.Add(this);
						this._FORM_ID = value.ID;
					}
					else
					{
						this._FORM_ID = default(int);
					}
					this.SendPropertyChanged("CS_KOD_FORM_LISTESI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KOD_FORM_LISTESI")]
	public partial class CS_KOD_FORM_LISTESI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FULL_ADI;
		
		private string _FORM_ACIKLAMA;
		
		private string _MENU_NESNE_ADI;
		
		private string _SUZME_KRITER;
		
		private System.Nullable<int> _FORM_GRUP_ID;
		
		private string _DB_TABLO_ADI;
		
		private string _BUTTON_GORUNUM_LIST;
		
		private int _MODUL;
		
		private int _MODUL2;
		
		private int _SUBE_ID;
		
		private bool _ADMIN_KAYIT_MI;
		
		private System.DateTime _KONTROL_NE_ZAMAN;
		
		private int _KONTROL_KIM_ID;
		
		private int _KONTROL_VERSIYON;
		
		private short _STAMP;
		
		private EntitySet<CS_KOD_PAKET_NN_FORM> _CS_KOD_PAKET_NN_FORMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFULL_ADIChanging(string value);
    partial void OnFULL_ADIChanged();
    partial void OnFORM_ACIKLAMAChanging(string value);
    partial void OnFORM_ACIKLAMAChanged();
    partial void OnMENU_NESNE_ADIChanging(string value);
    partial void OnMENU_NESNE_ADIChanged();
    partial void OnSUZME_KRITERChanging(string value);
    partial void OnSUZME_KRITERChanged();
    partial void OnFORM_GRUP_IDChanging(System.Nullable<int> value);
    partial void OnFORM_GRUP_IDChanged();
    partial void OnDB_TABLO_ADIChanging(string value);
    partial void OnDB_TABLO_ADIChanged();
    partial void OnBUTTON_GORUNUM_LISTChanging(string value);
    partial void OnBUTTON_GORUNUM_LISTChanged();
    partial void OnMODULChanging(int value);
    partial void OnMODULChanged();
    partial void OnMODUL2Changing(int value);
    partial void OnMODUL2Changed();
    partial void OnSUBE_IDChanging(int value);
    partial void OnSUBE_IDChanged();
    partial void OnADMIN_KAYIT_MIChanging(bool value);
    partial void OnADMIN_KAYIT_MIChanged();
    partial void OnKONTROL_NE_ZAMANChanging(System.DateTime value);
    partial void OnKONTROL_NE_ZAMANChanged();
    partial void OnKONTROL_KIM_IDChanging(int value);
    partial void OnKONTROL_KIM_IDChanged();
    partial void OnKONTROL_VERSIYONChanging(int value);
    partial void OnKONTROL_VERSIYONChanged();
    partial void OnSTAMPChanging(short value);
    partial void OnSTAMPChanged();
    #endregion
		
		public CS_KOD_FORM_LISTESI()
		{
			this._CS_KOD_PAKET_NN_FORMs = new EntitySet<CS_KOD_PAKET_NN_FORM>(new Action<CS_KOD_PAKET_NN_FORM>(this.attach_CS_KOD_PAKET_NN_FORMs), new Action<CS_KOD_PAKET_NN_FORM>(this.detach_CS_KOD_PAKET_NN_FORMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULL_ADI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FULL_ADI
		{
			get
			{
				return this._FULL_ADI;
			}
			set
			{
				if ((this._FULL_ADI != value))
				{
					this.OnFULL_ADIChanging(value);
					this.SendPropertyChanging();
					this._FULL_ADI = value;
					this.SendPropertyChanged("FULL_ADI");
					this.OnFULL_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_ACIKLAMA", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string FORM_ACIKLAMA
		{
			get
			{
				return this._FORM_ACIKLAMA;
			}
			set
			{
				if ((this._FORM_ACIKLAMA != value))
				{
					this.OnFORM_ACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._FORM_ACIKLAMA = value;
					this.SendPropertyChanged("FORM_ACIKLAMA");
					this.OnFORM_ACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_NESNE_ADI", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string MENU_NESNE_ADI
		{
			get
			{
				return this._MENU_NESNE_ADI;
			}
			set
			{
				if ((this._MENU_NESNE_ADI != value))
				{
					this.OnMENU_NESNE_ADIChanging(value);
					this.SendPropertyChanging();
					this._MENU_NESNE_ADI = value;
					this.SendPropertyChanged("MENU_NESNE_ADI");
					this.OnMENU_NESNE_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUZME_KRITER", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string SUZME_KRITER
		{
			get
			{
				return this._SUZME_KRITER;
			}
			set
			{
				if ((this._SUZME_KRITER != value))
				{
					this.OnSUZME_KRITERChanging(value);
					this.SendPropertyChanging();
					this._SUZME_KRITER = value;
					this.SendPropertyChanged("SUZME_KRITER");
					this.OnSUZME_KRITERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_GRUP_ID", DbType="Int")]
		public System.Nullable<int> FORM_GRUP_ID
		{
			get
			{
				return this._FORM_GRUP_ID;
			}
			set
			{
				if ((this._FORM_GRUP_ID != value))
				{
					this.OnFORM_GRUP_IDChanging(value);
					this.SendPropertyChanging();
					this._FORM_GRUP_ID = value;
					this.SendPropertyChanged("FORM_GRUP_ID");
					this.OnFORM_GRUP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_TABLO_ADI", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string DB_TABLO_ADI
		{
			get
			{
				return this._DB_TABLO_ADI;
			}
			set
			{
				if ((this._DB_TABLO_ADI != value))
				{
					this.OnDB_TABLO_ADIChanging(value);
					this.SendPropertyChanging();
					this._DB_TABLO_ADI = value;
					this.SendPropertyChanged("DB_TABLO_ADI");
					this.OnDB_TABLO_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUTTON_GORUNUM_LIST", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string BUTTON_GORUNUM_LIST
		{
			get
			{
				return this._BUTTON_GORUNUM_LIST;
			}
			set
			{
				if ((this._BUTTON_GORUNUM_LIST != value))
				{
					this.OnBUTTON_GORUNUM_LISTChanging(value);
					this.SendPropertyChanging();
					this._BUTTON_GORUNUM_LIST = value;
					this.SendPropertyChanged("BUTTON_GORUNUM_LIST");
					this.OnBUTTON_GORUNUM_LISTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODUL", DbType="Int NOT NULL")]
		public int MODUL
		{
			get
			{
				return this._MODUL;
			}
			set
			{
				if ((this._MODUL != value))
				{
					this.OnMODULChanging(value);
					this.SendPropertyChanging();
					this._MODUL = value;
					this.SendPropertyChanged("MODUL");
					this.OnMODULChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODUL2", DbType="Int NOT NULL")]
		public int MODUL2
		{
			get
			{
				return this._MODUL2;
			}
			set
			{
				if ((this._MODUL2 != value))
				{
					this.OnMODUL2Changing(value);
					this.SendPropertyChanging();
					this._MODUL2 = value;
					this.SendPropertyChanged("MODUL2");
					this.OnMODUL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE_ID", DbType="Int NOT NULL")]
		public int SUBE_ID
		{
			get
			{
				return this._SUBE_ID;
			}
			set
			{
				if ((this._SUBE_ID != value))
				{
					this.OnSUBE_IDChanging(value);
					this.SendPropertyChanging();
					this._SUBE_ID = value;
					this.SendPropertyChanged("SUBE_ID");
					this.OnSUBE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMIN_KAYIT_MI", DbType="Bit NOT NULL")]
		public bool ADMIN_KAYIT_MI
		{
			get
			{
				return this._ADMIN_KAYIT_MI;
			}
			set
			{
				if ((this._ADMIN_KAYIT_MI != value))
				{
					this.OnADMIN_KAYIT_MIChanging(value);
					this.SendPropertyChanging();
					this._ADMIN_KAYIT_MI = value;
					this.SendPropertyChanged("ADMIN_KAYIT_MI");
					this.OnADMIN_KAYIT_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_NE_ZAMAN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime KONTROL_NE_ZAMAN
		{
			get
			{
				return this._KONTROL_NE_ZAMAN;
			}
			set
			{
				if ((this._KONTROL_NE_ZAMAN != value))
				{
					this.OnKONTROL_NE_ZAMANChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_NE_ZAMAN = value;
					this.SendPropertyChanged("KONTROL_NE_ZAMAN");
					this.OnKONTROL_NE_ZAMANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_KIM_ID", DbType="Int NOT NULL")]
		public int KONTROL_KIM_ID
		{
			get
			{
				return this._KONTROL_KIM_ID;
			}
			set
			{
				if ((this._KONTROL_KIM_ID != value))
				{
					this.OnKONTROL_KIM_IDChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_KIM_ID = value;
					this.SendPropertyChanged("KONTROL_KIM_ID");
					this.OnKONTROL_KIM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_VERSIYON", DbType="Int NOT NULL")]
		public int KONTROL_VERSIYON
		{
			get
			{
				return this._KONTROL_VERSIYON;
			}
			set
			{
				if ((this._KONTROL_VERSIYON != value))
				{
					this.OnKONTROL_VERSIYONChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_VERSIYON = value;
					this.SendPropertyChanged("KONTROL_VERSIYON");
					this.OnKONTROL_VERSIYONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAMP", DbType="SmallInt NOT NULL")]
		public short STAMP
		{
			get
			{
				return this._STAMP;
			}
			set
			{
				if ((this._STAMP != value))
				{
					this.OnSTAMPChanging(value);
					this.SendPropertyChanging();
					this._STAMP = value;
					this.SendPropertyChanged("STAMP");
					this.OnSTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CS_KOD_FORM_LISTESI_CS_KOD_PAKET_NN_FORM", Storage="_CS_KOD_PAKET_NN_FORMs", ThisKey="ID", OtherKey="FORM_ID")]
		public EntitySet<CS_KOD_PAKET_NN_FORM> CS_KOD_PAKET_NN_FORMs
		{
			get
			{
				return this._CS_KOD_PAKET_NN_FORMs;
			}
			set
			{
				this._CS_KOD_PAKET_NN_FORMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_FORM_LISTESI = this;
		}
		
		private void detach_CS_KOD_PAKET_NN_FORMs(CS_KOD_PAKET_NN_FORM entity)
		{
			this.SendPropertyChanging();
			entity.CS_KOD_FORM_LISTESI = null;
		}
	}
}
#pragma warning restore 1591
