#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avukatpro.Reminder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BOS")]
	public partial class AVPReminderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAV001_TDI_BIL_HATIRLAT(AV001_TDI_BIL_HATIRLAT instance);
    partial void UpdateAV001_TDI_BIL_HATIRLAT(AV001_TDI_BIL_HATIRLAT instance);
    partial void DeleteAV001_TDI_BIL_HATIRLAT(AV001_TDI_BIL_HATIRLAT instance);
    #endregion
		
		public AVPReminderDataContext() : 
				base(global::Avukatpro.Reminder.Properties.Settings.Default.BOSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AVPReminderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AVPReminderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AVPReminderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AVPReminderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AV001_TDI_BIL_HATIRLAT> AV001_TDI_BIL_HATIRLATs
		{
			get
			{
				return this.GetTable<AV001_TDI_BIL_HATIRLAT>();
			}
		}
		
		public System.Data.Linq.Table<per_REMINDER> per_REMINDERs
		{
			get
			{
				return this.GetTable<per_REMINDER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AV001_TDI_BIL_HATIRLAT")]
	public partial class AV001_TDI_BIL_HATIRLAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _KULLANICI_ID;
		
		private string _REFERANS_NO;
		
		private System.Nullable<int> _IS_ID;
		
		private string _FIRMA_TABLO_KODU;
		
		private bool _HATIRLATSIN_MI;
		
		private string _GUNLUK_UYARI_SAAT;
		
		private int _SONRAKI_UYARI_SAAT;
		
		private int _SONRAKI_UYARI_DAKIKA;
		
		private int _PERIYOD_ID;
		
		private string _PERIYOD;
		
		private int _BASLANGIC_ID;
		
		private string _BASLANGIC;
		
		private bool _PERIYODUN_SON_PATLAMASI_OLDU_MU;
		
		private bool _BIR_DEFA_PATLAMASI_OLDU_MU;
		
		private System.DateTime _BASLAMA_TARIHI;
		
		private string _BASLAMA_SAATI;
		
		private System.DateTime _BITIS_TARIHI;
		
		private string _BITIS_SAATI;
		
		private System.Nullable<System.DateTime> _ENSON_PATLADIGI_TARIH;
		
		private string _ENSON_PATLADIGI_SAATI;
		
		private bool _GOSTERSIN_MI_2_SAAT_ONCE;
		
		private System.Nullable<System.DateTime> _ENSON_EXTRA_2_SAAT_ONCE;
		
		private bool _GOSTERSIN_MI_1_GUN_ONCE;
		
		private System.Nullable<System.DateTime> _ENSON_EXTRA_1_GUN_ONCE;
		
		private System.Nullable<System.DateTime> _OZEL_GUN_TARIHI;
		
		private string _OZEL_GUN_AY;
		
		private string _OZEL_GUN_GUN;
		
		private string _ACIKLAMA;
		
		private System.DateTime _KAYIT_TARIHI;
		
		private short _SUBE_KODU;
		
		private bool _ADMIN_KAYIT_MI;
		
		private System.DateTime _KONTROL_NE_ZAMAN;
		
		private string _KONTROL_KIM;
		
		private int _KONTROL_VERSIYON;
		
		private short _STAMP;
		
		private System.Nullable<int> _KONTROL_KIM_ID;
		
		private System.Nullable<int> _SUBE_KOD_ID;
		
		private System.Nullable<int> _IS_TARAF_ID;
		
		private System.Nullable<int> _HATIRLATMA_ARALIG;
		
		private string _HATIRLATMA_TIPI;
		
		private System.Nullable<int> _PERIYOT_TIPI;
		
		private System.Nullable<int> _TEKRAR;
		
		private string _SECILEN_GUNLER;
		
		private System.Nullable<int> _GUN;
		
		private System.Nullable<bool> _ERTELEME;
		
		private System.Nullable<int> _ERTELEME_ZAMAN;
		
		private System.Nullable<bool> _AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKULLANICI_IDChanging(int value);
    partial void OnKULLANICI_IDChanged();
    partial void OnREFERANS_NOChanging(string value);
    partial void OnREFERANS_NOChanged();
    partial void OnIS_IDChanging(System.Nullable<int> value);
    partial void OnIS_IDChanged();
    partial void OnFIRMA_TABLO_KODUChanging(string value);
    partial void OnFIRMA_TABLO_KODUChanged();
    partial void OnHATIRLATSIN_MIChanging(bool value);
    partial void OnHATIRLATSIN_MIChanged();
    partial void OnGUNLUK_UYARI_SAATChanging(string value);
    partial void OnGUNLUK_UYARI_SAATChanged();
    partial void OnSONRAKI_UYARI_SAATChanging(int value);
    partial void OnSONRAKI_UYARI_SAATChanged();
    partial void OnSONRAKI_UYARI_DAKIKAChanging(int value);
    partial void OnSONRAKI_UYARI_DAKIKAChanged();
    partial void OnPERIYOD_IDChanging(int value);
    partial void OnPERIYOD_IDChanged();
    partial void OnPERIYODChanging(string value);
    partial void OnPERIYODChanged();
    partial void OnBASLANGIC_IDChanging(int value);
    partial void OnBASLANGIC_IDChanged();
    partial void OnBASLANGICChanging(string value);
    partial void OnBASLANGICChanged();
    partial void OnPERIYODUN_SON_PATLAMASI_OLDU_MUChanging(bool value);
    partial void OnPERIYODUN_SON_PATLAMASI_OLDU_MUChanged();
    partial void OnBIR_DEFA_PATLAMASI_OLDU_MUChanging(bool value);
    partial void OnBIR_DEFA_PATLAMASI_OLDU_MUChanged();
    partial void OnBASLAMA_TARIHIChanging(System.DateTime value);
    partial void OnBASLAMA_TARIHIChanged();
    partial void OnBASLAMA_SAATIChanging(string value);
    partial void OnBASLAMA_SAATIChanged();
    partial void OnBITIS_TARIHIChanging(System.DateTime value);
    partial void OnBITIS_TARIHIChanged();
    partial void OnBITIS_SAATIChanging(string value);
    partial void OnBITIS_SAATIChanged();
    partial void OnENSON_PATLADIGI_TARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnENSON_PATLADIGI_TARIHChanged();
    partial void OnENSON_PATLADIGI_SAATIChanging(string value);
    partial void OnENSON_PATLADIGI_SAATIChanged();
    partial void OnGOSTERSIN_MI_2_SAAT_ONCEChanging(bool value);
    partial void OnGOSTERSIN_MI_2_SAAT_ONCEChanged();
    partial void OnENSON_EXTRA_2_SAAT_ONCEChanging(System.Nullable<System.DateTime> value);
    partial void OnENSON_EXTRA_2_SAAT_ONCEChanged();
    partial void OnGOSTERSIN_MI_1_GUN_ONCEChanging(bool value);
    partial void OnGOSTERSIN_MI_1_GUN_ONCEChanged();
    partial void OnENSON_EXTRA_1_GUN_ONCEChanging(System.Nullable<System.DateTime> value);
    partial void OnENSON_EXTRA_1_GUN_ONCEChanged();
    partial void OnOZEL_GUN_TARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnOZEL_GUN_TARIHIChanged();
    partial void OnOZEL_GUN_AYChanging(string value);
    partial void OnOZEL_GUN_AYChanged();
    partial void OnOZEL_GUN_GUNChanging(string value);
    partial void OnOZEL_GUN_GUNChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnKAYIT_TARIHIChanging(System.DateTime value);
    partial void OnKAYIT_TARIHIChanged();
    partial void OnSUBE_KODUChanging(short value);
    partial void OnSUBE_KODUChanged();
    partial void OnADMIN_KAYIT_MIChanging(bool value);
    partial void OnADMIN_KAYIT_MIChanged();
    partial void OnKONTROL_NE_ZAMANChanging(System.DateTime value);
    partial void OnKONTROL_NE_ZAMANChanged();
    partial void OnKONTROL_KIMChanging(string value);
    partial void OnKONTROL_KIMChanged();
    partial void OnKONTROL_VERSIYONChanging(int value);
    partial void OnKONTROL_VERSIYONChanged();
    partial void OnSTAMPChanging(short value);
    partial void OnSTAMPChanged();
    partial void OnKONTROL_KIM_IDChanging(System.Nullable<int> value);
    partial void OnKONTROL_KIM_IDChanged();
    partial void OnSUBE_KOD_IDChanging(System.Nullable<int> value);
    partial void OnSUBE_KOD_IDChanged();
    partial void OnIS_TARAF_IDChanging(System.Nullable<int> value);
    partial void OnIS_TARAF_IDChanged();
    partial void OnHATIRLATMA_ARALIGChanging(System.Nullable<int> value);
    partial void OnHATIRLATMA_ARALIGChanged();
    partial void OnHATIRLATMA_TIPIChanging(string value);
    partial void OnHATIRLATMA_TIPIChanged();
    partial void OnPERIYOT_TIPIChanging(System.Nullable<int> value);
    partial void OnPERIYOT_TIPIChanged();
    partial void OnTEKRARChanging(System.Nullable<int> value);
    partial void OnTEKRARChanged();
    partial void OnSECILEN_GUNLERChanging(string value);
    partial void OnSECILEN_GUNLERChanged();
    partial void OnGUNChanging(System.Nullable<int> value);
    partial void OnGUNChanged();
    partial void OnERTELEMEChanging(System.Nullable<bool> value);
    partial void OnERTELEMEChanged();
    partial void OnERTELEME_ZAMANChanging(System.Nullable<int> value);
    partial void OnERTELEME_ZAMANChanged();
    partial void OnAKTIFChanging(System.Nullable<bool> value);
    partial void OnAKTIFChanged();
    #endregion
		
		public AV001_TDI_BIL_HATIRLAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICI_ID", DbType="Int NOT NULL")]
		public int KULLANICI_ID
		{
			get
			{
				return this._KULLANICI_ID;
			}
			set
			{
				if ((this._KULLANICI_ID != value))
				{
					this.OnKULLANICI_IDChanging(value);
					this.SendPropertyChanging();
					this._KULLANICI_ID = value;
					this.SendPropertyChanged("KULLANICI_ID");
					this.OnKULLANICI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERANS_NO", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string REFERANS_NO
		{
			get
			{
				return this._REFERANS_NO;
			}
			set
			{
				if ((this._REFERANS_NO != value))
				{
					this.OnREFERANS_NOChanging(value);
					this.SendPropertyChanging();
					this._REFERANS_NO = value;
					this.SendPropertyChanged("REFERANS_NO");
					this.OnREFERANS_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ID", DbType="Int")]
		public System.Nullable<int> IS_ID
		{
			get
			{
				return this._IS_ID;
			}
			set
			{
				if ((this._IS_ID != value))
				{
					this.OnIS_IDChanging(value);
					this.SendPropertyChanging();
					this._IS_ID = value;
					this.SendPropertyChanged("IS_ID");
					this.OnIS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMA_TABLO_KODU", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string FIRMA_TABLO_KODU
		{
			get
			{
				return this._FIRMA_TABLO_KODU;
			}
			set
			{
				if ((this._FIRMA_TABLO_KODU != value))
				{
					this.OnFIRMA_TABLO_KODUChanging(value);
					this.SendPropertyChanging();
					this._FIRMA_TABLO_KODU = value;
					this.SendPropertyChanged("FIRMA_TABLO_KODU");
					this.OnFIRMA_TABLO_KODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLATSIN_MI", DbType="Bit NOT NULL")]
		public bool HATIRLATSIN_MI
		{
			get
			{
				return this._HATIRLATSIN_MI;
			}
			set
			{
				if ((this._HATIRLATSIN_MI != value))
				{
					this.OnHATIRLATSIN_MIChanging(value);
					this.SendPropertyChanging();
					this._HATIRLATSIN_MI = value;
					this.SendPropertyChanged("HATIRLATSIN_MI");
					this.OnHATIRLATSIN_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUNLUK_UYARI_SAAT", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GUNLUK_UYARI_SAAT
		{
			get
			{
				return this._GUNLUK_UYARI_SAAT;
			}
			set
			{
				if ((this._GUNLUK_UYARI_SAAT != value))
				{
					this.OnGUNLUK_UYARI_SAATChanging(value);
					this.SendPropertyChanging();
					this._GUNLUK_UYARI_SAAT = value;
					this.SendPropertyChanged("GUNLUK_UYARI_SAAT");
					this.OnGUNLUK_UYARI_SAATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONRAKI_UYARI_SAAT", DbType="Int NOT NULL")]
		public int SONRAKI_UYARI_SAAT
		{
			get
			{
				return this._SONRAKI_UYARI_SAAT;
			}
			set
			{
				if ((this._SONRAKI_UYARI_SAAT != value))
				{
					this.OnSONRAKI_UYARI_SAATChanging(value);
					this.SendPropertyChanging();
					this._SONRAKI_UYARI_SAAT = value;
					this.SendPropertyChanged("SONRAKI_UYARI_SAAT");
					this.OnSONRAKI_UYARI_SAATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONRAKI_UYARI_DAKIKA", DbType="Int NOT NULL")]
		public int SONRAKI_UYARI_DAKIKA
		{
			get
			{
				return this._SONRAKI_UYARI_DAKIKA;
			}
			set
			{
				if ((this._SONRAKI_UYARI_DAKIKA != value))
				{
					this.OnSONRAKI_UYARI_DAKIKAChanging(value);
					this.SendPropertyChanging();
					this._SONRAKI_UYARI_DAKIKA = value;
					this.SendPropertyChanged("SONRAKI_UYARI_DAKIKA");
					this.OnSONRAKI_UYARI_DAKIKAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIYOD_ID", DbType="Int NOT NULL")]
		public int PERIYOD_ID
		{
			get
			{
				return this._PERIYOD_ID;
			}
			set
			{
				if ((this._PERIYOD_ID != value))
				{
					this.OnPERIYOD_IDChanging(value);
					this.SendPropertyChanging();
					this._PERIYOD_ID = value;
					this.SendPropertyChanged("PERIYOD_ID");
					this.OnPERIYOD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIYOD", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string PERIYOD
		{
			get
			{
				return this._PERIYOD;
			}
			set
			{
				if ((this._PERIYOD != value))
				{
					this.OnPERIYODChanging(value);
					this.SendPropertyChanging();
					this._PERIYOD = value;
					this.SendPropertyChanged("PERIYOD");
					this.OnPERIYODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLANGIC_ID", DbType="Int NOT NULL")]
		public int BASLANGIC_ID
		{
			get
			{
				return this._BASLANGIC_ID;
			}
			set
			{
				if ((this._BASLANGIC_ID != value))
				{
					this.OnBASLANGIC_IDChanging(value);
					this.SendPropertyChanging();
					this._BASLANGIC_ID = value;
					this.SendPropertyChanged("BASLANGIC_ID");
					this.OnBASLANGIC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLANGIC", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string BASLANGIC
		{
			get
			{
				return this._BASLANGIC;
			}
			set
			{
				if ((this._BASLANGIC != value))
				{
					this.OnBASLANGICChanging(value);
					this.SendPropertyChanging();
					this._BASLANGIC = value;
					this.SendPropertyChanged("BASLANGIC");
					this.OnBASLANGICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIYODUN_SON_PATLAMASI_OLDU_MU", DbType="Bit NOT NULL")]
		public bool PERIYODUN_SON_PATLAMASI_OLDU_MU
		{
			get
			{
				return this._PERIYODUN_SON_PATLAMASI_OLDU_MU;
			}
			set
			{
				if ((this._PERIYODUN_SON_PATLAMASI_OLDU_MU != value))
				{
					this.OnPERIYODUN_SON_PATLAMASI_OLDU_MUChanging(value);
					this.SendPropertyChanging();
					this._PERIYODUN_SON_PATLAMASI_OLDU_MU = value;
					this.SendPropertyChanged("PERIYODUN_SON_PATLAMASI_OLDU_MU");
					this.OnPERIYODUN_SON_PATLAMASI_OLDU_MUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIR_DEFA_PATLAMASI_OLDU_MU", DbType="Bit NOT NULL")]
		public bool BIR_DEFA_PATLAMASI_OLDU_MU
		{
			get
			{
				return this._BIR_DEFA_PATLAMASI_OLDU_MU;
			}
			set
			{
				if ((this._BIR_DEFA_PATLAMASI_OLDU_MU != value))
				{
					this.OnBIR_DEFA_PATLAMASI_OLDU_MUChanging(value);
					this.SendPropertyChanging();
					this._BIR_DEFA_PATLAMASI_OLDU_MU = value;
					this.SendPropertyChanged("BIR_DEFA_PATLAMASI_OLDU_MU");
					this.OnBIR_DEFA_PATLAMASI_OLDU_MUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLAMA_TARIHI", DbType="SmallDateTime NOT NULL")]
		public System.DateTime BASLAMA_TARIHI
		{
			get
			{
				return this._BASLAMA_TARIHI;
			}
			set
			{
				if ((this._BASLAMA_TARIHI != value))
				{
					this.OnBASLAMA_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._BASLAMA_TARIHI = value;
					this.SendPropertyChanged("BASLAMA_TARIHI");
					this.OnBASLAMA_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLAMA_SAATI", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string BASLAMA_SAATI
		{
			get
			{
				return this._BASLAMA_SAATI;
			}
			set
			{
				if ((this._BASLAMA_SAATI != value))
				{
					this.OnBASLAMA_SAATIChanging(value);
					this.SendPropertyChanging();
					this._BASLAMA_SAATI = value;
					this.SendPropertyChanged("BASLAMA_SAATI");
					this.OnBASLAMA_SAATIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BITIS_TARIHI", DbType="SmallDateTime NOT NULL")]
		public System.DateTime BITIS_TARIHI
		{
			get
			{
				return this._BITIS_TARIHI;
			}
			set
			{
				if ((this._BITIS_TARIHI != value))
				{
					this.OnBITIS_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._BITIS_TARIHI = value;
					this.SendPropertyChanged("BITIS_TARIHI");
					this.OnBITIS_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BITIS_SAATI", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string BITIS_SAATI
		{
			get
			{
				return this._BITIS_SAATI;
			}
			set
			{
				if ((this._BITIS_SAATI != value))
				{
					this.OnBITIS_SAATIChanging(value);
					this.SendPropertyChanging();
					this._BITIS_SAATI = value;
					this.SendPropertyChanged("BITIS_SAATI");
					this.OnBITIS_SAATIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENSON_PATLADIGI_TARIH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ENSON_PATLADIGI_TARIH
		{
			get
			{
				return this._ENSON_PATLADIGI_TARIH;
			}
			set
			{
				if ((this._ENSON_PATLADIGI_TARIH != value))
				{
					this.OnENSON_PATLADIGI_TARIHChanging(value);
					this.SendPropertyChanging();
					this._ENSON_PATLADIGI_TARIH = value;
					this.SendPropertyChanged("ENSON_PATLADIGI_TARIH");
					this.OnENSON_PATLADIGI_TARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENSON_PATLADIGI_SAATI", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string ENSON_PATLADIGI_SAATI
		{
			get
			{
				return this._ENSON_PATLADIGI_SAATI;
			}
			set
			{
				if ((this._ENSON_PATLADIGI_SAATI != value))
				{
					this.OnENSON_PATLADIGI_SAATIChanging(value);
					this.SendPropertyChanging();
					this._ENSON_PATLADIGI_SAATI = value;
					this.SendPropertyChanged("ENSON_PATLADIGI_SAATI");
					this.OnENSON_PATLADIGI_SAATIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOSTERSIN_MI_2_SAAT_ONCE", DbType="Bit NOT NULL")]
		public bool GOSTERSIN_MI_2_SAAT_ONCE
		{
			get
			{
				return this._GOSTERSIN_MI_2_SAAT_ONCE;
			}
			set
			{
				if ((this._GOSTERSIN_MI_2_SAAT_ONCE != value))
				{
					this.OnGOSTERSIN_MI_2_SAAT_ONCEChanging(value);
					this.SendPropertyChanging();
					this._GOSTERSIN_MI_2_SAAT_ONCE = value;
					this.SendPropertyChanged("GOSTERSIN_MI_2_SAAT_ONCE");
					this.OnGOSTERSIN_MI_2_SAAT_ONCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENSON_EXTRA_2_SAAT_ONCE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ENSON_EXTRA_2_SAAT_ONCE
		{
			get
			{
				return this._ENSON_EXTRA_2_SAAT_ONCE;
			}
			set
			{
				if ((this._ENSON_EXTRA_2_SAAT_ONCE != value))
				{
					this.OnENSON_EXTRA_2_SAAT_ONCEChanging(value);
					this.SendPropertyChanging();
					this._ENSON_EXTRA_2_SAAT_ONCE = value;
					this.SendPropertyChanged("ENSON_EXTRA_2_SAAT_ONCE");
					this.OnENSON_EXTRA_2_SAAT_ONCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOSTERSIN_MI_1_GUN_ONCE", DbType="Bit NOT NULL")]
		public bool GOSTERSIN_MI_1_GUN_ONCE
		{
			get
			{
				return this._GOSTERSIN_MI_1_GUN_ONCE;
			}
			set
			{
				if ((this._GOSTERSIN_MI_1_GUN_ONCE != value))
				{
					this.OnGOSTERSIN_MI_1_GUN_ONCEChanging(value);
					this.SendPropertyChanging();
					this._GOSTERSIN_MI_1_GUN_ONCE = value;
					this.SendPropertyChanged("GOSTERSIN_MI_1_GUN_ONCE");
					this.OnGOSTERSIN_MI_1_GUN_ONCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENSON_EXTRA_1_GUN_ONCE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ENSON_EXTRA_1_GUN_ONCE
		{
			get
			{
				return this._ENSON_EXTRA_1_GUN_ONCE;
			}
			set
			{
				if ((this._ENSON_EXTRA_1_GUN_ONCE != value))
				{
					this.OnENSON_EXTRA_1_GUN_ONCEChanging(value);
					this.SendPropertyChanging();
					this._ENSON_EXTRA_1_GUN_ONCE = value;
					this.SendPropertyChanged("ENSON_EXTRA_1_GUN_ONCE");
					this.OnENSON_EXTRA_1_GUN_ONCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OZEL_GUN_TARIHI", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> OZEL_GUN_TARIHI
		{
			get
			{
				return this._OZEL_GUN_TARIHI;
			}
			set
			{
				if ((this._OZEL_GUN_TARIHI != value))
				{
					this.OnOZEL_GUN_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._OZEL_GUN_TARIHI = value;
					this.SendPropertyChanged("OZEL_GUN_TARIHI");
					this.OnOZEL_GUN_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OZEL_GUN_AY", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string OZEL_GUN_AY
		{
			get
			{
				return this._OZEL_GUN_AY;
			}
			set
			{
				if ((this._OZEL_GUN_AY != value))
				{
					this.OnOZEL_GUN_AYChanging(value);
					this.SendPropertyChanging();
					this._OZEL_GUN_AY = value;
					this.SendPropertyChanged("OZEL_GUN_AY");
					this.OnOZEL_GUN_AYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OZEL_GUN_GUN", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string OZEL_GUN_GUN
		{
			get
			{
				return this._OZEL_GUN_GUN;
			}
			set
			{
				if ((this._OZEL_GUN_GUN != value))
				{
					this.OnOZEL_GUN_GUNChanging(value);
					this.SendPropertyChanging();
					this._OZEL_GUN_GUN = value;
					this.SendPropertyChanged("OZEL_GUN_GUN");
					this.OnOZEL_GUN_GUNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAYIT_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime KAYIT_TARIHI
		{
			get
			{
				return this._KAYIT_TARIHI;
			}
			set
			{
				if ((this._KAYIT_TARIHI != value))
				{
					this.OnKAYIT_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._KAYIT_TARIHI = value;
					this.SendPropertyChanged("KAYIT_TARIHI");
					this.OnKAYIT_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE_KODU", DbType="SmallInt NOT NULL")]
		public short SUBE_KODU
		{
			get
			{
				return this._SUBE_KODU;
			}
			set
			{
				if ((this._SUBE_KODU != value))
				{
					this.OnSUBE_KODUChanging(value);
					this.SendPropertyChanging();
					this._SUBE_KODU = value;
					this.SendPropertyChanged("SUBE_KODU");
					this.OnSUBE_KODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADMIN_KAYIT_MI", DbType="Bit NOT NULL")]
		public bool ADMIN_KAYIT_MI
		{
			get
			{
				return this._ADMIN_KAYIT_MI;
			}
			set
			{
				if ((this._ADMIN_KAYIT_MI != value))
				{
					this.OnADMIN_KAYIT_MIChanging(value);
					this.SendPropertyChanging();
					this._ADMIN_KAYIT_MI = value;
					this.SendPropertyChanged("ADMIN_KAYIT_MI");
					this.OnADMIN_KAYIT_MIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_NE_ZAMAN", DbType="DateTime NOT NULL")]
		public System.DateTime KONTROL_NE_ZAMAN
		{
			get
			{
				return this._KONTROL_NE_ZAMAN;
			}
			set
			{
				if ((this._KONTROL_NE_ZAMAN != value))
				{
					this.OnKONTROL_NE_ZAMANChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_NE_ZAMAN = value;
					this.SendPropertyChanged("KONTROL_NE_ZAMAN");
					this.OnKONTROL_NE_ZAMANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_KIM", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string KONTROL_KIM
		{
			get
			{
				return this._KONTROL_KIM;
			}
			set
			{
				if ((this._KONTROL_KIM != value))
				{
					this.OnKONTROL_KIMChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_KIM = value;
					this.SendPropertyChanged("KONTROL_KIM");
					this.OnKONTROL_KIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_VERSIYON", DbType="Int NOT NULL")]
		public int KONTROL_VERSIYON
		{
			get
			{
				return this._KONTROL_VERSIYON;
			}
			set
			{
				if ((this._KONTROL_VERSIYON != value))
				{
					this.OnKONTROL_VERSIYONChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_VERSIYON = value;
					this.SendPropertyChanged("KONTROL_VERSIYON");
					this.OnKONTROL_VERSIYONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAMP", DbType="SmallInt NOT NULL")]
		public short STAMP
		{
			get
			{
				return this._STAMP;
			}
			set
			{
				if ((this._STAMP != value))
				{
					this.OnSTAMPChanging(value);
					this.SendPropertyChanging();
					this._STAMP = value;
					this.SendPropertyChanged("STAMP");
					this.OnSTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL_KIM_ID", DbType="Int")]
		public System.Nullable<int> KONTROL_KIM_ID
		{
			get
			{
				return this._KONTROL_KIM_ID;
			}
			set
			{
				if ((this._KONTROL_KIM_ID != value))
				{
					this.OnKONTROL_KIM_IDChanging(value);
					this.SendPropertyChanging();
					this._KONTROL_KIM_ID = value;
					this.SendPropertyChanged("KONTROL_KIM_ID");
					this.OnKONTROL_KIM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE_KOD_ID", DbType="Int")]
		public System.Nullable<int> SUBE_KOD_ID
		{
			get
			{
				return this._SUBE_KOD_ID;
			}
			set
			{
				if ((this._SUBE_KOD_ID != value))
				{
					this.OnSUBE_KOD_IDChanging(value);
					this.SendPropertyChanging();
					this._SUBE_KOD_ID = value;
					this.SendPropertyChanged("SUBE_KOD_ID");
					this.OnSUBE_KOD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_TARAF_ID", DbType="Int")]
		public System.Nullable<int> IS_TARAF_ID
		{
			get
			{
				return this._IS_TARAF_ID;
			}
			set
			{
				if ((this._IS_TARAF_ID != value))
				{
					this.OnIS_TARAF_IDChanging(value);
					this.SendPropertyChanging();
					this._IS_TARAF_ID = value;
					this.SendPropertyChanged("IS_TARAF_ID");
					this.OnIS_TARAF_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLATMA_ARALIG", DbType="Int")]
		public System.Nullable<int> HATIRLATMA_ARALIG
		{
			get
			{
				return this._HATIRLATMA_ARALIG;
			}
			set
			{
				if ((this._HATIRLATMA_ARALIG != value))
				{
					this.OnHATIRLATMA_ARALIGChanging(value);
					this.SendPropertyChanging();
					this._HATIRLATMA_ARALIG = value;
					this.SendPropertyChanged("HATIRLATMA_ARALIG");
					this.OnHATIRLATMA_ARALIGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLATMA_TIPI", DbType="NVarChar(50)")]
		public string HATIRLATMA_TIPI
		{
			get
			{
				return this._HATIRLATMA_TIPI;
			}
			set
			{
				if ((this._HATIRLATMA_TIPI != value))
				{
					this.OnHATIRLATMA_TIPIChanging(value);
					this.SendPropertyChanging();
					this._HATIRLATMA_TIPI = value;
					this.SendPropertyChanged("HATIRLATMA_TIPI");
					this.OnHATIRLATMA_TIPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIYOT_TIPI", DbType="Int")]
		public System.Nullable<int> PERIYOT_TIPI
		{
			get
			{
				return this._PERIYOT_TIPI;
			}
			set
			{
				if ((this._PERIYOT_TIPI != value))
				{
					this.OnPERIYOT_TIPIChanging(value);
					this.SendPropertyChanging();
					this._PERIYOT_TIPI = value;
					this.SendPropertyChanged("PERIYOT_TIPI");
					this.OnPERIYOT_TIPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEKRAR", DbType="Int")]
		public System.Nullable<int> TEKRAR
		{
			get
			{
				return this._TEKRAR;
			}
			set
			{
				if ((this._TEKRAR != value))
				{
					this.OnTEKRARChanging(value);
					this.SendPropertyChanging();
					this._TEKRAR = value;
					this.SendPropertyChanged("TEKRAR");
					this.OnTEKRARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECILEN_GUNLER", DbType="NVarChar(20)")]
		public string SECILEN_GUNLER
		{
			get
			{
				return this._SECILEN_GUNLER;
			}
			set
			{
				if ((this._SECILEN_GUNLER != value))
				{
					this.OnSECILEN_GUNLERChanging(value);
					this.SendPropertyChanging();
					this._SECILEN_GUNLER = value;
					this.SendPropertyChanged("SECILEN_GUNLER");
					this.OnSECILEN_GUNLERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUN", DbType="Int")]
		public System.Nullable<int> GUN
		{
			get
			{
				return this._GUN;
			}
			set
			{
				if ((this._GUN != value))
				{
					this.OnGUNChanging(value);
					this.SendPropertyChanging();
					this._GUN = value;
					this.SendPropertyChanged("GUN");
					this.OnGUNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERTELEME", DbType="Bit")]
		public System.Nullable<bool> ERTELEME
		{
			get
			{
				return this._ERTELEME;
			}
			set
			{
				if ((this._ERTELEME != value))
				{
					this.OnERTELEMEChanging(value);
					this.SendPropertyChanging();
					this._ERTELEME = value;
					this.SendPropertyChanged("ERTELEME");
					this.OnERTELEMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERTELEME_ZAMAN", DbType="Int")]
		public System.Nullable<int> ERTELEME_ZAMAN
		{
			get
			{
				return this._ERTELEME_ZAMAN;
			}
			set
			{
				if ((this._ERTELEME_ZAMAN != value))
				{
					this.OnERTELEME_ZAMANChanging(value);
					this.SendPropertyChanging();
					this._ERTELEME_ZAMAN = value;
					this.SendPropertyChanged("ERTELEME_ZAMAN");
					this.OnERTELEME_ZAMANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKTIF", DbType="Bit")]
		public System.Nullable<bool> AKTIF
		{
			get
			{
				return this._AKTIF;
			}
			set
			{
				if ((this._AKTIF != value))
				{
					this.OnAKTIFChanging(value);
					this.SendPropertyChanging();
					this._AKTIF = value;
					this.SendPropertyChanged("AKTIF");
					this.OnAKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.per_REMINDER")]
	public partial class per_REMINDER
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<bool> _HATIRLATILSIN_MI;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _BASLANGIC_TARIHI;
		
		private System.Nullable<int> _HATIRLAT_ID;
		
		private System.Nullable<System.DateTime> _HATIRLATMA_BASLAMA_TARIHI;
		
		private System.Nullable<System.DateTime> _ENSON_EXTRA_1_GUN_ONCE;
		
		private System.Nullable<System.DateTime> _BITIS_TARIHI;
		
		private System.Nullable<System.DateTime> _ONGORULEN_BITIS_TARIHI;
		
		private string _YAPILACAK_IS;
		
		private string _YER;
		
		private string _HATIRLATMA_BILGISI;
		
		private string _TEKRARLAMA_BILGISI;
		
		private string _KONU;
		
		private string _IS_TARAF;
		
		private System.Nullable<int> _CARI_ID;
		
		private string _AD;
		
		private string _CEP_TEL;
		
		private string _EMAIL_1;
		
		private string _HATIRLATMA_TIPI;
		
		private string _ZAMAN_KOSULU;
		
		private System.Nullable<bool> _DURUM;
		
		private string _BELGE_ADI;
		
		private string _BELGE_ACIKLAMA;
		
		private string _DOSYA_ADI;
		
		private System.Data.Linq.Binary _THUMBNAIL;
		
		private System.Data.Linq.Binary _ICERIK;
		
		private string _DOKUMAN_UZANTI;
		
		private System.Nullable<int> _BELGE_ID;
		
		private string _FAX;
		
		private string _TC_KIMLIK_NO;
		
		private string _ADLIYE;
		
		private string _GOREV;
		
		private string _NO;
		
		private string _ESAS_NO;
		
		private System.Nullable<int> _ONCELIK_ID;
		
		private string _GUNLUK_UYARI_SAAT;
		
		private System.Nullable<bool> _PERIYODUN_SON_PATLAMASI_OLDU_MU;
		
		private System.Nullable<bool> _BIR_DEFA_PATLAMASI_OLDU_MU;
		
		private System.Nullable<int> _TEKRAR;
		
		private System.Nullable<bool> _GOSTERSIN_MI_1_GUN_ONCE;
		
		public per_REMINDER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLATILSIN_MI", DbType="Bit")]
		public System.Nullable<bool> HATIRLATILSIN_MI
		{
			get
			{
				return this._HATIRLATILSIN_MI;
			}
			set
			{
				if ((this._HATIRLATILSIN_MI != value))
				{
					this._HATIRLATILSIN_MI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="NVarChar(MAX)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this._ACIKLAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLANGIC_TARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> BASLANGIC_TARIHI
		{
			get
			{
				return this._BASLANGIC_TARIHI;
			}
			set
			{
				if ((this._BASLANGIC_TARIHI != value))
				{
					this._BASLANGIC_TARIHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLAT_ID", DbType="Int")]
		public System.Nullable<int> HATIRLAT_ID
		{
			get
			{
				return this._HATIRLAT_ID;
			}
			set
			{
				if ((this._HATIRLAT_ID != value))
				{
					this._HATIRLAT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLATMA_BASLAMA_TARIHI", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HATIRLATMA_BASLAMA_TARIHI
		{
			get
			{
				return this._HATIRLATMA_BASLAMA_TARIHI;
			}
			set
			{
				if ((this._HATIRLATMA_BASLAMA_TARIHI != value))
				{
					this._HATIRLATMA_BASLAMA_TARIHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENSON_EXTRA_1_GUN_ONCE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ENSON_EXTRA_1_GUN_ONCE
		{
			get
			{
				return this._ENSON_EXTRA_1_GUN_ONCE;
			}
			set
			{
				if ((this._ENSON_EXTRA_1_GUN_ONCE != value))
				{
					this._ENSON_EXTRA_1_GUN_ONCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BITIS_TARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> BITIS_TARIHI
		{
			get
			{
				return this._BITIS_TARIHI;
			}
			set
			{
				if ((this._BITIS_TARIHI != value))
				{
					this._BITIS_TARIHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ONGORULEN_BITIS_TARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> ONGORULEN_BITIS_TARIHI
		{
			get
			{
				return this._ONGORULEN_BITIS_TARIHI;
			}
			set
			{
				if ((this._ONGORULEN_BITIS_TARIHI != value))
				{
					this._ONGORULEN_BITIS_TARIHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YAPILACAK_IS", DbType="NVarChar(4000)")]
		public string YAPILACAK_IS
		{
			get
			{
				return this._YAPILACAK_IS;
			}
			set
			{
				if ((this._YAPILACAK_IS != value))
				{
					this._YAPILACAK_IS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YER", DbType="NVarChar(500)")]
		public string YER
		{
			get
			{
				return this._YER;
			}
			set
			{
				if ((this._YER != value))
				{
					this._YER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLATMA_BILGISI", DbType="NVarChar(MAX)")]
		public string HATIRLATMA_BILGISI
		{
			get
			{
				return this._HATIRLATMA_BILGISI;
			}
			set
			{
				if ((this._HATIRLATMA_BILGISI != value))
				{
					this._HATIRLATMA_BILGISI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEKRARLAMA_BILGISI", DbType="NVarChar(MAX)")]
		public string TEKRARLAMA_BILGISI
		{
			get
			{
				return this._TEKRARLAMA_BILGISI;
			}
			set
			{
				if ((this._TEKRARLAMA_BILGISI != value))
				{
					this._TEKRARLAMA_BILGISI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONU", DbType="NVarChar(500)")]
		public string KONU
		{
			get
			{
				return this._KONU;
			}
			set
			{
				if ((this._KONU != value))
				{
					this._KONU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_TARAF", DbType="NVarChar(64)")]
		public string IS_TARAF
		{
			get
			{
				return this._IS_TARAF;
			}
			set
			{
				if ((this._IS_TARAF != value))
				{
					this._IS_TARAF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARI_ID", DbType="Int")]
		public System.Nullable<int> CARI_ID
		{
			get
			{
				return this._CARI_ID;
			}
			set
			{
				if ((this._CARI_ID != value))
				{
					this._CARI_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AD", DbType="NVarChar(128)")]
		public string AD
		{
			get
			{
				return this._AD;
			}
			set
			{
				if ((this._AD != value))
				{
					this._AD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP_TEL", DbType="NVarChar(16)")]
		public string CEP_TEL
		{
			get
			{
				return this._CEP_TEL;
			}
			set
			{
				if ((this._CEP_TEL != value))
				{
					this._CEP_TEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_1", DbType="NVarChar(64)")]
		public string EMAIL_1
		{
			get
			{
				return this._EMAIL_1;
			}
			set
			{
				if ((this._EMAIL_1 != value))
				{
					this._EMAIL_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HATIRLATMA_TIPI", DbType="NVarChar(50)")]
		public string HATIRLATMA_TIPI
		{
			get
			{
				return this._HATIRLATMA_TIPI;
			}
			set
			{
				if ((this._HATIRLATMA_TIPI != value))
				{
					this._HATIRLATMA_TIPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAMAN_KOSULU", DbType="NVarChar(500)")]
		public string ZAMAN_KOSULU
		{
			get
			{
				return this._ZAMAN_KOSULU;
			}
			set
			{
				if ((this._ZAMAN_KOSULU != value))
				{
					this._ZAMAN_KOSULU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="Bit")]
		public System.Nullable<bool> DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this._DURUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGE_ADI", DbType="NVarChar(255)")]
		public string BELGE_ADI
		{
			get
			{
				return this._BELGE_ADI;
			}
			set
			{
				if ((this._BELGE_ADI != value))
				{
					this._BELGE_ADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGE_ACIKLAMA", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string BELGE_ACIKLAMA
		{
			get
			{
				return this._BELGE_ACIKLAMA;
			}
			set
			{
				if ((this._BELGE_ACIKLAMA != value))
				{
					this._BELGE_ACIKLAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSYA_ADI", DbType="NVarChar(255)")]
		public string DOSYA_ADI
		{
			get
			{
				return this._DOSYA_ADI;
			}
			set
			{
				if ((this._DOSYA_ADI != value))
				{
					this._DOSYA_ADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUMBNAIL", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary THUMBNAIL
		{
			get
			{
				return this._THUMBNAIL;
			}
			set
			{
				if ((this._THUMBNAIL != value))
				{
					this._THUMBNAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICERIK", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ICERIK
		{
			get
			{
				return this._ICERIK;
			}
			set
			{
				if ((this._ICERIK != value))
				{
					this._ICERIK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOKUMAN_UZANTI", DbType="NVarChar(16)")]
		public string DOKUMAN_UZANTI
		{
			get
			{
				return this._DOKUMAN_UZANTI;
			}
			set
			{
				if ((this._DOKUMAN_UZANTI != value))
				{
					this._DOKUMAN_UZANTI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGE_ID", DbType="Int")]
		public System.Nullable<int> BELGE_ID
		{
			get
			{
				return this._BELGE_ID;
			}
			set
			{
				if ((this._BELGE_ID != value))
				{
					this._BELGE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="NVarChar(16)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this._FAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC_KIMLIK_NO", DbType="NVarChar(32)")]
		public string TC_KIMLIK_NO
		{
			get
			{
				return this._TC_KIMLIK_NO;
			}
			set
			{
				if ((this._TC_KIMLIK_NO != value))
				{
					this._TC_KIMLIK_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADLIYE", DbType="NVarChar(32)")]
		public string ADLIYE
		{
			get
			{
				return this._ADLIYE;
			}
			set
			{
				if ((this._ADLIYE != value))
				{
					this._ADLIYE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOREV", DbType="NVarChar(6)")]
		public string GOREV
		{
			get
			{
				return this._GOREV;
			}
			set
			{
				if ((this._GOREV != value))
				{
					this._GOREV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO", DbType="NVarChar(4)")]
		public string NO
		{
			get
			{
				return this._NO;
			}
			set
			{
				if ((this._NO != value))
				{
					this._NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESAS_NO", DbType="NVarChar(50)")]
		public string ESAS_NO
		{
			get
			{
				return this._ESAS_NO;
			}
			set
			{
				if ((this._ESAS_NO != value))
				{
					this._ESAS_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ONCELIK_ID", DbType="Int")]
		public System.Nullable<int> ONCELIK_ID
		{
			get
			{
				return this._ONCELIK_ID;
			}
			set
			{
				if ((this._ONCELIK_ID != value))
				{
					this._ONCELIK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUNLUK_UYARI_SAAT", DbType="NVarChar(5)")]
		public string GUNLUK_UYARI_SAAT
		{
			get
			{
				return this._GUNLUK_UYARI_SAAT;
			}
			set
			{
				if ((this._GUNLUK_UYARI_SAAT != value))
				{
					this._GUNLUK_UYARI_SAAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIYODUN_SON_PATLAMASI_OLDU_MU", DbType="Bit")]
		public System.Nullable<bool> PERIYODUN_SON_PATLAMASI_OLDU_MU
		{
			get
			{
				return this._PERIYODUN_SON_PATLAMASI_OLDU_MU;
			}
			set
			{
				if ((this._PERIYODUN_SON_PATLAMASI_OLDU_MU != value))
				{
					this._PERIYODUN_SON_PATLAMASI_OLDU_MU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIR_DEFA_PATLAMASI_OLDU_MU", DbType="Bit")]
		public System.Nullable<bool> BIR_DEFA_PATLAMASI_OLDU_MU
		{
			get
			{
				return this._BIR_DEFA_PATLAMASI_OLDU_MU;
			}
			set
			{
				if ((this._BIR_DEFA_PATLAMASI_OLDU_MU != value))
				{
					this._BIR_DEFA_PATLAMASI_OLDU_MU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEKRAR", DbType="Int")]
		public System.Nullable<int> TEKRAR
		{
			get
			{
				return this._TEKRAR;
			}
			set
			{
				if ((this._TEKRAR != value))
				{
					this._TEKRAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOSTERSIN_MI_1_GUN_ONCE", DbType="Bit")]
		public System.Nullable<bool> GOSTERSIN_MI_1_GUN_ONCE
		{
			get
			{
				return this._GOSTERSIN_MI_1_GUN_ONCE;
			}
			set
			{
				if ((this._GOSTERSIN_MI_1_GUN_ONCE != value))
				{
					this._GOSTERSIN_MI_1_GUN_ONCE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
