//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
//
#pragma warning disable 1591

namespace AvukatProLib.AVPLicence
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckAllCompletedEventHandler(object sender, CheckAllCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckDBVersionCompletedEventHandler(object sender, CheckDBVersionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckExeVersionCompletedEventHandler(object sender, CheckExeVersionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckProductKeyCompletedEventHandler(object sender, CheckProductKeyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckUpdaterVersionCompletedEventHandler(object sender, CheckUpdaterVersionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllCompletedEventHandler(object sender, GetAllCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateWebTablesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal CheckAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public Result Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDBVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal CheckDBVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public TMYS_DB_SURUM Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TMYS_DB_SURUM)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckExeVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal CheckExeVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public TMYS_DB_SURUM[] dbVersionList
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TMYS_DB_SURUM[])(this.results[1]));
            }
        }

        /// <remarks/>
        public TMYS_EXE_SURUM Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TMYS_EXE_SURUM)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckProductKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal CheckProductKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public LisansBilgisi Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((LisansBilgisi)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUpdaterVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal CheckUpdaterVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public TMYS_UPDATER_SURUM Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TMYS_UPDATER_SURUM)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CS_KOD_FORM_LISTESI
    {
        private bool aDMIN_KAYIT_MIField;
        private string bUTTON_GORUNUM_LISTField;
        private CS_KOD_KONTROL_LISTESI[] cS_KOD_KONTROL_LISTESIsField;
        private CS_KOD_PAKET_NN_FORM[] cS_KOD_PAKET_NN_FORMsField;
        private string dB_TABLO_ADIField;
        private string fORM_ACIKLAMAField;
        private System.Nullable<int> fORM_GRUP_IDField;
        private string fORM_TEXTField;
        private string fULL_ADIField;
        private int idField;
        private int kONTROL_KIM_IDField;
        private System.DateTime kONTROL_NE_ZAMANField;
        private int kONTROL_VERSIYONField;
        private string mENU_NESNE_ADIField;

        private System.Nullable<int> mODUL2Field;
        private System.Nullable<int> mODULField;
        private short sTAMPField;
        private int sUBE_IDField;
        private string sUZME_KRITERField;

        /// <remarks/>
        public bool ADMIN_KAYIT_MI
        {
            get
            {
                return this.aDMIN_KAYIT_MIField;
            }
            set
            {
                this.aDMIN_KAYIT_MIField = value;
            }
        }

        /// <remarks/>
        public string BUTTON_GORUNUM_LIST
        {
            get
            {
                return this.bUTTON_GORUNUM_LISTField;
            }
            set
            {
                this.bUTTON_GORUNUM_LISTField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_KONTROL_LISTESI[] CS_KOD_KONTROL_LISTESIs
        {
            get
            {
                return this.cS_KOD_KONTROL_LISTESIsField;
            }
            set
            {
                this.cS_KOD_KONTROL_LISTESIsField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_PAKET_NN_FORM[] CS_KOD_PAKET_NN_FORMs
        {
            get
            {
                return this.cS_KOD_PAKET_NN_FORMsField;
            }
            set
            {
                this.cS_KOD_PAKET_NN_FORMsField = value;
            }
        }

        /// <remarks/>
        public string DB_TABLO_ADI
        {
            get
            {
                return this.dB_TABLO_ADIField;
            }
            set
            {
                this.dB_TABLO_ADIField = value;
            }
        }

        /// <remarks/>
        public string FORM_ACIKLAMA
        {
            get
            {
                return this.fORM_ACIKLAMAField;
            }
            set
            {
                this.fORM_ACIKLAMAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> FORM_GRUP_ID
        {
            get
            {
                return this.fORM_GRUP_IDField;
            }
            set
            {
                this.fORM_GRUP_IDField = value;
            }
        }

        /// <remarks/>
        public string FORM_TEXT
        {
            get
            {
                return this.fORM_TEXTField;
            }
            set
            {
                this.fORM_TEXTField = value;
            }
        }

        /// <remarks/>
        public string FULL_ADI
        {
            get
            {
                return this.fULL_ADIField;
            }
            set
            {
                this.fULL_ADIField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public int KONTROL_KIM_ID
        {
            get
            {
                return this.kONTROL_KIM_IDField;
            }
            set
            {
                this.kONTROL_KIM_IDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KONTROL_NE_ZAMAN
        {
            get
            {
                return this.kONTROL_NE_ZAMANField;
            }
            set
            {
                this.kONTROL_NE_ZAMANField = value;
            }
        }

        /// <remarks/>
        public int KONTROL_VERSIYON
        {
            get
            {
                return this.kONTROL_VERSIYONField;
            }
            set
            {
                this.kONTROL_VERSIYONField = value;
            }
        }

        /// <remarks/>
        public string MENU_NESNE_ADI
        {
            get
            {
                return this.mENU_NESNE_ADIField;
            }
            set
            {
                this.mENU_NESNE_ADIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> MODUL
        {
            get
            {
                return this.mODULField;
            }
            set
            {
                this.mODULField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> MODUL2
        {
            get
            {
                return this.mODUL2Field;
            }
            set
            {
                this.mODUL2Field = value;
            }
        }

        /// <remarks/>
        public short STAMP
        {
            get
            {
                return this.sTAMPField;
            }
            set
            {
                this.sTAMPField = value;
            }
        }

        /// <remarks/>
        public int SUBE_ID
        {
            get
            {
                return this.sUBE_IDField;
            }
            set
            {
                this.sUBE_IDField = value;
            }
        }

        /// <remarks/>
        public string SUZME_KRITER
        {
            get
            {
                return this.sUZME_KRITERField;
            }
            set
            {
                this.sUZME_KRITERField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CS_KOD_KONTROL_LISTESI
    {
        private bool aDMIN_KAYIT_MIField;
        private CS_KOD_FORM_LISTESI cS_KOD_FORM_LISTESIField;
        private CS_KOD_KONTROL_LISTESI cS_KOD_KONTROL_LISTESI1Field;
        private CS_KOD_KONTROL_LISTESI[] cS_KOD_KONTROL_LISTESIsField;
        private CS_KOD_KONTROL_OZELLIKLERI[] cS_KOD_KONTROL_OZELLIKLERIsField;
        private int fORM_IDField;
        private int idField;
        private string kONTROL_ACIKLAMAField;
        private string kONTROL_ADIField;
        private int kONTROL_KIM_IDField;
        private System.DateTime kONTROL_NE_ZAMANField;
        private string kONTROL_TEXTField;
        private int kONTROL_VERSIYONField;
        private System.Nullable<int> pARENT_IDField;
        private short sTAMPField;
        private System.Nullable<int> sUBE_IDField;
        private string sUZME_KRITERField;
        private string tIP_ADIField;

        private System.Nullable<int> uNIQUE_IDField;

        /// <remarks/>
        public bool ADMIN_KAYIT_MI
        {
            get
            {
                return this.aDMIN_KAYIT_MIField;
            }
            set
            {
                this.aDMIN_KAYIT_MIField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_FORM_LISTESI CS_KOD_FORM_LISTESI
        {
            get
            {
                return this.cS_KOD_FORM_LISTESIField;
            }
            set
            {
                this.cS_KOD_FORM_LISTESIField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_KONTROL_LISTESI CS_KOD_KONTROL_LISTESI1
        {
            get
            {
                return this.cS_KOD_KONTROL_LISTESI1Field;
            }
            set
            {
                this.cS_KOD_KONTROL_LISTESI1Field = value;
            }
        }

        /// <remarks/>
        public CS_KOD_KONTROL_LISTESI[] CS_KOD_KONTROL_LISTESIs
        {
            get
            {
                return this.cS_KOD_KONTROL_LISTESIsField;
            }
            set
            {
                this.cS_KOD_KONTROL_LISTESIsField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_KONTROL_OZELLIKLERI[] CS_KOD_KONTROL_OZELLIKLERIs
        {
            get
            {
                return this.cS_KOD_KONTROL_OZELLIKLERIsField;
            }
            set
            {
                this.cS_KOD_KONTROL_OZELLIKLERIsField = value;
            }
        }

        /// <remarks/>
        public int FORM_ID
        {
            get
            {
                return this.fORM_IDField;
            }
            set
            {
                this.fORM_IDField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string KONTROL_ACIKLAMA
        {
            get
            {
                return this.kONTROL_ACIKLAMAField;
            }
            set
            {
                this.kONTROL_ACIKLAMAField = value;
            }
        }

        /// <remarks/>
        public string KONTROL_ADI
        {
            get
            {
                return this.kONTROL_ADIField;
            }
            set
            {
                this.kONTROL_ADIField = value;
            }
        }

        /// <remarks/>
        public int KONTROL_KIM_ID
        {
            get
            {
                return this.kONTROL_KIM_IDField;
            }
            set
            {
                this.kONTROL_KIM_IDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KONTROL_NE_ZAMAN
        {
            get
            {
                return this.kONTROL_NE_ZAMANField;
            }
            set
            {
                this.kONTROL_NE_ZAMANField = value;
            }
        }

        /// <remarks/>
        public string KONTROL_TEXT
        {
            get
            {
                return this.kONTROL_TEXTField;
            }
            set
            {
                this.kONTROL_TEXTField = value;
            }
        }

        /// <remarks/>
        public int KONTROL_VERSIYON
        {
            get
            {
                return this.kONTROL_VERSIYONField;
            }
            set
            {
                this.kONTROL_VERSIYONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PARENT_ID
        {
            get
            {
                return this.pARENT_IDField;
            }
            set
            {
                this.pARENT_IDField = value;
            }
        }

        /// <remarks/>
        public short STAMP
        {
            get
            {
                return this.sTAMPField;
            }
            set
            {
                this.sTAMPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SUBE_ID
        {
            get
            {
                return this.sUBE_IDField;
            }
            set
            {
                this.sUBE_IDField = value;
            }
        }

        /// <remarks/>
        public string SUZME_KRITER
        {
            get
            {
                return this.sUZME_KRITERField;
            }
            set
            {
                this.sUZME_KRITERField = value;
            }
        }

        /// <remarks/>
        public string TIP_ADI
        {
            get
            {
                return this.tIP_ADIField;
            }
            set
            {
                this.tIP_ADIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> UNIQUE_ID
        {
            get
            {
                return this.uNIQUE_IDField;
            }
            set
            {
                this.uNIQUE_IDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CS_KOD_KONTROL_OZELLIKLERI
    {
        private System.Nullable<byte> aKTIF_MIField;
        private CS_KOD_KONTROL_LISTESI cS_KOD_KONTROL_LISTESIField;
        private CS_KOD_PAKET cS_KOD_PAKETField;
        private System.Nullable<byte> gORUNUR_MUField;
        private int idField;

        private int kONTROL_IDField;

        private int pAKET_IDField;
        private System.Nullable<byte> sEPETTE_GOSTERILSIN_MIField;

        private System.Nullable<byte> yETKILENDIRMEDE_KULLANILSIN_MIField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<byte> AKTIF_MI
        {
            get
            {
                return this.aKTIF_MIField;
            }
            set
            {
                this.aKTIF_MIField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_KONTROL_LISTESI CS_KOD_KONTROL_LISTESI
        {
            get
            {
                return this.cS_KOD_KONTROL_LISTESIField;
            }
            set
            {
                this.cS_KOD_KONTROL_LISTESIField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_PAKET CS_KOD_PAKET
        {
            get
            {
                return this.cS_KOD_PAKETField;
            }
            set
            {
                this.cS_KOD_PAKETField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<byte> GORUNUR_MU
        {
            get
            {
                return this.gORUNUR_MUField;
            }
            set
            {
                this.gORUNUR_MUField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public int KONTROL_ID
        {
            get
            {
                return this.kONTROL_IDField;
            }
            set
            {
                this.kONTROL_IDField = value;
            }
        }

        /// <remarks/>
        public int PAKET_ID
        {
            get
            {
                return this.pAKET_IDField;
            }
            set
            {
                this.pAKET_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<byte> SEPETTE_GOSTERILSIN_MI
        {
            get
            {
                return this.sEPETTE_GOSTERILSIN_MIField;
            }
            set
            {
                this.sEPETTE_GOSTERILSIN_MIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<byte> YETKILENDIRMEDE_KULLANILSIN_MI
        {
            get
            {
                return this.yETKILENDIRMEDE_KULLANILSIN_MIField;
            }
            set
            {
                this.yETKILENDIRMEDE_KULLANILSIN_MIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CS_KOD_PAKET
    {
        private string aCIKLAMAField;
        private CS_KOD_KONTROL_OZELLIKLERI[] cS_KOD_KONTROL_OZELLIKLERIsField;
        private CS_KOD_PAKET_NN_FORM[] cS_KOD_PAKET_NN_FORMsField;
        private CS_KOD_PAKET cS_KOD_PAKET1Field;
        private CS_KOD_PAKET[] cS_KOD_PAKETsField;
        private int dAVA_KAYIT_SAYISIField;
        private int dAVA_KULLANICIField;
        private int iCRA_KAYIT_SAYISIField;
        private int iCRA_KULLANICIField;
        private int idField;

        private System.DateTime kAYIT_TARIHIField;
        private int mODUL_NOField;
        private string pAKET_ADIField;
        private System.Nullable<int> pARENT_IDField;
        private int sORUSTURMA_KAYIT_SAYISIField;
        private int sORUSTURMA_KULLANICIField;
        private short stampField;

        private TMYS_URUN_ANAHTARI[] tMYS_URUN_ANAHTARIsField;
        private System.Nullable<System.Guid> uNIQUE_IDField;

        /// <remarks/>
        public string ACIKLAMA
        {
            get
            {
                return this.aCIKLAMAField;
            }
            set
            {
                this.aCIKLAMAField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_KONTROL_OZELLIKLERI[] CS_KOD_KONTROL_OZELLIKLERIs
        {
            get
            {
                return this.cS_KOD_KONTROL_OZELLIKLERIsField;
            }
            set
            {
                this.cS_KOD_KONTROL_OZELLIKLERIsField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_PAKET_NN_FORM[] CS_KOD_PAKET_NN_FORMs
        {
            get
            {
                return this.cS_KOD_PAKET_NN_FORMsField;
            }
            set
            {
                this.cS_KOD_PAKET_NN_FORMsField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_PAKET CS_KOD_PAKET1
        {
            get
            {
                return this.cS_KOD_PAKET1Field;
            }
            set
            {
                this.cS_KOD_PAKET1Field = value;
            }
        }

        /// <remarks/>
        public CS_KOD_PAKET[] CS_KOD_PAKETs
        {
            get
            {
                return this.cS_KOD_PAKETsField;
            }
            set
            {
                this.cS_KOD_PAKETsField = value;
            }
        }

        /// <remarks/>
        public int DAVA_KAYIT_SAYISI
        {
            get
            {
                return this.dAVA_KAYIT_SAYISIField;
            }
            set
            {
                this.dAVA_KAYIT_SAYISIField = value;
            }
        }

        /// <remarks/>
        public int DAVA_KULLANICI
        {
            get
            {
                return this.dAVA_KULLANICIField;
            }
            set
            {
                this.dAVA_KULLANICIField = value;
            }
        }

        /// <remarks/>
        public int ICRA_KAYIT_SAYISI
        {
            get
            {
                return this.iCRA_KAYIT_SAYISIField;
            }
            set
            {
                this.iCRA_KAYIT_SAYISIField = value;
            }
        }

        /// <remarks/>
        public int ICRA_KULLANICI
        {
            get
            {
                return this.iCRA_KULLANICIField;
            }
            set
            {
                this.iCRA_KULLANICIField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KAYIT_TARIHI
        {
            get
            {
                return this.kAYIT_TARIHIField;
            }
            set
            {
                this.kAYIT_TARIHIField = value;
            }
        }

        /// <remarks/>
        public int MODUL_NO
        {
            get
            {
                return this.mODUL_NOField;
            }
            set
            {
                this.mODUL_NOField = value;
            }
        }

        /// <remarks/>
        public string PAKET_ADI
        {
            get
            {
                return this.pAKET_ADIField;
            }
            set
            {
                this.pAKET_ADIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PARENT_ID
        {
            get
            {
                return this.pARENT_IDField;
            }
            set
            {
                this.pARENT_IDField = value;
            }
        }

        /// <remarks/>
        public int SORUSTURMA_KAYIT_SAYISI
        {
            get
            {
                return this.sORUSTURMA_KAYIT_SAYISIField;
            }
            set
            {
                this.sORUSTURMA_KAYIT_SAYISIField = value;
            }
        }

        /// <remarks/>
        public int SORUSTURMA_KULLANICI
        {
            get
            {
                return this.sORUSTURMA_KULLANICIField;
            }
            set
            {
                this.sORUSTURMA_KULLANICIField = value;
            }
        }

        /// <remarks/>
        public short stamp
        {
            get
            {
                return this.stampField;
            }
            set
            {
                this.stampField = value;
            }
        }

        /// <remarks/>
        public TMYS_URUN_ANAHTARI[] TMYS_URUN_ANAHTARIs
        {
            get
            {
                return this.tMYS_URUN_ANAHTARIsField;
            }
            set
            {
                this.tMYS_URUN_ANAHTARIsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.Guid> UNIQUE_ID
        {
            get
            {
                return this.uNIQUE_IDField;
            }
            set
            {
                this.uNIQUE_IDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CS_KOD_PAKET_NN_FORM
    {
        private CS_KOD_FORM_LISTESI cS_KOD_FORM_LISTESIField;
        private CS_KOD_PAKET cS_KOD_PAKETField;
        private int fORM_IDField;
        private int pAKET_IDField;

        /// <remarks/>
        public CS_KOD_FORM_LISTESI CS_KOD_FORM_LISTESI
        {
            get
            {
                return this.cS_KOD_FORM_LISTESIField;
            }
            set
            {
                this.cS_KOD_FORM_LISTESIField = value;
            }
        }

        /// <remarks/>
        public CS_KOD_PAKET CS_KOD_PAKET
        {
            get
            {
                return this.cS_KOD_PAKETField;
            }
            set
            {
                this.cS_KOD_PAKETField = value;
            }
        }

        /// <remarks/>
        public int FORM_ID
        {
            get
            {
                return this.fORM_IDField;
            }
            set
            {
                this.fORM_IDField = value;
            }
        }

        /// <remarks/>
        public int PAKET_ID
        {
            get
            {
                return this.pAKET_IDField;
            }
            set
            {
                this.pAKET_IDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public CS_KOD_PAKET[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CS_KOD_PAKET[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "LicenceControlSoap", Namespace = "http://tempuri.org/")]
    public partial class LicenceControl : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        /// <remarks/>
        public LicenceControl()
        {
            this.Url = global::AvukatProLib.Properties.Settings.Default.AvukatProLib_AVPLicence_LicenceControl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        private System.Threading.SendOrPostCallback CheckAllOperationCompleted;

        private System.Threading.SendOrPostCallback CheckDBVersionOperationCompleted;
        private System.Threading.SendOrPostCallback CheckExeVersionOperationCompleted;
        private System.Threading.SendOrPostCallback CheckProductKeyOperationCompleted;

        private System.Threading.SendOrPostCallback CheckUpdaterVersionOperationCompleted;
        private System.Threading.SendOrPostCallback GetAllOperationCompleted;
        private System.Threading.SendOrPostCallback UpdateWebTablesOperationCompleted;
        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public event CheckAllCompletedEventHandler CheckAllCompleted;

        /// <remarks/>
        public event CheckDBVersionCompletedEventHandler CheckDBVersionCompleted;

        /// <remarks/>
        public event CheckExeVersionCompletedEventHandler CheckExeVersionCompleted;

        /// <remarks/>
        public event CheckProductKeyCompletedEventHandler CheckProductKeyCompleted;

        /// <remarks/>
        public event CheckUpdaterVersionCompletedEventHandler CheckUpdaterVersionCompleted;

        /// <remarks/>
        public event GetAllCompletedEventHandler GetAllCompleted;

        /// <remarks/>
        public event UpdateWebTablesCompletedEventHandler UpdateWebTablesCompleted;

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckAll", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result CheckAll(LisansBilgisi licenceInfo, VersionInfo versionInfo)
        {
            object[] results = this.Invoke("CheckAll", new object[] {
                        licenceInfo,
                        versionInfo});
            return ((Result)(results[0]));
        }

        /// <remarks/>
        public void CheckAllAsync(LisansBilgisi licenceInfo, VersionInfo versionInfo)
        {
            this.CheckAllAsync(licenceInfo, versionInfo, null);
        }

        /// <remarks/>
        public void CheckAllAsync(LisansBilgisi licenceInfo, VersionInfo versionInfo, object userState)
        {
            if ((this.CheckAllOperationCompleted == null))
            {
                this.CheckAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckAllOperationCompleted);
            }
            this.InvokeAsync("CheckAll", new object[] {
                        licenceInfo,
                        versionInfo}, this.CheckAllOperationCompleted, userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDBVersion", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TMYS_DB_SURUM CheckDBVersion(string dbVersion)
        {
            object[] results = this.Invoke("CheckDBVersion", new object[] {
                        dbVersion});
            return ((TMYS_DB_SURUM)(results[0]));
        }

        /// <remarks/>
        public void CheckDBVersionAsync(string dbVersion)
        {
            this.CheckDBVersionAsync(dbVersion, null);
        }

        /// <remarks/>
        public void CheckDBVersionAsync(string dbVersion, object userState)
        {
            if ((this.CheckDBVersionOperationCompleted == null))
            {
                this.CheckDBVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDBVersionOperationCompleted);
            }
            this.InvokeAsync("CheckDBVersion", new object[] {
                        dbVersion}, this.CheckDBVersionOperationCompleted, userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckExeVersion", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TMYS_EXE_SURUM CheckExeVersion(string exeVersion, out TMYS_DB_SURUM[] dbVersionList)
        {
            object[] results = this.Invoke("CheckExeVersion", new object[] {
                        exeVersion});
            dbVersionList = ((TMYS_DB_SURUM[])(results[1]));
            return ((TMYS_EXE_SURUM)(results[0]));
        }

        /// <remarks/>
        public void CheckExeVersionAsync(string exeVersion)
        {
            this.CheckExeVersionAsync(exeVersion, null);
        }

        /// <remarks/>
        public void CheckExeVersionAsync(string exeVersion, object userState)
        {
            if ((this.CheckExeVersionOperationCompleted == null))
            {
                this.CheckExeVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckExeVersionOperationCompleted);
            }
            this.InvokeAsync("CheckExeVersion", new object[] {
                        exeVersion}, this.CheckExeVersionOperationCompleted, userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckProductKey", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LisansBilgisi CheckProductKey(string productKey)
        {
            object[] results = this.Invoke("CheckProductKey", new object[] {
                        productKey});
            return ((LisansBilgisi)(results[0]));
        }

        /// <remarks/>
        public void CheckProductKeyAsync(string productKey)
        {
            this.CheckProductKeyAsync(productKey, null);
        }

        /// <remarks/>
        public void CheckProductKeyAsync(string productKey, object userState)
        {
            if ((this.CheckProductKeyOperationCompleted == null))
            {
                this.CheckProductKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckProductKeyOperationCompleted);
            }
            this.InvokeAsync("CheckProductKey", new object[] {
                        productKey}, this.CheckProductKeyOperationCompleted, userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUpdaterVersion", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TMYS_UPDATER_SURUM CheckUpdaterVersion(string updaterVersion)
        {
            object[] results = this.Invoke("CheckUpdaterVersion", new object[] {
                        updaterVersion});
            return ((TMYS_UPDATER_SURUM)(results[0]));
        }

        /// <remarks/>
        public void CheckUpdaterVersionAsync(string updaterVersion)
        {
            this.CheckUpdaterVersionAsync(updaterVersion, null);
        }

        /// <remarks/>
        public void CheckUpdaterVersionAsync(string updaterVersion, object userState)
        {
            if ((this.CheckUpdaterVersionOperationCompleted == null))
            {
                this.CheckUpdaterVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUpdaterVersionOperationCompleted);
            }
            this.InvokeAsync("CheckUpdaterVersion", new object[] {
                        updaterVersion}, this.CheckUpdaterVersionOperationCompleted, userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAll", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CS_KOD_PAKET[] GetAll(string productKey)
        {
            object[] results = this.Invoke("GetAll", new object[] {
                        productKey});
            return ((CS_KOD_PAKET[])(results[0]));
        }

        /// <remarks/>
        public void GetAllAsync(string productKey)
        {
            this.GetAllAsync(productKey, null);
        }

        /// <remarks/>
        public void GetAllAsync(string productKey, object userState)
        {
            if ((this.GetAllOperationCompleted == null))
            {
                this.GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperationCompleted);
            }
            this.InvokeAsync("GetAll", new object[] {
                        productKey}, this.GetAllOperationCompleted, userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateWebTables", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateWebTables(string productKey, string newExeVersion, string newDbVersion)
        {
            this.Invoke("UpdateWebTables", new object[] {
                        productKey,
                        newExeVersion,
                        newDbVersion});
        }

        /// <remarks/>
        public void UpdateWebTablesAsync(string productKey, string newExeVersion, string newDbVersion)
        {
            this.UpdateWebTablesAsync(productKey, newExeVersion, newDbVersion, null);
        }

        /// <remarks/>
        public void UpdateWebTablesAsync(string productKey, string newExeVersion, string newDbVersion, object userState)
        {
            if ((this.UpdateWebTablesOperationCompleted == null))
            {
                this.UpdateWebTablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateWebTablesOperationCompleted);
            }
            this.InvokeAsync("UpdateWebTables", new object[] {
                        productKey,
                        newExeVersion,
                        newDbVersion}, this.UpdateWebTablesOperationCompleted, userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }

        private void OnCheckAllOperationCompleted(object arg)
        {
            if ((this.CheckAllCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckAllCompleted(this, new CheckAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        private void OnCheckDBVersionOperationCompleted(object arg)
        {
            if ((this.CheckDBVersionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDBVersionCompleted(this, new CheckDBVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        private void OnCheckExeVersionOperationCompleted(object arg)
        {
            if ((this.CheckExeVersionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckExeVersionCompleted(this, new CheckExeVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        private void OnCheckProductKeyOperationCompleted(object arg)
        {
            if ((this.CheckProductKeyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckProductKeyCompleted(this, new CheckProductKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        private void OnCheckUpdaterVersionOperationCompleted(object arg)
        {
            if ((this.CheckUpdaterVersionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUpdaterVersionCompleted(this, new CheckUpdaterVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        private void OnGetAllOperationCompleted(object arg)
        {
            if ((this.GetAllCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        private void OnUpdateWebTablesOperationCompleted(object arg)
        {
            if ((this.UpdateWebTablesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateWebTablesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class LisansBilgisi
    {
        private string adSoyadField;
        private System.Nullable<int> davaKayitSayisiField;
        private System.Nullable<int> davaKullaniciSayisiField;
        private System.Nullable<int> icraKayitSayisiField;
        private System.Nullable<int> icraKullaniciSayisiField;
        private System.Nullable<System.DateTime> lisansBitisTarihiField;
        private int modulNoField;
        private string paketAdiField;
        private PaketBilgisi[] paketBilgileriField;
        private string productKeyField;
        private System.Nullable<int> sorusturmaKayitSayisiField;
        private System.Nullable<int> sorusturmaKullaniciSayisiField;

        /// <remarks/>
        public string AdSoyad
        {
            get
            {
                return this.adSoyadField;
            }
            set
            {
                this.adSoyadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> DavaKayitSayisi
        {
            get
            {
                return this.davaKayitSayisiField;
            }
            set
            {
                this.davaKayitSayisiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> DavaKullaniciSayisi
        {
            get
            {
                return this.davaKullaniciSayisiField;
            }
            set
            {
                this.davaKullaniciSayisiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> IcraKayitSayisi
        {
            get
            {
                return this.icraKayitSayisiField;
            }
            set
            {
                this.icraKayitSayisiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> IcraKullaniciSayisi
        {
            get
            {
                return this.icraKullaniciSayisiField;
            }
            set
            {
                this.icraKullaniciSayisiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> LisansBitisTarihi
        {
            get
            {
                return this.lisansBitisTarihiField;
            }
            set
            {
                this.lisansBitisTarihiField = value;
            }
        }

        /// <remarks/>
        public int ModulNo
        {
            get
            {
                return this.modulNoField;
            }
            set
            {
                this.modulNoField = value;
            }
        }

        /// <remarks/>
        public string PaketAdi
        {
            get
            {
                return this.paketAdiField;
            }
            set
            {
                this.paketAdiField = value;
            }
        }

        /// <remarks/>
        public PaketBilgisi[] PaketBilgileri
        {
            get
            {
                return this.paketBilgileriField;
            }
            set
            {
                this.paketBilgileriField = value;
            }
        }

        /// <remarks/>
        public string ProductKey
        {
            get
            {
                return this.productKeyField;
            }
            set
            {
                this.productKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SorusturmaKayitSayisi
        {
            get
            {
                return this.sorusturmaKayitSayisiField;
            }
            set
            {
                this.sorusturmaKayitSayisiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SorusturmaKullaniciSayisi
        {
            get
            {
                return this.sorusturmaKullaniciSayisiField;
            }
            set
            {
                this.sorusturmaKullaniciSayisiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class PaketBilgisi
    {
        private string aciklamaField;
        private PaketForm[] formListesiField;
        private string paketAdiField;

        /// <remarks/>
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }

        /// <remarks/>
        public PaketForm[] FormListesi
        {
            get
            {
                return this.formListesiField;
            }
            set
            {
                this.formListesiField = value;
            }
        }

        /// <remarks/>
        public string PaketAdi
        {
            get
            {
                return this.paketAdiField;
            }
            set
            {
                this.paketAdiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class PaketControl
    {
        private string aciklamaField;
        private bool aktifField;
        private bool gorunurField;
        private string kontrolAdiField;
        private PaketControl parentField;
        private string relativePathField;
        private bool sepette_GosterField;
        private string textField;
        private string tipAdiField;
        private int uniqueIdField;
        private bool yetkilendirmede_KullanField;

        /// <remarks/>
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }

        /// <remarks/>
        public bool Aktif
        {
            get
            {
                return this.aktifField;
            }
            set
            {
                this.aktifField = value;
            }
        }

        /// <remarks/>
        public bool Gorunur
        {
            get
            {
                return this.gorunurField;
            }
            set
            {
                this.gorunurField = value;
            }
        }

        /// <remarks/>
        public string KontrolAdi
        {
            get
            {
                return this.kontrolAdiField;
            }
            set
            {
                this.kontrolAdiField = value;
            }
        }

        /// <remarks/>
        public PaketControl Parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        /// <remarks/>
        public string RelativePath
        {
            get
            {
                return this.relativePathField;
            }
            set
            {
                this.relativePathField = value;
            }
        }

        /// <remarks/>
        public bool Sepette_Goster
        {
            get
            {
                return this.sepette_GosterField;
            }
            set
            {
                this.sepette_GosterField = value;
            }
        }

        /// <remarks/>
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        public string TipAdi
        {
            get
            {
                return this.tipAdiField;
            }
            set
            {
                this.tipAdiField = value;
            }
        }

        /// <remarks/>
        public int UniqueId
        {
            get
            {
                return this.uniqueIdField;
            }
            set
            {
                this.uniqueIdField = value;
            }
        }

        /// <remarks/>
        public bool Yetkilendirmede_Kullan
        {
            get
            {
                return this.yetkilendirmede_KullanField;
            }
            set
            {
                this.yetkilendirmede_KullanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class PaketForm
    {
        private string aciklamaField;
        private string formAdiField;

        private PaketControl[] kontrolListesiField;
        private string textField;

        /// <remarks/>
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }

        /// <remarks/>
        public string FormAdi
        {
            get
            {
                return this.formAdiField;
            }
            set
            {
                this.formAdiField = value;
            }
        }

        /// <remarks/>
        public PaketControl[] KontrolListesi
        {
            get
            {
                return this.kontrolListesiField;
            }
            set
            {
                this.kontrolListesiField = value;
            }
        }

        /// <remarks/>
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class Result
    {
        private TMYS_DB_SURUM dBVersionInfoField;
        private TMYS_EXE_SURUM exeVersionInfoField;
        private bool isDbUptoDateField;
        private bool isExeUptoDateField;
        private LisansBilgisi licenceInfoField;

        /// <remarks/>
        public TMYS_DB_SURUM DBVersionInfo
        {
            get
            {
                return this.dBVersionInfoField;
            }
            set
            {
                this.dBVersionInfoField = value;
            }
        }

        /// <remarks/>
        public TMYS_EXE_SURUM ExeVersionInfo
        {
            get
            {
                return this.exeVersionInfoField;
            }
            set
            {
                this.exeVersionInfoField = value;
            }
        }

        /// <remarks/>
        public bool IsDbUptoDate
        {
            get
            {
                return this.isDbUptoDateField;
            }
            set
            {
                this.isDbUptoDateField = value;
            }
        }

        /// <remarks/>
        public bool IsExeUptoDate
        {
            get
            {
                return this.isExeUptoDateField;
            }
            set
            {
                this.isExeUptoDateField = value;
            }
        }

        /// <remarks/>
        public LisansBilgisi LicenceInfo
        {
            get
            {
                return this.licenceInfoField;
            }
            set
            {
                this.licenceInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TMYS_DB_SURUM
    {
        private bool bIR_ONCEKI_SURUM_GEREKLIField;
        private System.DateTime cIKIS_TARIHIField;
        private byte dURUMField;
        private System.Guid eUIDField;
        private int idField;

        private string iNDIRME_ADRESIField;
        private System.DateTime kAYIT_TARIHIField;
        private string sURUM_NOTLARIField;
        private string sURUMField;

        /// <remarks/>
        public bool BIR_ONCEKI_SURUM_GEREKLI
        {
            get
            {
                return this.bIR_ONCEKI_SURUM_GEREKLIField;
            }
            set
            {
                this.bIR_ONCEKI_SURUM_GEREKLIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CIKIS_TARIHI
        {
            get
            {
                return this.cIKIS_TARIHIField;
            }
            set
            {
                this.cIKIS_TARIHIField = value;
            }
        }

        /// <remarks/>
        public byte DURUM
        {
            get
            {
                return this.dURUMField;
            }
            set
            {
                this.dURUMField = value;
            }
        }

        /// <remarks/>
        public System.Guid EUID
        {
            get
            {
                return this.eUIDField;
            }
            set
            {
                this.eUIDField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string INDIRME_ADRESI
        {
            get
            {
                return this.iNDIRME_ADRESIField;
            }
            set
            {
                this.iNDIRME_ADRESIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KAYIT_TARIHI
        {
            get
            {
                return this.kAYIT_TARIHIField;
            }
            set
            {
                this.kAYIT_TARIHIField = value;
            }
        }

        /// <remarks/>
        public string SURUM
        {
            get
            {
                return this.sURUMField;
            }
            set
            {
                this.sURUMField = value;
            }
        }

        /// <remarks/>
        public string SURUM_NOTLARI
        {
            get
            {
                return this.sURUM_NOTLARIField;
            }
            set
            {
                this.sURUM_NOTLARIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TMYS_EXE_SURUM
    {
        private bool bIR_ONCEKI_SURUM_GEREKLIField;
        private System.DateTime cIKIS_TARIHIField;
        private System.Nullable<int> dB_SURUM_IDField;
        private byte dURUMField;
        private System.Guid eUIDField;
        private int idField;

        private string iNDIRME_ADRESIField;
        private System.DateTime kAYIT_TARIHIField;
        private string sURUM_NOTLARIField;
        private string sURUMField;
        private TMYS_DB_SURUM tMYS_DB_SURUMField;

        /// <remarks/>
        public bool BIR_ONCEKI_SURUM_GEREKLI
        {
            get
            {
                return this.bIR_ONCEKI_SURUM_GEREKLIField;
            }
            set
            {
                this.bIR_ONCEKI_SURUM_GEREKLIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CIKIS_TARIHI
        {
            get
            {
                return this.cIKIS_TARIHIField;
            }
            set
            {
                this.cIKIS_TARIHIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> DB_SURUM_ID
        {
            get
            {
                return this.dB_SURUM_IDField;
            }
            set
            {
                this.dB_SURUM_IDField = value;
            }
        }

        /// <remarks/>
        public byte DURUM
        {
            get
            {
                return this.dURUMField;
            }
            set
            {
                this.dURUMField = value;
            }
        }

        /// <remarks/>
        public System.Guid EUID
        {
            get
            {
                return this.eUIDField;
            }
            set
            {
                this.eUIDField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string INDIRME_ADRESI
        {
            get
            {
                return this.iNDIRME_ADRESIField;
            }
            set
            {
                this.iNDIRME_ADRESIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KAYIT_TARIHI
        {
            get
            {
                return this.kAYIT_TARIHIField;
            }
            set
            {
                this.kAYIT_TARIHIField = value;
            }
        }

        /// <remarks/>
        public string SURUM
        {
            get
            {
                return this.sURUMField;
            }
            set
            {
                this.sURUMField = value;
            }
        }

        /// <remarks/>
        public string SURUM_NOTLARI
        {
            get
            {
                return this.sURUM_NOTLARIField;
            }
            set
            {
                this.sURUM_NOTLARIField = value;
            }
        }

        /// <remarks/>
        public TMYS_DB_SURUM TMYS_DB_SURUM
        {
            get
            {
                return this.tMYS_DB_SURUMField;
            }
            set
            {
                this.tMYS_DB_SURUMField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TMYS_MUSTERI
    {
        private string aD_SOYADField;
        private string bAKIM_DURUMUField;
        private string bAKIM_T_1Field;
        private string bAKIM_T_2Field;
        private string bEDASField;
        private string bIREYSEL_BAKIM_ARANANField;
        private int dAVA_KAYIT_SAYISIField;
        private int dAVA_KULLANICIField;
        private byte dURUMField;
        private string eGITIM_DURUMUField;
        private System.Guid eUIDField;
        private string gORUSME_NOT1Field;
        private string gORUSME_NOT2Field;
        private string gORUSME_NOT3Field;
        private int iCRA_KAYIT_SAYISIField;
        private int iCRA_KULLANICIField;
        private int idField;
        private System.DateTime kAYIT_TARIHIField;
        private string kLASOR_YERIField;
        private string kULLANICIField;
        private System.DateTime lISANS_BITIS_TARIHIField;
        private System.Nullable<int> mODUL_NOField;
        private string mUSTERI_TIPIField;
        private string sEHIRField;
        private string sERVERField;
        private string sON_DB_VERSIYONField;
        private string sON_EXE_VERSIYONField;
        private System.Nullable<System.DateTime> sON_GUNCELLEME_TARIHIField;
        private int sORUSTURMA_KAYIT_SAYISIField;
        private int sORUSTURMA_KULLANICIField;
        private System.DateTime sOZLESME_T_1Field;
        private string sOZLESME_T_2Field;
        private string sOZLESME_T_3Field;
        private System.Nullable<System.DateTime> tEKRAR_ARANACAKField;
        private TMYS_URUN_ANAHTARI[] tMYS_URUN_ANAHTARIsField;
        private string yAZILIM_TIPField;
        private string yAZILIM_TURUField;

        /// <remarks/>
        public string AD_SOYAD
        {
            get
            {
                return this.aD_SOYADField;
            }
            set
            {
                this.aD_SOYADField = value;
            }
        }

        /// <remarks/>
        public string BAKIM_DURUMU
        {
            get
            {
                return this.bAKIM_DURUMUField;
            }
            set
            {
                this.bAKIM_DURUMUField = value;
            }
        }

        /// <remarks/>
        public string BAKIM_T_1
        {
            get
            {
                return this.bAKIM_T_1Field;
            }
            set
            {
                this.bAKIM_T_1Field = value;
            }
        }

        /// <remarks/>
        public string BAKIM_T_2
        {
            get
            {
                return this.bAKIM_T_2Field;
            }
            set
            {
                this.bAKIM_T_2Field = value;
            }
        }

        /// <remarks/>
        public string BEDAS
        {
            get
            {
                return this.bEDASField;
            }
            set
            {
                this.bEDASField = value;
            }
        }

        /// <remarks/>
        public string BIREYSEL_BAKIM_ARANAN
        {
            get
            {
                return this.bIREYSEL_BAKIM_ARANANField;
            }
            set
            {
                this.bIREYSEL_BAKIM_ARANANField = value;
            }
        }

        /// <remarks/>
        public int DAVA_KAYIT_SAYISI
        {
            get
            {
                return this.dAVA_KAYIT_SAYISIField;
            }
            set
            {
                this.dAVA_KAYIT_SAYISIField = value;
            }
        }

        /// <remarks/>
        public int DAVA_KULLANICI
        {
            get
            {
                return this.dAVA_KULLANICIField;
            }
            set
            {
                this.dAVA_KULLANICIField = value;
            }
        }

        /// <remarks/>
        public byte DURUM
        {
            get
            {
                return this.dURUMField;
            }
            set
            {
                this.dURUMField = value;
            }
        }

        /// <remarks/>
        public string EGITIM_DURUMU
        {
            get
            {
                return this.eGITIM_DURUMUField;
            }
            set
            {
                this.eGITIM_DURUMUField = value;
            }
        }

        /// <remarks/>
        public System.Guid EUID
        {
            get
            {
                return this.eUIDField;
            }
            set
            {
                this.eUIDField = value;
            }
        }

        /// <remarks/>
        public string GORUSME_NOT1
        {
            get
            {
                return this.gORUSME_NOT1Field;
            }
            set
            {
                this.gORUSME_NOT1Field = value;
            }
        }

        /// <remarks/>
        public string GORUSME_NOT2
        {
            get
            {
                return this.gORUSME_NOT2Field;
            }
            set
            {
                this.gORUSME_NOT2Field = value;
            }
        }

        /// <remarks/>
        public string GORUSME_NOT3
        {
            get
            {
                return this.gORUSME_NOT3Field;
            }
            set
            {
                this.gORUSME_NOT3Field = value;
            }
        }

        /// <remarks/>
        public int ICRA_KAYIT_SAYISI
        {
            get
            {
                return this.iCRA_KAYIT_SAYISIField;
            }
            set
            {
                this.iCRA_KAYIT_SAYISIField = value;
            }
        }

        /// <remarks/>
        public int ICRA_KULLANICI
        {
            get
            {
                return this.iCRA_KULLANICIField;
            }
            set
            {
                this.iCRA_KULLANICIField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KAYIT_TARIHI
        {
            get
            {
                return this.kAYIT_TARIHIField;
            }
            set
            {
                this.kAYIT_TARIHIField = value;
            }
        }

        /// <remarks/>
        public string KLASOR_YERI
        {
            get
            {
                return this.kLASOR_YERIField;
            }
            set
            {
                this.kLASOR_YERIField = value;
            }
        }

        /// <remarks/>
        public string KULLANICI
        {
            get
            {
                return this.kULLANICIField;
            }
            set
            {
                this.kULLANICIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime LISANS_BITIS_TARIHI
        {
            get
            {
                return this.lISANS_BITIS_TARIHIField;
            }
            set
            {
                this.lISANS_BITIS_TARIHIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> MODUL_NO
        {
            get
            {
                return this.mODUL_NOField;
            }
            set
            {
                this.mODUL_NOField = value;
            }
        }

        /// <remarks/>
        public string MUSTERI_TIPI
        {
            get
            {
                return this.mUSTERI_TIPIField;
            }
            set
            {
                this.mUSTERI_TIPIField = value;
            }
        }

        /// <remarks/>
        public string SEHIR
        {
            get
            {
                return this.sEHIRField;
            }
            set
            {
                this.sEHIRField = value;
            }
        }

        /// <remarks/>
        public string SERVER
        {
            get
            {
                return this.sERVERField;
            }
            set
            {
                this.sERVERField = value;
            }
        }

        /// <remarks/>
        public string SON_DB_VERSIYON
        {
            get
            {
                return this.sON_DB_VERSIYONField;
            }
            set
            {
                this.sON_DB_VERSIYONField = value;
            }
        }

        /// <remarks/>
        public string SON_EXE_VERSIYON
        {
            get
            {
                return this.sON_EXE_VERSIYONField;
            }
            set
            {
                this.sON_EXE_VERSIYONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> SON_GUNCELLEME_TARIHI
        {
            get
            {
                return this.sON_GUNCELLEME_TARIHIField;
            }
            set
            {
                this.sON_GUNCELLEME_TARIHIField = value;
            }
        }

        /// <remarks/>
        public int SORUSTURMA_KAYIT_SAYISI
        {
            get
            {
                return this.sORUSTURMA_KAYIT_SAYISIField;
            }
            set
            {
                this.sORUSTURMA_KAYIT_SAYISIField = value;
            }
        }

        /// <remarks/>
        public int SORUSTURMA_KULLANICI
        {
            get
            {
                return this.sORUSTURMA_KULLANICIField;
            }
            set
            {
                this.sORUSTURMA_KULLANICIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime SOZLESME_T_1
        {
            get
            {
                return this.sOZLESME_T_1Field;
            }
            set
            {
                this.sOZLESME_T_1Field = value;
            }
        }

        /// <remarks/>
        public string SOZLESME_T_2
        {
            get
            {
                return this.sOZLESME_T_2Field;
            }
            set
            {
                this.sOZLESME_T_2Field = value;
            }
        }

        /// <remarks/>
        public string SOZLESME_T_3
        {
            get
            {
                return this.sOZLESME_T_3Field;
            }
            set
            {
                this.sOZLESME_T_3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> TEKRAR_ARANACAK
        {
            get
            {
                return this.tEKRAR_ARANACAKField;
            }
            set
            {
                this.tEKRAR_ARANACAKField = value;
            }
        }

        /// <remarks/>
        public TMYS_URUN_ANAHTARI[] TMYS_URUN_ANAHTARIs
        {
            get
            {
                return this.tMYS_URUN_ANAHTARIsField;
            }
            set
            {
                this.tMYS_URUN_ANAHTARIsField = value;
            }
        }

        /// <remarks/>
        public string YAZILIM_TIP
        {
            get
            {
                return this.yAZILIM_TIPField;
            }
            set
            {
                this.yAZILIM_TIPField = value;
            }
        }

        /// <remarks/>
        public string YAZILIM_TURU
        {
            get
            {
                return this.yAZILIM_TURUField;
            }
            set
            {
                this.yAZILIM_TURUField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TMYS_UPDATER_SURUM
    {
        private bool bIR_ONCEKI_SURUM_GEREKLIField;
        private System.DateTime cIKIS_TARIHIField;
        private byte dURUMField;
        private System.Guid eUIDField;
        private int idField;

        private string iNDIRME_ADRESIField;
        private System.DateTime kAYIT_TARIHIField;
        private string sURUM_NOTLARIField;
        private string sURUMField;

        /// <remarks/>
        public bool BIR_ONCEKI_SURUM_GEREKLI
        {
            get
            {
                return this.bIR_ONCEKI_SURUM_GEREKLIField;
            }
            set
            {
                this.bIR_ONCEKI_SURUM_GEREKLIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CIKIS_TARIHI
        {
            get
            {
                return this.cIKIS_TARIHIField;
            }
            set
            {
                this.cIKIS_TARIHIField = value;
            }
        }

        /// <remarks/>
        public byte DURUM
        {
            get
            {
                return this.dURUMField;
            }
            set
            {
                this.dURUMField = value;
            }
        }

        /// <remarks/>
        public System.Guid EUID
        {
            get
            {
                return this.eUIDField;
            }
            set
            {
                this.eUIDField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string INDIRME_ADRESI
        {
            get
            {
                return this.iNDIRME_ADRESIField;
            }
            set
            {
                this.iNDIRME_ADRESIField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KAYIT_TARIHI
        {
            get
            {
                return this.kAYIT_TARIHIField;
            }
            set
            {
                this.kAYIT_TARIHIField = value;
            }
        }

        /// <remarks/>
        public string SURUM
        {
            get
            {
                return this.sURUMField;
            }
            set
            {
                this.sURUMField = value;
            }
        }

        /// <remarks/>
        public string SURUM_NOTLARI
        {
            get
            {
                return this.sURUM_NOTLARIField;
            }
            set
            {
                this.sURUM_NOTLARIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TMYS_URUN_ANAHTARI
    {
        private CS_KOD_PAKET cS_KOD_PAKETField;
        private byte dURUMField;
        private System.Guid eUIDField;
        private int idField;

        private System.DateTime kAYIT_TARIHIField;
        private string mUSTERI_ANAHTARIField;
        private int mUSTERI_IDField;
        private System.Nullable<int> pAKET_IDField;
        private TMYS_MUSTERI tMYS_MUSTERIField;
        private string uRUN_ANAHTARIField;

        /// <remarks/>
        public CS_KOD_PAKET CS_KOD_PAKET
        {
            get
            {
                return this.cS_KOD_PAKETField;
            }
            set
            {
                this.cS_KOD_PAKETField = value;
            }
        }

        /// <remarks/>
        public byte DURUM
        {
            get
            {
                return this.dURUMField;
            }
            set
            {
                this.dURUMField = value;
            }
        }

        /// <remarks/>
        public System.Guid EUID
        {
            get
            {
                return this.eUIDField;
            }
            set
            {
                this.eUIDField = value;
            }
        }

        /// <remarks/>
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public System.DateTime KAYIT_TARIHI
        {
            get
            {
                return this.kAYIT_TARIHIField;
            }
            set
            {
                this.kAYIT_TARIHIField = value;
            }
        }

        /// <remarks/>
        public string MUSTERI_ANAHTARI
        {
            get
            {
                return this.mUSTERI_ANAHTARIField;
            }
            set
            {
                this.mUSTERI_ANAHTARIField = value;
            }
        }

        /// <remarks/>
        public int MUSTERI_ID
        {
            get
            {
                return this.mUSTERI_IDField;
            }
            set
            {
                this.mUSTERI_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PAKET_ID
        {
            get
            {
                return this.pAKET_IDField;
            }
            set
            {
                this.pAKET_IDField = value;
            }
        }

        /// <remarks/>
        public TMYS_MUSTERI TMYS_MUSTERI
        {
            get
            {
                return this.tMYS_MUSTERIField;
            }
            set
            {
                this.tMYS_MUSTERIField = value;
            }
        }

        /// <remarks/>
        public string URUN_ANAHTARI
        {
            get
            {
                return this.uRUN_ANAHTARIField;
            }
            set
            {
                this.uRUN_ANAHTARIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class VersionInfo
    {
        private TMYS_DB_SURUM dBVersionInfoField;
        private string exeVersionField;

        /// <remarks/>
        public TMYS_DB_SURUM DBVersionInfo
        {
            get
            {
                return this.dBVersionInfoField;
            }
            set
            {
                this.dBVersionInfoField = value;
            }
        }

        /// <remarks/>
        public string ExeVersion
        {
            get
            {
                return this.exeVersionField;
            }
            set
            {
                this.exeVersionField = value;
            }
        }
    }
}

#pragma warning restore 1591