//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
//
#pragma warning disable 1591

namespace AvukatProRaporlar.Raport.Util.DovizAPI
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GunlukKurGetirCompletedEventHandler(object sender, GunlukKurGetirCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "AVP_NG_DOVIZ_SOAP_API_NENCSoap", Namespace = "http://tempuri.org/")]
    public partial class AVP_NG_DOVIZ_SOAP_API_NENC : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        /// <remarks/>
        public AVP_NG_DOVIZ_SOAP_API_NENC()
        {
            this.Url = global::AvukatProRaporlar.Raport.Util.Properties.Settings.Default.AvukatProRaporlar_Raport_Util_com_avukatpro_www_AVP_NG_DOVIZ_SOAP_API_NENC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        private System.Threading.SendOrPostCallback GunlukKurGetirOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public event GunlukKurGetirCompletedEventHandler GunlukKurGetirCompleted;

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GunlukKurGetir", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GunlukKurGetir(string password, System.DateTime gun)
        {
            object[] results = this.Invoke("GunlukKurGetir", new object[] {
                        password,
                        gun});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GunlukKurGetirAsync(string password, System.DateTime gun)
        {
            this.GunlukKurGetirAsync(password, gun, null);
        }

        /// <remarks/>
        public void GunlukKurGetirAsync(string password, System.DateTime gun, object userState)
        {
            if ((this.GunlukKurGetirOperationCompleted == null))
            {
                this.GunlukKurGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGunlukKurGetirOperationCompleted);
            }
            this.InvokeAsync("GunlukKurGetir", new object[] {
                        password,
                        gun}, this.GunlukKurGetirOperationCompleted, userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }

        private void OnGunlukKurGetirOperationCompleted(object arg)
        {
            if ((this.GunlukKurGetirCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GunlukKurGetirCompleted(this, new GunlukKurGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GunlukKurGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        internal GunlukKurGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        private object[] results;

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591